/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:54:24 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class BBZeroingWeakReference, NSString;

@interface BBAssertion : NSObject {

	BBZeroingWeakReference* _delegate;
	NSString* _identifier;
	unsigned _transactionID;

}
-(void)dealloc;
-(id)identifier;
-(id)initWithDelegate:(id)arg1 identifier:(id)arg2 ;
-(void)increaseOrIgnoreTransactionID:(unsigned)arg1 ;
-(unsigned)transactionID;
@end

