/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:54:24 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BulletinBoard/BulletinBoard-Structs.h>
#import <CoreFoundation/NSCopying.h>
#import <CoreFoundation/NSCoding.h>

@class NSCountedSet, NSMutableDictionary;

@interface BBAttachments : NSObject <NSCopying, NSCoding> {

	int primaryType;
	NSCountedSet* _additionalAttachments;
	NSMutableDictionary* _clientSideComposedImageInfos;

}

@property (assign,nonatomic) int primaryType; 
@property (nonatomic,retain) NSCountedSet * additionalAttachments;                            //@synthesize additionalAttachments=_additionalAttachments - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * clientSideComposedImageInfos;              //@synthesize clientSideComposedImageInfos=_clientSideComposedImageInfos - In the implementation block
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)copyWithZone:(NSZone)arg1 ;
-(int)primaryType;
-(unsigned)numberOfAdditionalAttachments;
-(unsigned)numberOfAdditionalAttachmentsOfType:(int)arg1 ;
-(void)setPrimaryType:(int)arg1 ;
-(void)addAttachmentOfType:(int)arg1 ;
-(BOOL)isEqualToAttachments:(id)arg1 ;
-(id)additionalAttachments;
-(void)setAdditionalAttachments:(id)arg1 ;
-(id)clientSideComposedImageInfos;
-(void)setClientSideComposedImageInfos:(id)arg1 ;
@end

