/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:54:24 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <BulletinBoard/ABPredicateDelegate.h>

@interface BBNotificationBehaviorFavoritesListDelegate : NSObject <ABPredicateDelegate> {

	/*^block*/ id _handlerBlock;

}
-(BOOL)predicateShouldContinue:(id)arg1 ;
-(BOOL)predicateShouldContinue:(id)arg1 afterFindingRecord:(void*)arg2 ;
-(void)dealloc;
-(id)initWithHandlerBlock:(/*^block*/ id)arg1 ;
@end

