/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:54:24 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

#import <CoreGraphics/CoreGraphics.h>

typedef struct {
	unsigned pushDataProvider : 1;
	unsigned dataProviderDidLoad : 1;
	unsigned bulletinsWithRequestParameters : 1;
	unsigned bulletinsFilteredByDEPRECATED : 1;
	unsigned bulletinsFilteredByEnabledSectionsDEPRECATED : 1;
	unsigned clearedInfoAndBulletinsForClearingAllBulletins : 1;
	unsigned clearedInfoForBulletins : 1;
	unsigned clearedInfoForBulletinsDEPRECATED : 1;
	unsigned attachmentPNGDataForRecordID : 1;
	unsigned attachmentAspectRatioForRecordID : 1;
	unsigned defaultSectionInfo : 1;
	unsigned defaultSubsectionInfos : 1;
	unsigned displayNameForSubsectionID : 1;
	unsigned sectionParameters : 1;
	unsigned migrateSectionInfo : 1;
	unsigned sectionDisplayName : 1;
	unsigned sectionIcon : 1;
	unsigned sectionIconDataDEPRECATED : 1;
	unsigned receiveMessageWithName : 1;
	unsigned noteSectionInfoDidChange : 1;
	unsigned syncBulletinDismissal : 1;
	unsigned handleBulletinActionResponse : 1;
} SCD_Struct_BB2;

