/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface PLProgressStack : NSObject
{
    _Bool notifyUsingAssetsdNotificationCenter;
    CGFloat currentMultiplier;
    CGFloat currentTotal;
    id delegate;
    NSMutableArray *multipliers;
    NSString *mediaPathString;
}

+ (id)unarchiveFromDictionary:(id)arg1;
@property(retain, nonatomic) NSString *mediaPathString; // @synthesize mediaPathString;
@property(nonatomic) _Bool notifyUsingAssetsdNotificationCenter; // @synthesize notifyUsingAssetsdNotificationCenter;
@property(nonatomic) CGFloat currentTotal; // @synthesize currentTotal;
@property(retain, nonatomic) NSMutableArray *multipliers; // @synthesize multipliers;
@property(nonatomic) CGFloat currentMultiplier; // @synthesize currentMultiplier;
@property(nonatomic) id delegate; // @synthesize delegate;
- (id)archiveToDictionary;
- (void)setCurrentMediaPath:(id)arg1;
- (void)popAndUpdate;
- (void)updateProgress:(CGFloat)arg1;
- (void)dealloc;
- (CGFloat)totalProgress:(CGFloat)arg1;
- (void)pop;
- (void)push:(CGFloat)arg1;
- (id)initWithDelegate:(id)arg1;

@end

