/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface PLSlalomRangeMapper : NSObject
{
    NSMutableArray *_originalLengths;
    NSMutableArray *_scaledLengths;
    NSMutableArray *_scaledRegions;
}

- (void)enumerateScaledRegionsUsingBlock:(id)arg1;
- (void)markScaledRegionWithRate:(CGFloat)arg1 rampInStartTime:(CGFloat)arg2 rampInEndTime:(CGFloat)arg3 rampOutStartTime:(CGFloat)arg4 rampOutEndTime:(CGFloat)arg5;
- (CGFloat)_mapTime:(CGFloat)arg1 fromLengths:(id)arg2 toLengths:(id)arg3;
- (CGFloat)originalTimeForScaledTime:(CGFloat)arg1;
- (CGFloat)scaledTimeForOriginalTime:(CGFloat)arg1;
- (void)addNextRange:(CGFloat)arg1 scaledLength:(CGFloat)arg2;
- (void)dealloc;
- (id)init;

@end

