/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:16 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface SPDomainManager : NSObject
+(id)defaultManager;
-(void)registerApplication:(id)arg1 withCategories:(id)arg2 ;
-(void)notifyIndexer;
-(void)_removeAllDomainsForDisplayIdentifier:(id)arg1 ;
-(void)applicationWasUninstalled:(id)arg1 ;
@end

