/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:16 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSMutableString, NSNumber;

@interface SPPhoneticEncoder : NSObject {

	NSString* _source;
	NSMutableString* _primary;
	NSMutableString* _alternate;
	int _idx;
	NSNumber* _slavoGermanic;

}
-(BOOL)isAnyString:(id)arg1 atIndex:(int)arg2 ;
-(BOOL)isVowelAtIndex:(int)arg1 ;
-(void)addPrimary:(id)arg1 alternate:(id)arg2 ;
-(BOOL)isSlavoGermanic;
-(id)codesForString:(id)arg1 ;
-(void)add:(id)arg1 ;
@end

