/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:16 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber, NSDate;

@interface SPRecord : NSManagedObject

@property (nonatomic,@dynamic,retain) NSString * actionURL; 
@property (nonatomic,@dynamic,retain) NSString * auxsubtitle; 
@property (nonatomic,@dynamic,retain) NSString * auxtitle; 
@property (nonatomic,@dynamic,retain) NSString * content; 
@property (nonatomic,@dynamic,retain) NSNumber * cxid; 
@property (nonatomic,@dynamic,retain) NSDate * date; 
@property (nonatomic,@dynamic,retain) NSString * extid; 
@property (nonatomic,@dynamic,retain) NSString * subtitle; 
@property (nonatomic,@dynamic,retain) NSString * summary; 
@property (nonatomic,@dynamic,retain) NSString * title; 
@property (nonatomic,@dynamic,retain) NSNumber * generation; 
@end

