/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:16 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/Search.framework/Search
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <ProtocolBuffer/PBDataReader.h>

@interface SPSearchResultDeserializer : PBDataReader {

	unsigned _byteVector;
	BOOL _munmapAtDealloc;

}
-(void)dealloc;
-(BOOL)deserializeNextSection:(id*)arg1 ;
-(id)initWithMappedRegion:(unsigned)arg1 length:(unsigned)arg2 ;
-(id)initWithMallocRegion:(unsigned)arg1 length:(unsigned)arg2 ;
-(id)initWithSerializer:(id)arg1 ;
@end

