//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString;

@interface CKMessageStatus : NSObject
{
    int _status;
    NSString *_guid;
    NSAttributedString *_attributedTranscriptText;
    id <CKMessage> _message;
}

+ (id)thePastDateFormatter;
+ (id)thisWeekRelativeDateFormatter;
+ (id)todayDateFormatter;
+ (id)statusWithType:(int)arg1 message:(id)arg2;
@property(retain, nonatomic) id <CKMessage> message; // @synthesize message=_message;
@property(nonatomic) int status; // @synthesize status=_status;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (void)significantTimeChange:(id)arg1;
- (id)now;
@property(readonly, nonatomic) NSAttributedString *attributedTranscriptText; // @synthesize attributedTranscriptText=_attributedTranscriptText;
@property(readonly, nonatomic) NSString *guid; // @synthesize guid=_guid;
- (id)initWithStatus:(int)arg1 message:(id)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;

@end

