//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKPreferredServiceManager.h>

@interface CKMessagesAppPreferredServiceManager : CKPreferredServiceManager
{
}

- (id)preferredServiceForConversation:(id)arg1 newComposition:(_Bool)arg2 checkWithServer:(_Bool)arg3 error:(char *)arg4;
- (unsigned long long)_optionsForRecipients:(id)arg1;
- (unsigned long long)__optionsForConversation:(id)arg1;

@end

