/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "ChatKit-Structs.h"
#import <UIKit/UIView.h>

@class UIImageView;

@interface CKProgressBar : UIView {
	UIImageView* _well;
	UIImageView* _fill;
	CGFloat _progressValue;
}
@property(assign, nonatomic) CGFloat progressValue;
+(CGFloat)defaultHeight;
+(CGFloat)_minFillWidth;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(void)layoutSubviews;
-(void)_setupFillFrame;
@end

