//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CKEntity, NSString;

@interface CKTypingIndicator : NSObject
{
    _Bool _hasAppeared;
    id <CKMessage> _message;
}

@property(nonatomic) _Bool hasAppeared; // @synthesize hasAppeared=_hasAppeared;
@property(retain, nonatomic) id <CKMessage> message; // @synthesize message=_message;
@property(readonly, nonatomic) CKEntity *sender;
@property(readonly, nonatomic) NSString *guid;
- (id)initWithMessage:(id)arg1;
- (void)dealloc;
- (_Bool)isEqual:(id)arg1;

@end

