/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIButton.h>

@interface CAMFlipButton : UIButton
{
}

+ (id)flipButton;
- (id)_flipImage;
- (id)initWithCoder:(id)aDecoder;
- (id)initWithFrame:(CGRect)frame;
- (void)_commonCAMFlipButtonInitialization;

@end

