/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIButton.h>

@class CAMButtonLabel;

@interface CAMHDRButton : UIButton
{
    BOOL _on;
    long long _orientation;
    CAMButtonLabel *__hdrLabel;
    CAMButtonLabel *__offLabel;
    CAMButtonLabel *__onLabel;
}

@property(readonly, nonatomic) CAMButtonLabel *_onLabel; // @synthesize _onLabel=__onLabel;
@property(readonly, nonatomic) CAMButtonLabel *_offLabel; // @synthesize _offLabel=__offLabel;
@property(readonly, nonatomic) CAMButtonLabel *_hdrLabel; // @synthesize _hdrLabel=__hdrLabel;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(nonatomic, getter=isOn) BOOL on; // @synthesize on=_on;
- (void)_updateFromOrientationChangeAnimated:(BOOL)animated;
- (void)_updateFrameFromOrientation;
- (CGAffineTransform)_transformForOrientation:(long long)orientation;
- (void)_updateLabelsFromOrientation;
- (void)_updateFromOnState;
- (void)setOrientation:(long long)orientation animated:(BOOL)animated;
- (void)layoutSubviews;
- (void)_layoutForLandscapeOrientation;
- (void)_layoutForPortraitOrientation;
- (CGSize)sizeThatFits:(CGSize)size;
- (void)dealloc;
- (id)initWithCoder:(id)aDecoder;
- (id)initWithFrame:(CGRect)frame;
- (void)_commonCAMHDRButtonInitialization;

@end

