/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <PhotoLibrary/PLPhotoTileViewController.h>

@interface PLPhotoTileViewController (PLImagePickerUtils)
- (long long)_imageOrientation;
- (id)_newOriginalImageForPickerFromCachedData;
@end

