//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class UIWebView;

@interface AdSupportAboutController : UIViewController <UIWebViewDelegate>
{
    UIWebView *_webView;
}

@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void)viewWillDisappear;
- (BOOL)isAdSupportURLReachable;
- (void)viewWillAppear:(BOOL)arg1;
- (id)localizedStringFromDictionary:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)showErrorAlert;
- (void)dealloc;
- (id)init;

@end

