//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class NSMutableArray, NSMutableDictionary, UIActionSheet, UIAlertView;

@interface AutomaticContentDownloadController : PSListController
{
    UIAlertView *_locationConfirmationAlert;
    UIActionSheet *_locationConfirmationSheet;
    BOOL _hasLocationApps;
    NSMutableArray *_applications;
    NSMutableDictionary *_applicationStates;
}

@property(retain, nonatomic) NSMutableDictionary *applicationStates; // @synthesize applicationStates=_applicationStates;
@property(retain, nonatomic) NSMutableArray *applications; // @synthesize applications=_applications;
- (BOOL)_appObjectIsLocApp:(id)arg1;
- (void)confirmationClickedButtonAtIndex:(int)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)applicationEnabled:(id)arg1;
- (void)setApplicationEnabled:(id)arg1 forSpecifier:(id)arg2;
- (id)backgroundRefreshState:(id)arg1;
- (void)setBackgroundRefreshState:(id)arg1 withSpecifier:(id)arg2;
- (void)_reallySetBackgroundRefreshState:(BOOL)arg1;
- (id)specifiers;
- (void)migrateApplication:(id)arg1;
- (id)whitelist;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

