//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSSwitchTableCell.h"

@class UIImageView;

@interface BackgroundAppUsageIndicatorCell : PSSwitchTableCell
{
    UIImageView *_usageIndicator;
}

- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

