//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSEditableListController.h"

@class BBSectionInfo, NSDictionary, NSObject<OS_dispatch_semaphore>, PSSpecifier;

@interface BulletinBoardController : PSEditableListController
{
    int _inCount;
    int _orderRule;
    PSSpecifier *_inGroupEmptyCell;
    PSSpecifier *_outGroupEmptyCell;
    unsigned int _cellChangeAction;
    NSObject<OS_dispatch_semaphore> *_loadSem;
    int _todaySection;
    int _inNotificationCenterSection;
    int _outOfNotificationCenterSection;
    BOOL _loadingFromBBGateway;
    BOOL _telephonyDevice;
    unsigned int _dndDataTypes;
    NSDictionary *_urlResourceDictionary;
    BBSectionInfo *_todaySectionInfo;
    BBSectionInfo *_stocksSectionInfo;
    BBSectionInfo *_attributionSectionInfo;
}

@property(retain, nonatomic) BBSectionInfo *attributionSectionInfo; // @synthesize attributionSectionInfo=_attributionSectionInfo;
@property(retain, nonatomic) BBSectionInfo *stocksSectionInfo; // @synthesize stocksSectionInfo=_stocksSectionInfo;
@property(retain, nonatomic) BBSectionInfo *todaySectionInfo; // @synthesize todaySectionInfo=_todaySectionInfo;
@property(nonatomic) BOOL telephonyDevice; // @synthesize telephonyDevice=_telephonyDevice;
@property(retain, nonatomic) NSDictionary *urlResourceDictionary; // @synthesize urlResourceDictionary=_urlResourceDictionary;
@property(nonatomic) unsigned int dndDataTypes; // @synthesize dndDataTypes=_dndDataTypes;
@property BOOL loadingFromBBGateway; // @synthesize loadingFromBBGateway=_loadingFromBBGateway;
@property(retain, nonatomic) PSSpecifier *outGroupEmptyCell; // @synthesize outGroupEmptyCell=_outGroupEmptyCell;
@property(retain, nonatomic) PSSpecifier *inGroupEmptyCell; // @synthesize inGroupEmptyCell=_inGroupEmptyCell;
- (void)_loadSegmentCellState:(int)arg1;
- (void)_reloadSections;
- (id)cmasAlertsValue:(id)arg1;
- (void)setCmasAlertState:(id)arg1 forSpecifier:(id)arg2;
- (id)todaySectionState:(id)arg1;
- (void)setTodaySectionState:(id)arg1 specifier:(id)arg2;
- (void)_checkAndUpdateAttributionState;
- (id)trafficConditionsState:(id)arg1;
- (void)setTrafficConditionsState:(id)arg1 forSpecifier:(id)arg2;
- (void)_loadSections;
- (void)_reallyLoadSections:(id)arg1 chronologicalSections:(id)arg2;
- (id)_filterSuppressedSections:(id)arg1;
- (void)_pushControllerAtIndexPath:(id)arg1;
- (void)_clearSections;
- (id)_sectionUIDescriptions;
- (id)_sectionDescriptions;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)adjustEmptyCells;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (int)indexOfBBSectionInfoForIndexPath:(id)arg1;
- (void)moveSpecifier:(id)arg1 toOnPosition:(BOOL)arg2;
- (id)_sectionIDs;
- (void)setOrderingMode:(id)arg1 specifier:(id)arg2;
- (id)orderingMode:(id)arg1;
- (void)createGroupIndices;
- (void)setEnabledInLockScreen:(id)arg1 specifier:(id)arg2;
- (id)enabledInLockScreen:(id)arg1;
- (id)specifiers;
- (void)loadedDNDData:(unsigned int)arg1;
- (id)sectionsOrderedByInOutState:(id)arg1;
- (void)handleURL:(id)arg1;
- (id)inOutSpecifiersFrom:(id)arg1;
- (void)_addRegionalAlertGroupToSpecifiers:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)notifyFMFOfChanges;
- (void)notifyGamedOfChanges:(unsigned int)arg1 mask:(unsigned int)arg2;
- (void)setDesiredVerticalContentOffset:(float)arg1;
- (void)profileNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

