//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

#import "UIPopoverControllerDelegate.h"

@class NSIndexPath, NSTimer, PSSpecifier, UIPopoverController;

@interface DateTimeController : PSListController <UIPopoverControllerDelegate>
{
    UIPopoverController *_setDateAndTimePopoverController;
    NSIndexPath *_setDateAndTimeIndexPath;
    NSTimer *_timer;
    BOOL _localeForces24HourTime;
    BOOL _setDateAndTimePopoverShouldRePresent;
    struct __CFDateFormatter *_dateFormatter;
    struct __CFDateFormatter *_timeFormatter;
    PSSpecifier *_timeZoneSpecifier;
    PSSpecifier *_timePickerSpecifier;
    PSSpecifier *_currentTimeSpecifier;
}

@property(retain) PSSpecifier *currentTimeSpecifier; // @synthesize currentTimeSpecifier=_currentTimeSpecifier;
@property(retain) PSSpecifier *timePickerSpecifier; // @synthesize timePickerSpecifier=_timePickerSpecifier;
@property(retain) PSSpecifier *timeZoneSpecifier; // @synthesize timeZoneSpecifier=_timeZoneSpecifier;
- (void)stopTimer;
- (void)startTimer;
- (id)currentDateString;
- (id)currentTimeString;
- (void)_createDateTimeFormatters;
- (void)_updateCurrentTime;
- (void)setTimeZoneValue:(id)arg1 specifier:(id)arg2;
- (id)timeZoneValue:(id)arg1;
- (void)set24HourTime:(id)arg1 specifier:(id)arg2;
- (id)is24HourTime:(id)arg1;
- (void)setUseAutomaticTime:(id)arg1 specifier:(id)arg2;
- (id)useAutomaticTime:(id)arg1;
- (id)valueForTime:(id)arg1;
- (BOOL)shouldDisplayTimezoneSpinner;
- (void)localeChanged:(id)arg1;
- (void)significantTimeChange:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)newCarrierNotification;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)datePickerChanged:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)makeCurrentTimeSpecifier;
- (id)makeTimePickerSpecifier;
- (void)reloadTimezoneSpinner;
- (void)setAutomaticTimeFooter;
- (id)specifiers;
- (id)init;
- (void)dealloc;
- (void)_setSpecifier:(id)arg1 valueEnabled:(BOOL)arg2;

@end

