//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PSHeaderFooterView.h"

@class UIImageView, UILabel;

@interface DUETLocationIndicatorExplanationView : UIView <PSHeaderFooterView>
{
    UIImageView *_activeIcon;
    UILabel *_activeLabel;
}

- (float)preferredHeightForWidth:(float)arg1 inTableView:(id)arg2;
- (float)preferredHeightForWidth:(float)arg1;
- (void)layoutSubviews;
- (void)layoutForWidth:(float)arg1 inTableView:(id)arg2;
- (void)dealloc;
- (id)initWithSpecifier:(id)arg1;

@end

