//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

#import "RadiosPreferencesDelegate.h"
#import "UIActionSheetDelegate.h"

@class ACAccountStore, EAAccessory, NSArray, NSDictionary, NSObject<OS_dispatch_queue>, NSSet, NSString, PSSpecifier, UIActionSheet, UIViewController<PSController>;

@interface PrefsListController : PSListController <UIActionSheetDelegate, RadiosPreferencesDelegate>
{
    BOOL _didFirstLoad;
    EAAccessory *_speakerAccessory;
    PSSpecifier *_eqSpecifier;
    NSArray *_thirdPartySpecifiers;
    NSDictionary *_movedThirdPartySpecifiers;
    BOOL _victoriaCapable;
    PSSpecifier *_victoriaSpecifier;
    BOOL _notificationState;
    PSSpecifier *_notificationsSpecifier;
    PSSpecifier *_castleSpecifier;
    PSSpecifier *_twitterSpecifier;
    PSSpecifier *_facebookSpecifier;
    PSSpecifier *_flickrSpecifier;
    PSSpecifier *_vimeoSpecifier;
    PSSpecifier *_weiboSpecifier;
    PSSpecifier *_tencentweiboSpecifier;
    PSSpecifier *_messagesSpecifier;
    PSSpecifier *_faceTimeSpecifier;
    PSSpecifier *_gameCenterSpecifier;
    PSSpecifier *_carrierSelectionSpecifier;
    PSSpecifier *_personalHotspotSpecifier;
    BOOL _suppressControllerAnimationForExpiry;
    BOOL _wifiValueIsClean;
    BOOL _bluetoothValueIsClean;
    NSArray *_originalSpecifiers;
    NSSet *_originalDisplayIdentifiers;
    NSObject<OS_dispatch_queue> *_iconCacheQueue;
    NSDictionary *_iconCache;
    UIActionSheet *_airplaneSheet;
    ACAccountStore *_accountStore;
    NSString *_wifiString;
    NSString *_bluetoothString;
}

+ (void)setAirplaneMode:(BOOL)arg1;
+ (BOOL)airplaneMode;
+ (id)radiosPreferences;
@property(copy, nonatomic) NSString *bluetoothString; // @synthesize bluetoothString=_bluetoothString;
@property(copy, nonatomic) NSString *wifiString; // @synthesize wifiString=_wifiString;
- (void)bluetoothPowerChanged:(id)arg1;
- (id)bluetoothValue:(id)arg1;
- (void)bluetoothValueFetch:(id)arg1;
- (void)iMessageSupportMayHaveChanged;
- (void)lazyLoadSpecialBundleForSpecifier:(id)arg1;
- (id)cellularDataStatusForSpecifier:(id)arg1;
- (void)airplaneModeChanged;
- (id)phoneStatusForSpecifier:(id)arg1;
- (id)cellularDisabledStatusForSpecifier:(id)arg1;
- (void)reloadCellularRelatedSpecifiers;
- (id)getAirplaneMode:(id)arg1;
- (void)confirmationSpecifierCancelled:(id)arg1;
- (void)confirmationSpecifierConfirmed:(id)arg1;
- (void)_setAirplaneMode:(BOOL)arg1;
- (void)setAirplaneMode:(id)arg1 specifier:(id)arg2;
- (id)getNotificationsEnabled:(id)arg1;
- (void)_beginObservingAccountStoreDidChangeNotification;
- (id)_accountStore;
- (void)appleAccountsDidChange;
- (void)_setupiCloudSpecifier:(id)arg1;
- (void)setupAppleAccountCategory:(id)arg1;
- (void)MISStateChangedNotification:(id)arg1;
- (void)updatePersonalHotspotWithState:(int)arg1 andReason:(int)arg2;
- (id)getTetheringStatus:(id)arg1;
- (id)wifiNetwork:(id)arg1;
- (void)wifiNetworkFetch:(id)arg1;
- (void)updateWifi;
- (void)willEnterForeground;
- (void)updateShowsCarrierSettingsMenuVisibility;
- (void)setShowsCarrierSettingsMenu:(BOOL)arg1;
- (void)networkChanged;
- (id)currentNetwork:(id)arg1;
- (void)_localeChanged;
- (void)_newCarrierNotification;
- (void)_simStatusChanged:(struct __CFString *)arg1;
@property(readonly, nonatomic) UIViewController<PSController> *categoryController;
- (id)specifierForBundle:(id)arg1;
- (id)specifierForID:(id)arg1;
- (void)loadPPTTestSpecifiers:(int)arg1;
- (void)_loadThirdPartySpecifiers;
- (id)dndGlobalState:(id)arg1;
- (id)specifiers;
- (void)updateWeiboState;
- (void)updateAccountSpecifiers;
- (void)updateRestrictedSettings;
- (void)displayIdentifiersChanged;
- (BOOL)shouldReloadSpecifiersOnResume;
- (void)refresh3rdPartyBundles;
- (void)insertMovedThirdPartySpecifiersAtStartIndex:(unsigned int)arg1 usingInsertBlock:(CDUnknownBlockType)arg2 andExistenceBlock:(CDUnknownBlockType)arg3;
- (id)_specifierDictionaryForDeveloperBundlePath:(id)arg1 identifier:(id)arg2;
- (id)_specifierDictionaryForBundlePath:(id)arg1 identifier:(id)arg2 internalIcon:(BOOL)arg3;
- (BOOL)_showCarrier;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (id)identifierForSelectedIndex;
- (void)selectGeneralCategory;
- (void)suppressControllerAnimationForExpiry;
- (void)checkDeveloperSettingsState;
- (void)dealloc;
- (id)init;
- (void)rerootNavigationController;
- (void)viewWillAppear:(BOOL)arg1;
- (void)reloadSpecifiers;
- (void)clearCache;
- (void)setSpeakerAccessory:(id)arg1 eqAvailable:(BOOL)arg2;

@end

