//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSTableCell.h"

@class UIImageView, UILabel;

@interface PSBadgedTableCell : PSTableCell
{
    UIImageView *_badgeImageView;
    UILabel *_badgeNumberLabel;
    int _badgeInt;
}

+ (id)reuseIdentifierForClassAndType:(int)arg1;
- (void)badgeWithInteger:(int)arg1;
- (void)layoutSubviews;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)resetLocale;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

