//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSEditableTableCell.h"

@interface PSMesaIdentityTableCell : PSEditableTableCell
{
}

- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)textFieldShouldBeginEditing:(id)arg1;
- (BOOL)isEditing;

@end

