//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

#import "UIAlertViewDelegate.h"

@class PSSpecifier, UIAlertView, UISwitch;

@interface RestrictionsController : PSListController <UIAlertViewDelegate>
{
    UIAlertView *_alert;
    UISwitch *_delayedSwitch;
    BOOL _delayedValue;
    PSSpecifier *_findMyFriendsSpecifier;
    PSSpecifier *_iBooksSpecifier;
    PSSpecifier *_iBooksExplicitSpecifier;
    BOOL _isObservingFaceTimeChanges;
}

+ (BOOL)requiresPIN;
- (id)contentRestriction:(id)arg1;
- (BOOL)canBeShownFromSuspendedState;
- (id)countryCodes;
- (id)currentCountryCode;
- (void)setCountryCode:(id)arg1 reload:(BOOL)arg2;
- (id)contentRatingsForMediaType:(id)arg1;
- (id)iBooksExplicitEnabledString:(id)arg1;
- (void)setExplicitEnabled:(id)arg1;
- (id)explicitEnabled;
- (id)explicitEnabledString;
- (id)localizedContentRestrictionStringForRank:(id)arg1 mediaType:(id)arg2;
- (id)currentCountryString:(id)arg1;
- (id)localizedStringForiTunesStorePasswordDefaultTimeout;
- (id)specifiers;
- (void)dealloc;
- (id)init;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)willResignActive;
- (void)willBecomeActive;
- (void)_observeFaceTimeChanges:(BOOL)arg1;
- (void)profileNotification:(id)arg1;
- (void)_handleExternalApplicationChange;
- (void)updateToggleStateAndReload;
- (void)updateToggleState;
- (void)revertRestrictionPrefsIfNeeded;
- (id)capabilityEnabled:(id)arg1;
- (void)setCapabilityEnabled:(id)arg1 specifier:(id)arg2;
- (id)siriContentRestrictionState:(id)arg1;
- (BOOL)siriContentRestrictionsLockedDown;
- (id)webContentRestrictionState:(id)arg1;
- (id)featureValue:(id)arg1;
- (BOOL)featureRestricted:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)setFeatureValue:(id)arg1 specifier:(id)arg2;
- (void)setReversedBoolFeatureValue:(id)arg1 specifier:(id)arg2;
- (id)reversedBoolFeatureValue:(id)arg1;
- (void)_handleFaceTimeConferenceStateChanged;
- (void)_disableFaceTimeRestrictions;
- (void)_disableSpecifier:(id)arg1;
- (BOOL)_isInConference;
- (BOOL)_isiTunesUInstalled;
- (BOOL)_isiBooksInstalled;
- (BOOL)_isFindMyFriendsInstalled;

@end

