//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSDetailController.h"

@interface RingtoneController : PSDetailController
{
}

- (void)applicationWillSuspend;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)willBecomeActive;
- (void)viewDidAppear:(BOOL)arg1;

@end

