//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

#import "UIWebViewDelegate.h"

@class NSString;

@interface SUPrefDetailedReleaseNotes : PSListController <UIWebViewDelegate>
{
    NSString *_releaseNotes;
}

@property(retain, nonatomic) NSString *releaseNotes; // @synthesize releaseNotes=_releaseNotes;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)loadView;
- (id)specifiers;
- (void)dealloc;
- (id)init;

@end

