//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TexttonePane.h"

@interface TonePane : TexttonePane
{
}

+ (id)tonePickerWithFrame:(struct CGRect)arg1;
- (void)setPreferenceSpecifier:(id)arg1;

@end

