/*
* This header is generated by classdump-dyld 0.2
* on Monday, December 30, 2013 at 4:57:31 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /private/var/stash/Applications.BjEYur/MobileSlideShow.app/MobileSlideShow
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PLConfigurableNavigationDisplayOptions <NSObject>
@property (retain) UIView * customTitleView; 
@property (copy) NSString * customTitle; 
@required
-(void)setCustomTitleView:(UIView *)arg1;
-(UIView *)customTitleView;
-(NSString *)customTitle;
-(void)setCustomTitle:(NSString *)arg1;
@end

