/*
* This header is generated by classdump-dyld 0.2
* on Monday, December 30, 2013 at 4:57:31 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /private/var/stash/Applications.BjEYur/MobileSlideShow.app/MobileSlideShow
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PUTabbedLibraryViewController.h>

@class WImportViewController;

@interface TabbedLibraryViewController : PUTabbedLibraryViewController {

	WImportViewController* _importViewController;

}

@property (nonatomic,retain) WImportViewController * importViewController;              //@synthesize importViewController=_importViewController - In the implementation block
-(void)setImportViewController:(id)arg1 ;
-(id)importViewController;
-(void)dealloc;
-(BOOL)shouldShowTabForContentMode:(int)arg1 ;
-(id)newRootViewControllerForContentMode:(int)arg1 ;
@end

