//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSEditingPane.h>

#import "UIKeyInput.h"

@class UIKeyboard, UITransitionView, UIView<PINEntryView>;

@interface DevicePINPane : PSEditingPane <UIKeyInput>
{
    UITransitionView *_transitionView;
    BOOL _transitioning;
    UIView<PINEntryView> *_pinView;
    struct CGRect _pinViewFrame;
    UIKeyboard *_keypad;
    struct CGRect _keypadFrame;
    BOOL _keypadActive;
    int _autocapitalizationType;
    int _autocorrectionType;
    int _keyboardType;
    int _keyboardAppearance;
    BOOL _playSound;
    BOOL _isBlocked;
    BOOL _simplePIN;
}

- (void)activateKeypadView;
- (void)_setKeypadState:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_setPlaysKeyboardClicks:(BOOL)arg1;
- (void)pinView:(id)arg1 pinEntered:(id)arg2;
- (void)adjustButtonsNow;
- (void)setSimplePIN:(BOOL)arg1 requiresKeyboard:(BOOL)arg2;
- (void)slideToNewPasscodeField:(BOOL)arg1 withKeyboard:(BOOL)arg2;
- (void)okButtonPressed;
- (BOOL)simplePIN;
- (void)setPINPolicyString:(id)arg1 visible:(BOOL)arg2;
- (void)hideError;
- (void)hideFailedAttempts;
- (void)showError:(id)arg1 error:(id)arg2 isBlocked:(BOOL)arg3 animate:(BOOL)arg4;
- (void)showFailedAttempts:(int)arg1;
- (void)dismissKeypad;
- (void)deactivateKeypadView;
- (id)specifierLabel;
- (BOOL)requiresKeyboard;
@property(nonatomic) int keyboardAppearance; // @synthesize keyboardAppearance=_keyboardAppearance;
@property(nonatomic) int keyboardType; // @synthesize keyboardType=_keyboardType;
@property(nonatomic) int autocorrectionType; // @synthesize autocorrectionType=_autocorrectionType;
@property(nonatomic) int autocapitalizationType; // @synthesize autocapitalizationType=_autocapitalizationType;
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
- (void)deleteBackward;
- (void)insertText:(id)arg1;
- (BOOL)hasText;
- (void)transitionViewDidComplete:(id)arg1;
- (void)setText:(id)arg1;
- (id)text;
- (BOOL)canBecomeFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (void)setTitle:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)clearPassword;
- (id)password;

// Remaining properties
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(nonatomic) int returnKeyType;
@property(nonatomic) int spellCheckingType;

@end

