//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSKeychainSyncViewController.h>

#import "KeychainSyncPhoneSettingsFragmentDelegate.h"
#import "KeychainSyncViewController.h"
#import "UIAlertViewDelegate.h"

@class KeychainSyncPhoneSettingsFragment, UIAlertView;

@interface KeychainSyncPhoneNumberController : PSKeychainSyncViewController <KeychainSyncPhoneSettingsFragmentDelegate, UIAlertViewDelegate, KeychainSyncViewController>
{
    KeychainSyncPhoneSettingsFragment *_phoneSettingsFragment;
    UIAlertView *_invalidPhoneNumberAlert;
}

- (void)controllerDone;
- (void)nextPressed;
- (void)reloadSpecifiers;
- (id)specifiers;
- (void)phoneSettingsFragment:(id)arg1 didChangePhoneNumber:(id)arg2 countryInfo:(id)arg3;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)loadView;
- (void)viewWillAppear:(BOOL)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)dealloc;

// Remaining properties
@property(nonatomic) id <KeychainSyncViewControllerDelegate> delegate;

@end

