//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/KeychainSyncTextEntryController.h>

#import "UIAlertViewDelegate.h"

@class NSString, UIAlertView, UIButton;

@interface KeychainSyncSecurityCodeController : KeychainSyncTextEntryController <UIAlertViewDelegate>
{
    NSString *_generatedCode;
    BOOL _passcodeMismatch;
    UIButton *_footerButton;
    UIAlertView *_forgotSecurityCodeAlert;
    BOOL _forgotCodeAlertHasApproveButton;
    UIAlertView *_resetKeychainAlert;
    UIAlertView *_weakSecurityCodeAlert;
    BOOL _showsAdvancedSettings;
    int _mode;
    int _securityCodeType;
    NSString *_firstPasscodeEntry;
}

- (void)keyboardWillShow:(id)arg1;
@property(nonatomic) BOOL showsAdvancedSettings; // @synthesize showsAdvancedSettings=_showsAdvancedSettings;
- (void)didFinishEnteringText:(id)arg1;
- (void)textEntryViewDidChange:(id)arg1;
- (void)animatePasscodeFieldLeft:(BOOL)arg1;
- (void)updateNextButton;
- (void)forgotSecurityCode;
- (void)generateRandomCode;
- (void)showAdvancedOptions;
- (id)textEntryCell;
- (Class)textEntryCellClass;
@property(retain, nonatomic) NSString *firstPasscodeEntry; // @synthesize firstPasscodeEntry=_firstPasscodeEntry;
@property(nonatomic) int securityCodeType; // @synthesize securityCodeType=_securityCodeType;
- (id)specifiers;
- (id)placeholderText;
@property(nonatomic) int mode; // @synthesize mode=_mode;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (id)init;
- (void)dealloc;

@end

