//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSTableCell.h>

#import "PSPasscodeFieldDelegate.h"
#import "UIKeyInput.h"

@class PSPasscodeField;

@interface PasscodeFieldCell : PSTableCell <UIKeyInput, PSPasscodeFieldDelegate>
{
    PSPasscodeField *_passcodeField;
    id <KeychainSyncPasscodeFieldDelegate> _delegate;
}

- (id)passcodeText;
- (void)setPasscodeText:(id)arg1;
- (void)_setSecureTextEntry:(BOOL)arg1;
- (void)passcodeField:(id)arg1 enteredPasscode:(id)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
@property(nonatomic) int keyboardType;
- (void)deleteBackward;
- (void)insertText:(id)arg1;
- (BOOL)hasText;
@property(nonatomic) id <KeychainSyncPasscodeFieldDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)dealloc;

// Remaining properties
@property(nonatomic) int autocapitalizationType;
@property(nonatomic) int autocorrectionType;
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(nonatomic) int keyboardAppearance;
@property(nonatomic) int returnKeyType;
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(nonatomic) int spellCheckingType;

@end

