//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSListController.h>

@class PSSpecifier, PrefsUILinkLabel;

@interface ProblemReportingController : PSListController
{
    PrefsUILinkLabel *_aboutDiagnosticsLinkLabel;
    PSSpecifier *_diagnosticDataGroupSpecifier;
}

+ (BOOL)isProblemReportingEnabled;
- (void)setProblemReportingEnabled:(BOOL)arg1;
- (BOOL)shouldEnableProblemReportingForCheckedSpecifier;
- (void)diagnosticsDonePressed:(id)arg1;
- (void)showAboutDiagnosticsSheet:(id)arg1;
- (Class)tableViewClass;
- (id)specifiers;
- (void)viewDidLoad;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)dealloc;

@end

