//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSTableCell.h>

#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class PSListController, UIColor;

@interface PSEditableTableCell : PSTableCell <UITextViewDelegate, UITextFieldDelegate>
{
    UIColor *_textColor;
    id _delegate;
    BOOL _forceFirstResponder;
    BOOL _delaySpecifierRelease;
    SEL _targetSetter;
    id _realTarget;
    BOOL _valueChanged;
    BOOL _returnKeyTapped;
    PSListController *_controllerDelegate;
}

+ (int)cellStyle;
@property(nonatomic) PSListController *controllerDelegate; // @synthesize controllerDelegate=_controllerDelegate;
@property(readonly, nonatomic) BOOL returnKeyTapped; // @synthesize returnKeyTapped=_returnKeyTapped;
- (BOOL)_cellIsEditing;
- (void)endEditingAndSave;
- (void)_saveForExit;
- (void)_setValueChanged;
- (BOOL)isTextFieldEditing;
- (void)controlChanged:(id)arg1;
- (void)setValueChangedTarget:(id)arg1 action:(SEL)arg2 specifier:(id)arg3;
- (void)cellRemovedFromView;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (BOOL)canReload;
- (void)setPlaceholderText:(id)arg1;
- (void)setCellEnabled:(BOOL)arg1;
- (id)textField;
- (BOOL)canResignFirstResponder;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)textFieldShouldClear:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)prepareForReuse;
- (BOOL)isEditing;
- (BOOL)isFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (id)value;
- (void)setValue:(id)arg1;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (void)setTitle:(id)arg1;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end

