//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSListItemsController.h>

@class NSMutableDictionary;

@interface PSInternationalLanguageController : PSListItemsController
{
    NSMutableDictionary *_cellCache;
}

- (void)generateLanguageCellCache;
@property(retain, nonatomic) NSMutableDictionary *cellCache; // @synthesize cellCache=_cellCache;
- (void)updateNavigationItem;
- (void)doneButtonTapped;
- (void)_removeBlackFrame;
- (void)cancelButtonTapped;
- (id)specifiers;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)init;
- (void)dealloc;

@end

