//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Preferences/PSListController.h>

@class PSSpecifier;

@interface PSLocaleController : PSListController
{
    PSSpecifier *_checkedSpecifier;
    BOOL _firstAppearance;
}

- (void)localeChangedAction;
- (id)locale:(id)arg1;
- (void)subcategorySelected:(id)arg1 specifier:(id)arg2;
- (void)addLanguage:(id)arg1 toSupportedLanguages:(id)arg2;
- (void)updateChecked:(id)arg1;
- (void)setLocale:(id)arg1 specifier:(id)arg2;
- (id)specifiers;
- (void)viewWillAppear:(BOOL)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)init;
- (void)dealloc;

@end

