/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "SBIconViewDelegate.h"
#import "SBIconViewMapDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary, SBStopScrollingGestureRecognizer, UIScrollView, UIView;

@interface SBAppSliderIconController : UIViewController <UIScrollViewDelegate, SBIconViewMapDelegate, SBIconViewDelegate>
{
    NSMutableArray *_appList;
    NSMutableDictionary *_iconViews;
    NSMutableArray *_iconViewCenters;
    UIScrollView *_scrollView;
    UIView *_iconContainer;
    CGFloat _distanceBetweenCenters;
    CGFloat _nominalDistanceBetweenCenters3;
    CGFloat _nominalDistanceBetweenCenters5;
    NSUInteger _iconTransitionIndex;
    BOOL _dragMaster;
    BOOL _preventScroll;
    SBStopScrollingGestureRecognizer *_stopScrollingGesture;
    int _layoutOrientation;
    int _simplicityOptions;
    CGRect _iconViewDefaultFrame;
    id <SBAppSliderIconControllerDelegate> _delegate;
    NSArray *_displayIdentifiers;
}

+ (CGFloat)nominalDistanceBetween5IconCentersForSize:(CGSize)arg1;
+ (CGFloat)nominalDistanceBetween3IconCentersForSize:(CGSize)arg1;
@property(copy, nonatomic) NSArray *displayIdentifiers; // @synthesize displayIdentifiers=_displayIdentifiers;
@property(nonatomic) NSUInteger iconTransitionIndex; // @synthesize iconTransitionIndex=_iconTransitionIndex;
@property(nonatomic) id <SBAppSliderIconControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_iconsReloaded;
- (CGFloat)iconLabelWidth;
- (void)iconTouchBegan:(id)arg1;
- (void)iconHandleLongPress:(id)arg1;
- (BOOL)iconShouldAllowTap:(id)arg1;
- (void)iconTapped:(id)arg1;
- (Class)viewMap:(id)arg1 iconViewClassForIcon:(id)arg2;
- (int)viewMap:(id)arg1 locationForIcon:(id)arg2;
- (NSUInteger)viewMap:(id)arg1 maxRecycledIconViewsOfClass:(Class)arg2;
- (int)_windowInterfaceOrientation;
- (NSUInteger)_centeredIndex;
- (void)_handleStopScrollingGesture:(id)arg1;
- (CGFloat)_recalculateLayout:(BOOL)arg1;
- (CGFloat)_calculateDistanceBetweenCentersBasedOnCurrentContentOffset;
- (CGFloat)_calculateDistanceBetweenCentersBasedOnCenteredIndex:(NSUInteger)arg1;
- (void)_layoutForDistance:(CGFloat)arg1;
- (void)_updateVisibleIconViewsWithPadding:(BOOL)arg1;
- (CGPoint)_adjustedCenter:(CGPoint)arg1 forIconView:(id)arg2;
- (BOOL)_isIndexVisible:(NSUInteger)arg1 withPadding:(BOOL)arg2;
- (CGPoint)_centerOfIndex:(NSUInteger)arg1 forDistance:(CGFloat)arg2 inOrientation:(int)arg3;
- (CGFloat)_distanceBetweenCenters;
- (void)reloadInOrientation:(int)arg1;
- (void)_cleanupAllIcons;
- (void)_cleanupIcon:(id)arg1;
- (CGFloat)_halfWidth;
- (void)_recalculateBaseIconSpacingValues;
- (NSUInteger)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (void)removeIndex:(NSUInteger)arg1 duration:(double)arg2;
- (void)cancelScrolling;
- (void)switcherWasDismissed:(BOOL)arg1;
- (void)loadView;
- (BOOL)isScrolling;
- (void)setNormalizedOffset:(CGFloat)arg1;
- (void)setOffsetToIndex:(NSUInteger)arg1 animated:(BOOL)arg2;
- (CGFloat)_maxXOffsetForDistance:(CGFloat)arg1;
- (id)_iconViewForIndex:(NSUInteger)arg1;
- (CGRect)_iconFaultRectForIndex:(NSUInteger)arg1;
- (void)dealloc;
- (id)init;

@end

