/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@class NSString, SBApplication;

@interface SBApplicationIcon : SBLeafIcon
{
    NSString *_displayIdentifier;
}

- (NSString *)applicationBundleID;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (void)setBadge:(id)arg1;
- (id)automationID;
- (id)tags;
- (id)getUnmaskedIconImage:(NSInteger)imgType;
- (id)generateIconImage:(NSInteger)imgType;
- (BOOL)canGenerateImageInBackgroundForFormat:(NSInteger)arg1;
- (void)generateIconImageInBackground:(id)arg1;
- (id)blockForGeneratingIconImageInBackgroundWithFormat:(SEL)arg1;
- (id)_blockForGeneratingIconImageInBackgroundWithFormat:(SEL)arg1 complete:(NSInteger)arg2;
- (id)__loadIconImageForDataSource:(id)arg1 format:(NSInteger)arg2;
- (id)application;
- (void)dealloc;
- (id)copyWithZone:(NSZone)arg1;
- (id)initWithApplication:(SBApplication *)app;

@end

