/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol SBAppSliderIconControllerDelegate <NSObject>
- (void)sliderIconScrollerDidEndScrolling:(id)arg1;
- (unsigned int)sliderIconScroller:(id)arg1 settledIndexForNormalizedOffset:(inout CGFloat *)arg2 andXVelocity:(CGFloat)arg3;
- (void)sliderIconScrollerBeganPanning:(id)arg1;
- (void)sliderIconScroller:(id)arg1 activate:(id)arg2;
- (void)sliderIconScroller:(id)arg1 contentOffsetChanged:(CGFloat)arg2;
@end

