/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>
#import "SBResponderTouchDelegate-Protocol.h"
#import "_SBFVibrantView-Protocol.h"

@class SBLegibilityView, _SBFVibrantSettings;

@interface SBCameraGrabberView : UIView <_SBFVibrantView>
{
    struct UIEdgeInsets _hitTestEdgeInsets;
    UIView *_colorCompositingView;
    UIView *_darkTintView;
    UIView *_lightTintView;
    UIView *_backgroundView;
    SBLegibilityView *_legibilityView;
    _SBFVibrantSettings *_vibrantSettings;
    id <SBResponderTouchDelegate> _delegate;
}

@property(nonatomic, assign) id <SBResponderTouchDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) _SBFVibrantSettings *vibrantSettings; // @synthesize vibrantSettings=_vibrantSettings;

- (void)updateForChangedSettings:(id)arg1;
- (void)setStrength:(float)strength;
- (id)_lazyLegibilityView;
- (void)setBackgroundView:(id)view;
- (CGSize)sizeThatFits:(CGSize)size;
- (id)_cameraGrabberImage;

@end

