/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@interface SBCalendarApplicationIcon : SBApplicationIcon
{
}

+ (id)countriesRequiringBlackDayOfWeek;
- (void)_drawIconIntoCurrentContextWithImageSize:(CGSize)size iconBase:(id)base;
- (id)numberFont;
- (id)colorForDayOfWeek;
- (BOOL)isBlackDayOfWeekRequiredForLocale:(id)arg1;
- (BOOL)canGenerateImageInBackgroundForFormat:(NSInteger)arg1;
- (id)getUnmaskedIconImage:(NSInteger)arg1;
- (id)generateIconImage:(NSInteger)arg1;
- (void)localeChanged;
- (void)dealloc;
- (id)initWithApplication:(id)arg1;

@end

