/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIcon.h"
#import "SBRootIconListView.h"
#import "CDStructures.h"

@class SBIconListModel;
@interface SBDockIconListView : SBRootIconListView
+ (NSUInteger)iconRowsForInterfaceOrientation:(UIInterfaceOrientation)orientation;
+ (NSUInteger)iconColumnsForInterfaceOrientation:(UIInterfaceOrientation)orientation;
+ (CGPoint)defaultHeight;

- (NSUInteger)columnAtPoint:(CGPoint)point;
- (CGPoint)originForIconAtCoordinate:(SBIconCoordinate)coordinate;
- (CGPoint)_additionalSideInsetToCenterIcons;
- (NSUInteger)rowAtPoint:(CGPoint)point;
- (SBIcon *)iconAtPoint:(CGPoint)point index:(NSUInteger *)index proposedOrder:(NSInteger *)order grabbedIcon:(id)icon;
- (CGPoint)sideIconInset;
- (CGPoint)topIconInset;
- (NSUInteger)iconsInRowForSpacingCalculation;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (SBIconLocation)iconLocation;
- (instancetype)initWithModel:(SBIconListModel *)model orientation:(UIInterfaceOrientation)ori viewMap:(id)viewMap;

@end

