/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBGestureRecognizer.h"

@interface SBFluidSlideGestureRecognizer : SBGestureRecognizer
{
    int m_degreeOfFreedom;
    unsigned int m_minTouches;
    BOOL m_blocksIconController;
    CGFloat _animationDistance;
    CGFloat _commitDistance;
    CGFloat _accelerationThreshold;
    CGFloat _accelerationPower;
    int _requiredDirectionality;
    CGFloat _defaultHandSize;
    CGFloat _handSizeCompensationPower;
    CGFloat _incrementalMotion;
    CGFloat _smoothedIncrementalMotion;
    CGFloat _cumulativeMotion;
    CGFloat _cumulativeMotionEnvelope;
    CGFloat _cumulativeMotionSkipped;
    BOOL _hasSignificantMotion;
    struct CGPoint _movementVelocityInPointsPerSecond;
    struct CGPoint _centroidPoint;
    double _recognitionStartTimestamp;
}

@property(readonly, nonatomic) struct CGPoint centroidPoint; // @synthesize centroidPoint=_centroidPoint;
@property(readonly, nonatomic) struct CGPoint movementVelocityInPointsPerSecond; // @synthesize movementVelocityInPointsPerSecond=_movementVelocityInPointsPerSecond;
@property(nonatomic) int requiredDirectionality; // @synthesize requiredDirectionality=_requiredDirectionality;
@property(nonatomic) CGFloat accelerationPower; // @synthesize accelerationPower=_accelerationPower;
@property(nonatomic) CGFloat accelerationThreshold; // @synthesize accelerationThreshold=_accelerationThreshold;
@property(nonatomic) CGFloat animationDistance; // @synthesize animationDistance=_animationDistance;
@property(nonatomic) unsigned int minTouches; // @synthesize minTouches=m_minTouches;
@property(readonly, nonatomic) int degreeOfFreedom; // @synthesize degreeOfFreedom=m_degreeOfFreedom;
- (void)touchesCancelled:(struct __SBGestureContext *)arg1;
- (void)touchesEnded:(struct __SBGestureContext *)arg1;
- (void)touchesMoved:(struct __SBGestureContext *)arg1;
- (void)touchesBegan:(struct __SBGestureContext *)arg1;
- (void)updateActiveTouches:(struct __SBGestureContext *)arg1;
- (void)updateForEndedOrCancelledTouches:(struct __SBGestureContext *)arg1;
- (void)updateForBeganOrMovedTouches:(struct __SBGestureContext *)arg1;
- (void)setState:(int)arg1;
- (int)completionTypeProjectingMomentumForInterval:(double)arg1;
- (CGFloat)projectMotionForInterval:(double)arg1;
- (void)computeCentroidPoint:(struct __SBGestureContext *)arg1;
- (void)computeHasSignificantMotionIfNeeded:(struct __SBGestureContext *)arg1;
- (CGFloat)computeIncrementalGestureMotion:(struct __SBGestureContext *)arg1;
- (void)computeGestureMotion:(struct __SBGestureContext *)arg1;
- (CGFloat)computeHandSizeCompensationGain:(CGFloat)arg1;
- (CGFloat)computeNonlinearSpeedGain:(CGFloat)arg1;
- (void)skipCumulativeMotion;
- (void)reset;
- (double)activeTouchTimestamp;
@property(readonly, nonatomic) double activeRecognitionDuration;
@property(readonly, nonatomic) CGFloat incrementalMotion;
@property(readonly, nonatomic) CGFloat cumulativeMotion;
@property(readonly, nonatomic) CGFloat cumulativePercentage;
@property(readonly, nonatomic) CGFloat skippedCumulativePercentage;
- (id)init;

@end

