/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBFolderView.h"
#import <UIKit/UIKit.h>
#import "_UISettingsKeyObserver-Protocol.h"

@class SBFolderBackgroundView, SBFolderSettings, UILongPressGestureRecognizer, UIPinchGestureRecognizer, UITapGestureRecognizer, UIView;

@interface SBFloatyFolderView : SBFolderView <UIGestureRecognizerDelegate, _UISettingsKeyObserver>
{
    UIView *_scrollClipView;
    SBFolderBackgroundView *_backgroundView;
    UITapGestureRecognizer *_tapGesture;
    UIPinchGestureRecognizer *_pinchGesture;
    UILongPressGestureRecognizer *_longPressGesture;
    SBFolderSettings *_folderSettings;
}

- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)_tapToCloseGestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_handleLongPressGesture:(id)arg1;
- (void)_handlePinchGesture:(id)arg1;
- (void)_handleOutsideTap:(id)arg1;
- (void)_configureGestures;
- (void)fadeContentForMinificationFraction:(CGFloat)arg1;
- (void)fadeContentForMagnificationFraction:(CGFloat)arg1;
- (void)didAnimate;
- (void)willAnimate;
- (CGFloat)_titleFontSize;
- (BOOL)_showsTitle;
- (BOOL)locationCountsAsInsideFolder:(CGPoint)arg1;
- (CGRect)_frameForScalingView;
- (void)_layoutSubviews;
- (CGPoint)visibleFolderRelativeImageCenterForIcon:(id)arg1;
- (void)setBackgroundAlpha:(CGFloat)arg1;

- (instancetype)initWithFolder:(SBFolder *)folder orientation:(UIInterfaceOrientation)orientation;

@end

