/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "SBWallpaperObserver-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class SBFolderSettings, SBWallpaperEffectView, UIImageView;

@interface SBFolderBackgroundView : UIView <_UISettingsKeyObserver, SBWallpaperObserver>
{
    SBWallpaperEffectView *_backdropView;
    UIImageView *_backgroundImageView;
    SBFolderSettings *_folderSettings;
}

+ (CGFloat)cornerRadiusToInsetContent;
+ (CGSize)folderBackgroundSize;

- (void)wallpaperDidChangeForVariant:(NSInteger)arg1;
- (void)settings:(id)settings changedValueForKey:(id)key;
- (void)_configureBackground;
- (void)adjustCornerRadiusForMagnificationFraction:(CGFloat)arg1;
- (void)didAnimate;
- (void)willAnimate;

@end

