/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconListView.h"

@interface SBFolderIconListView : SBIconListView
{
}

/*
Only overrides methods in SBIconListView to adjust positioning/ayout.
+ (NSUInteger)maxVisibleIconRowsInterfaceOrientation:(UIInterfaceOrientation)orientation;
+ (NSUInteger)iconColumnsForInterfaceOrientation:(UIInterfaceOrientation)orientation;
- (NSInteger)iconLocation;
- (CGFloat)sideIconInset;
- (CGFloat)bottomIconInset;
- (CGFloat)topIconInset;
*/
@end

