/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBHarmonicOscillator : NSObject
{
    CGFloat A;
    CGFloat Z;
    CGFloat k;
    CGFloat dk;
    CGFloat mink;
    CGFloat m;
    CGFloat dm;
    CGFloat minm;
    CGFloat psi_n;
    CGFloat psi_d;
    CGFloat zeta;
}

@property(nonatomic) CGFloat minimumMass; // @synthesize minimumMass=minm;
@property(nonatomic) CGFloat massDecay; // @synthesize massDecay=dm;
@property(nonatomic) CGFloat mass; // @synthesize mass=m;
@property(nonatomic) CGFloat minimumSpringStrength; // @synthesize minimumSpringStrength=mink;
@property(nonatomic) CGFloat springDecay; // @synthesize springDecay=dk;
@property(nonatomic) CGFloat springStrength; // @synthesize springStrength=k;
@property(nonatomic) CGFloat endingAmplitude; // @synthesize endingAmplitude=Z;
@property(nonatomic) CGFloat startingAmplitude; // @synthesize startingAmplitude=A;
- (CGFloat)amplitudeForElapsedTime:(double)arg1;
- (void)updateParameters;
- (void)setSpringConstant:(CGFloat)arg1;
- (id)init;

@end

