/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIKit/UIView.h"

#import "SBIconObserver-Protocol.h"
#import "SBIconProgressViewDelegate-Protocol.h"

@class SBIcon, SBIconProgressView, UIImage, UIImageView;

@interface SBIconImageView : UIView <SBIconObserver, SBIconProgressViewDelegate>
{
    UIImageView *_overlayView;
    SBIconProgressView *_progressView;
    BOOL _isPaused;
    UIImage *_cachedSquareContentsImage;
    BOOL _showsSquareCorners;
    SBIcon *_icon;
    CGFloat _brightness;
    CGFloat _overlayAlpha;
}

+ (id)dequeueRecycledIconImageViewOfClass:(Class)arg1;
+ (void)recycleIconImageView:(id)arg1;
+ (CGFloat)cornerRadius;
@property(nonatomic) BOOL showsSquareCorners; // @synthesize showsSquareCorners=_showsSquareCorners;
@property(nonatomic) CGFloat overlayAlpha; // @synthesize overlayAlpha=_overlayAlpha;
@property(nonatomic) CGFloat brightness; // @synthesize brightness=_brightness;
@property(retain, nonatomic) SBIcon *icon; // @synthesize icon=_icon;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)iconImageDidUpdate:(id)arg1;
- (CGRect)visibleBounds;
- (CGSize)sizeThatFits:(CGSize)arg1;
- (id)squareDarkeningOverlayImage;
- (id)darkeningOverlayImage;
- (id)squareContentsImage;
- (id)contentsImage;
- (void)_clearCachedImages;
- (id)_generateSquareContentsImage;
- (void)_updateProgressMask;
- (void)_updateOverlayImage;
- (id)_currentOverlayImage;
- (void)updateImageAnimated:(BOOL)arg1;
- (id)snapshot;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setPaused:(BOOL)arg1;
- (void)setProgressAlpha:(CGFloat)arg1;
- (void)_clearProgressView;
- (void)progressViewCanBeRemoved:(id)progressView;
- (void)setProgressState:(int)state paused:(BOOL)paused percent:(CGFloat)percent animated:(BOOL)animated;
- (void)_updateOverlayAlpha;
- (void)setIcon:(id)icon animated:(BOOL)animated;
- (void)dealloc;

@end

