/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface SBIconContentView : UIView
{
    UIInterfaceOrientation _orientation;
    NSMutableArray *_folderContentViews;
    CGFloat _searchGestureProgress;
}

@property(nonatomic) UIInterfaceOrientation orientation; // @synthesize orientation=_orientation;

- (void)clearAllFolderContentViews;
- (void)popFolderContentView:(UIView *)view;
- (void)pushFolderContentView:(UIView *)view;
- (void)updateLayoutWithDuration:(NSTimeInterval)duration;
- (instancetype)initWithOrientation:(UIInterfaceOrientation)arg1;

@end

