/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "_SBIconWallpaperColorClient-Protocol.h"
#import "SBIconBlurryBackgroundViewObserver-Protocol.h"

@interface SBIconBlurryBackgroundView : UIView <_SBIconWallpaperColorClient>
{
    struct CGRect _wallpaperRelativeBounds;
    BOOL _isBlurring;
    BOOL _suppressesExternalUpdates;
    id <SBIconBlurryBackgroundViewObserver> _observer;
    id _wantsBlurEvaluator;
    struct CGPoint _wallpaperRelativeCenter;
}

@property(nonatomic, getter=isSuppressingExternalUpdates) BOOL suppressesExternalUpdates; // @synthesize suppressesExternalUpdates=_suppressesExternalUpdates;
@property(copy, nonatomic) id wantsBlurEvaluator; // @synthesize wantsBlurEvaluator=_wantsBlurEvaluator;
@property(readonly, nonatomic) BOOL isBlurring; // @synthesize isBlurring=_isBlurring;
@property(nonatomic) CGPoint wallpaperRelativeCenter; // @synthesize wallpaperRelativeCenter=_wallpaperRelativeCenter;
@property(nonatomic, assign) id<SBIconBlurryBackgroundViewObserver> observer; // @synthesize observer=_observer;
- (BOOL)_shouldAnimatePropertyWithKey:(id)key;
- (void)setBlurring:(BOOL)blurring;
- (void)setWallpaperColor:(CGColorRef)color phase:(CGSize)arg2;
- (BOOL)wantsBlur:(id)arg1;
- (CGRect)wallpaperRelativeBounds;

@end

