/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/_UISettings.h>

@interface SBLegibilitySettings : _UISettings
{
    CGFloat _slideToUnlockDarkShadowStrength;
    CGFloat _slideToUnlockLightShadowStrength;
    CGFloat _cameraGrabberDarkShadowStrength;
    CGFloat _cameraGrabberLightShadowStrength;
    CGFloat _timeDarkShadowStrength;
    CGFloat _timeLightShadowStrength;
    CGFloat _dateDarkShadowStrength;
    CGFloat _dateLightShadowStrength;
    CGFloat _legalDarkShadowStrength;
    CGFloat _legalLightShadowStrength;
    CGFloat _iconLabelDarkShadowStrength;
    CGFloat _iconLabelLightShadowStrength;
    CGFloat _folderTitleDarkShadowStrength;
    CGFloat _folderTitleLightShadowStrength;
    CGFloat _timerTextDarkShadowStrength;
    CGFloat _timerTextLightShadowStrength;
    CGFloat _timerDialDarkShadowStrength;
    CGFloat _timerDialLightShadowStrength;
}

+ (id)settingsControllerModule;
@property CGFloat timerDialLightShadowStrength; // @synthesize timerDialLightShadowStrength=_timerDialLightShadowStrength;
@property CGFloat timerDialDarkShadowStrength; // @synthesize timerDialDarkShadowStrength=_timerDialDarkShadowStrength;
@property CGFloat timerTextLightShadowStrength; // @synthesize timerTextLightShadowStrength=_timerTextLightShadowStrength;
@property CGFloat timerTextDarkShadowStrength; // @synthesize timerTextDarkShadowStrength=_timerTextDarkShadowStrength;
@property CGFloat folderTitleLightShadowStrength; // @synthesize folderTitleLightShadowStrength=_folderTitleLightShadowStrength;
@property CGFloat folderTitleDarkShadowStrength; // @synthesize folderTitleDarkShadowStrength=_folderTitleDarkShadowStrength;
@property CGFloat iconLabelLightShadowStrength; // @synthesize iconLabelLightShadowStrength=_iconLabelLightShadowStrength;
@property CGFloat iconLabelDarkShadowStrength; // @synthesize iconLabelDarkShadowStrength=_iconLabelDarkShadowStrength;
@property CGFloat legalLightShadowStrength; // @synthesize legalLightShadowStrength=_legalLightShadowStrength;
@property CGFloat legalDarkShadowStrength; // @synthesize legalDarkShadowStrength=_legalDarkShadowStrength;
@property CGFloat dateLightShadowStrength; // @synthesize dateLightShadowStrength=_dateLightShadowStrength;
@property CGFloat dateDarkShadowStrength; // @synthesize dateDarkShadowStrength=_dateDarkShadowStrength;
@property CGFloat timeLightShadowStrength; // @synthesize timeLightShadowStrength=_timeLightShadowStrength;
@property CGFloat timeDarkShadowStrength; // @synthesize timeDarkShadowStrength=_timeDarkShadowStrength;
@property CGFloat cameraGrabberLightShadowStrength; // @synthesize cameraGrabberLightShadowStrength=_cameraGrabberLightShadowStrength;
@property CGFloat cameraGrabberDarkShadowStrength; // @synthesize cameraGrabberDarkShadowStrength=_cameraGrabberDarkShadowStrength;
@property CGFloat slideToUnlockLightShadowStrength; // @synthesize slideToUnlockLightShadowStrength=_slideToUnlockLightShadowStrength;
@property CGFloat slideToUnlockDarkShadowStrength; // @synthesize slideToUnlockDarkShadowStrength=_slideToUnlockDarkShadowStrength;
- (CGFloat)timerDialStrengthForStyle:(NSInteger)arg1;
- (CGFloat)timerTextStrengthForStyle:(NSInteger)arg1;
- (CGFloat)folderTitleStrengthForStyle:(NSInteger)arg1;
- (CGFloat)iconLabelStrengthForStyle:(NSInteger)arg1;
- (CGFloat)legalStrengthForStyle:(NSInteger)arg1;
- (CGFloat)dateStrengthForStyle:(NSInteger)arg1;
- (CGFloat)timeStrengthForStyle:(NSInteger)arg1;
- (CGFloat)cameraGrabberStrengthForStyle:(NSInteger)arg1;
- (CGFloat)slideToUnlockStrengthForStyle:(NSInteger)arg1;
- (void)setDefaultValues;

@end

