/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIcon.h"
#import "SBLeafIconDataSource-Protocol.h"
#import <Foundation/Foundation.h>

@interface SBLeafIcon : SBIcon <NSCopying>
{
    NSString *_leafIdentifier;
    NSString *_applicationBundleID;
    NSMutableSet *_dataSources;
    id<SBLeafIconDataSource> _activeDataSource;
    id<SBLeafIconDataSource> _dataSourceAtUninstallation;
}

- (id)nodeIdentifier;
- (void)launchFromLocation:(SBIconLocation)loc;
- (BOOL)launchEnabled;
- (void)completeUninstall;
- (void)setUninstalled;
- (BOOL)allowsUninstall;
- (BOOL)isRecentlyUpdated;
- (NSInteger)accessoryTypeForLocation:(SBIconLocation)loc;
- (id)accessoryTextForLocation:(SBIconLocation)loc;
- (id)badgeNumberOrString;
- (BOOL)progressIsPaused;
- (CGFloat)progressPercent;
- (NSInteger)progressState;
- (BOOL)iconAppearsInNewsstand;
- (BOOL)canEllipsizeLabel;
- (id)displayName;
- (id)getGenericIconImage:(NSInteger)imgType;
- (id)generateIconImage:(NSInteger)imgType;
- (void)_noteDataSourceDidInvalidateNotification:(NSNotification *)notif;
- (void)_noteActiveDataSourceDidGenerateImageNotification:(NSNotification *)notif;
- (void)_noteActiveDataSourceDidChangeNotification:(NSNotification *)notif;
- (void)_noteActiveDataSourceDidGenerateIconFormat:(NSInteger)format;
- (void)_noteActiveDataSourceDidChangeAndReloadIcon:(BOOL)reload;
- (id<SBLeafIconDataSource>)activeDataSource;
- (void)removeIconDataSourcesOfClass:(Class)cls;
- (void)removeIconDataSource:(id<SBLeafIconDataSource>)dataSource;
- (void)addIconDataSource:(id<SBLeafIconDataSource>)dataSource;
- (void)_updateActiveDataSource;
- (BOOL)matchesRepresentation:(id)repr;
- (id)representation;
- (NSString *)applicationBundleID;
- (NSString *)leafIdentifier;
- (instancetype)initWithLeafIdentifier:(NSString *)ident applicationBundleID:(NSString *)bundleIdent;
@end

