/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class UIColor, _UIBackdropViewSettings;

@interface SBLockOverlayStyleProperties : NSObject
{
    UIColor *_primaryColor;
    UIColor *_secondaryColor;
    UIColor *_tintColor;
    CGFloat _tintAlpha;
    CGFloat _blurRadius;
    unsigned int _style;
    int _quality;
    _UIBackdropViewSettings *_settings;
}

@property(readonly, nonatomic) CGFloat blurRadius; // @synthesize blurRadius=_blurRadius;
@property(readonly, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(readonly, nonatomic) CGFloat tintAlpha; // @synthesize tintAlpha=_tintAlpha;
@property(readonly, nonatomic) int graphicsQuality; // @synthesize graphicsQuality=_quality;
@property(readonly, nonatomic) unsigned int style; // @synthesize style=_style;
- (id)_stringForStyle;
- (id)_stringForQuality;
- (id)_settingsForStyle;
- (void)_configure;
- (id)description;
- (void)dealloc;
- (id)initWithStyle:(unsigned int)arg1 quality:(int)arg2;

@end

