/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBNotificationsSectionInfo.h"

@interface SBNotificationsMissedModeSectionInfo : SBNotificationsSectionInfo
{
}

- (CGFloat)heightForReusableViewInTableView:(id)arg1;
- (Class)reusableViewClass;
- (int)sectionCategory;
- (id)identifier;

@end

