/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconZoomAnimator.h"
#import "CDStructures.h"
#import "SBScaleZoomSettings.h"

@class SBIcon, SBIconView, SBScaleZoomSettings, UIView;

@interface SBScaleIconZoomAnimator : SBIconZoomAnimator
{
    UIEdgeInsets _iconScootch;
    CGFloat _dockStretch;
    SBIconCoordinate _dockListCenterCoordinate;
    SBIconCoordinate _mainListCenterCoordinate;
    CGFloat _naturalVisualAltitude;
    UIView *_scalingView;
    SBIcon *_targetIcon;
    CGFloat _zoomScale;
}

@property(readonly, nonatomic) CGFloat zoomScale; // @synthesize zoomScale=_zoomScale;
@property(readonly, nonatomic) SBIcon *targetIcon; // @synthesize targetIcon=_targetIcon;
- (void)_calculateIconScootch;
- (CGPoint)_scootchForIcon:(id)arg1 inDock:(BOOL)arg2;
- (void)_applyOuterFadeFraction:(CGFloat)arg1;
- (void)_applyZoomFraction:(CGFloat)arg1;
- (CGFloat)_zoomedVisualAltitude;
- (CGPoint)_zoomedIconCenter;
- (CGRect)_zoomedFrame;
- (void)_animateToFraction:(CGFloat)fraction afterDelay:(NSTimeInterval)delay withSharedCompletion:(id)arg3;
- (NSUInteger)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(CGFloat)arg1;
- (void)_prepareAnimation;
@property(readonly, nonatomic) SBIconView *targetIconView;
- (void)dealloc;
- (id)initWithFolderController:(SBFolderController *)folderController targetIcon:(id)arg2;

// Remaining properties
@property(retain, nonatomic) SBScaleZoomSettings *settings; // 7.0.x+
@property(retain, nonatomic) SBScaleZoomSettings *zoomSettings; // 7.0

@end

