/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class SBFLockScreenDateView, SBFadeAnimationSettings, SBLockScreenView, UIView, UIWindow;

@interface SBScreenFadeAnimationController : NSObject
{
    UIWindow *_fadeWindow;
    UIView *_overlayView;
    SBFLockScreenDateView *_dateView;
    CGFloat _originalDateLeftEdge;
    CGFloat _originalDateBottomEdge;
    CGFloat _finalTimeAlpha;
    CGFloat _finalDateAlpha;
    CGFloat _finalStatusBarAlpha;
    SBLockScreenView *_lockScreenView;
    BOOL _preparingToAnimateFadeIn;
    BOOL _animatingForFadeIn;
    BOOL _animatingForFadeOut;
    int _animationToken;
    id _fadeInCompletionBlock;
    id _fadeOutCompletionBlock;
    BOOL _animatingDateTime;
    BOOL _animatingWallpaper;
    BOOL _animatingOverlay;
    BOOL _animatingContent;
    SBFadeAnimationSettings *_settings;
}

+ (id)sharedInstance;
- (void)setLegibilitySettings:(id)arg1;
- (void)setTextColor:(id)arg1;
- (void)hideDate;
- (void)setDateViewAlpha:(CGFloat)arg1;
- (void)_runCompletionHandlerForFadeIn:(BOOL)arg1;
- (void)_handleAnimationCompletionIfNecessaryForFadeIn:(BOOL)arg1;
- (void)fadeOutWithCompletion:(id)arg1;
- (void)_startFadeAnimationsForFadeIn:(BOOL)arg1;
- (void)_cleanupAnimationWhenInterruptingFadeIn:(BOOL)arg1;
- (void)_assistantVisibilityChanged;
- (void)_mediaControlsDidShow;
- (void)_blankScreenStateChanged;
- (void)_startFadeInIfNecessary;
- (void)prepareToFadeInWithTimeAlpha:(CGFloat)arg1 dateAlpha:(CGFloat)arg2 statusBarAlpha:(CGFloat)arg3 lockScreenView:(id)arg4 existingDateView:(id)arg5 completion:(id)arg6;
- (void)_setRelevantLockScreenViewsHidden:(BOOL)arg1;
- (void)_adjustViewsForCurrentOrientation;
- (void)updateDateFrameHorizontalOffset:(CGFloat)arg1 verticalOffset:(CGFloat)arg2;
- (BOOL)isFadeOutAnimationInProgress;
- (BOOL)isFadeInAnimationInProgress;
- (void)_createFadeWindowForFadeIn:(BOOL)arg1;
- (double)fadeOutAnimationDuration;
- (double)fadeInAnimationDuration;
- (void)dealloc;
- (id)init;

@end

