/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class SBApplication, SBStretchTransformer;

@interface SBSwitchAppGestureView : UIView
{
    int m_orientation;
    SBApplication *m_startingApp;
    SBApplication *m_endingApp;
    SBApplication *m_leftwardApp;
    SBApplication *m_rightwardApp;
    int m_startingViewOrientation;
    int m_leftwardViewOrientation;
    int m_rightwardViewOrientation;
    UIView *m_startingView;
    UIView *m_leftwardView;
    UIView *m_rightwardView;
    CGFloat m_pageWidth;
    CGFloat m_percentage;
    CGFloat m_contentOffset;
    SBStretchTransformer *m_stretchTransformer;
    BOOL m_finishingPaging;
    BOOL m_underflowing;
    BOOL m_overflowing;
    id m_completion;
}

@property(copy, nonatomic) id completion; // @synthesize completion=m_completion;
@property(nonatomic) BOOL overflowing; // @synthesize overflowing=m_overflowing;
@property(nonatomic) BOOL underflowing; // @synthesize underflowing=m_underflowing;
@property(retain, nonatomic) SBStretchTransformer *stretchTransformer; // @synthesize stretchTransformer=m_stretchTransformer;
@property(nonatomic) CGFloat contentOffset; // @synthesize contentOffset=m_contentOffset;
@property(nonatomic) CGFloat percentage; // @synthesize percentage=m_percentage;
@property(nonatomic) CGFloat pageWidth; // @synthesize pageWidth=m_pageWidth;
@property(nonatomic) int rightwardViewOrientation; // @synthesize rightwardViewOrientation=m_rightwardViewOrientation;
@property(nonatomic) int leftwardViewOrientation; // @synthesize leftwardViewOrientation=m_leftwardViewOrientation;
@property(nonatomic) int startingViewOrientation; // @synthesize startingViewOrientation=m_startingViewOrientation;
@property(retain, nonatomic) UIView *rightwardView; // @synthesize rightwardView=m_rightwardView;
@property(retain, nonatomic) UIView *leftwardView; // @synthesize leftwardView=m_leftwardView;
@property(retain, nonatomic) UIView *startingView; // @synthesize startingView=m_startingView;
@property(retain, nonatomic) SBApplication *rightwardApp; // @synthesize rightwardApp=m_rightwardApp;
@property(retain, nonatomic) SBApplication *leftwardApp; // @synthesize leftwardApp=m_leftwardApp;
@property(retain, nonatomic) SBApplication *endingApp; // @synthesize endingApp=m_endingApp;
@property(retain, nonatomic) SBApplication *startingApp; // @synthesize startingApp=m_startingApp;
@property(nonatomic) int orientation; // @synthesize orientation=m_orientation;
@property(readonly, nonatomic) BOOL pagingRightward;
@property(readonly, nonatomic) BOOL pagingLeftward;
- (BOOL)isPagingOverflowPercentage:(CGFloat)arg1;
- (BOOL)isPagingUnderflowPercentage:(CGFloat)arg1;
- (void)stretchTransformerAnimationDidStop:(BOOL)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)moveToContentOffset:(CGFloat)arg1 percentage:(CGFloat)arg2 animated:(BOOL)arg3;
- (void)moveToApp:(id)arg1 animated:(BOOL)arg2;
- (void)moveToApp:(id)arg1;
- (CGFloat)opacityForPercentage:(CGFloat)arg1;
- (CGFloat)scaleForPercentage:(CGFloat)arg1;
- (CGFloat)percentageForApp:(id)arg1;
- (CGFloat)contentOffsetForApp:(id)arg1;
- (void)finishBackwardToStartWithCompletion:(id)arg1;
- (void)finishForwardToEndWithPercentage:(CGFloat)arg1 completion:(id)arg2;
- (void)updatePaging:(CGFloat)arg1;
- (void)beginPaging;
- (id)viewForApp:(id)arg1;
- (void)transformGestureViewContainer:(id)arg1;
- (void)dealloc;
- (id)initWithInterfaceOrientation:(int)arg1 startingApp:(id)arg2 leftwardApp:(id)arg3 rightwardApp:(id)arg4;

@end

