/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKit.h>

#import "SBWallpaperObserver-Protocol.h"
#import "_SBFakeBlurObserver-Protocol.h"
#import "_SBFakeBlur-Protocol.h"

typedef NS_ENUM(NSInteger, SBWallpaperVariant) {
    SBWallpaperVariantLockScreen,
    SBWallpaperVariantHomeScreen
};

@interface SBWallpaperEffectView : UIView <_SBFakeBlurObserver, SBWallpaperObserver>
{
    int _variant;
    UIColor *_wallpaperAverageColor;
    int _startStyle;
    int _endStyle;
    CGFloat _transitionFraction;
    UIView<_SBFakeBlur> *_blurView;
    UIView *_grayscaleTintView;
    UIView *_colorTintView;
    UIView<_SBFakeBlur> *_transitionBlurView;
    UIView *_transitionGrayscaleTintView;
    UIView *_transitionColorTintView;
    UIImageView *_maskImageView;
    UIView *_blurMaskingContainer;
    UIView *_tintMaskingContainer;
    UIImage *_maskImage;
    BOOL _shouldMaskBlur;
    BOOL _shouldMaskTint;
    BOOL _accessibilityIncreaseContrastEnabled;
}

+ (id)imageInRect:(CGRect)arg1 forVariant:(NSInteger)arg2 withStyle:(NSInteger)arg3 zoomFactor:(CGFloat)arg4 mask:(id)arg5 masksBlur:(BOOL)arg6 masksTint:(BOOL)arg7;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_accessibilityEnhanceBackgroundContrastChanged:(id)arg1;
- (void)_clearView:(id *)arg1;
- (void)_configureGrayscaleTintView:(id *)arg1 colorTintView:(id *)arg2 forStyle:(NSInteger)arg3;
- (void)_configureViews;
- (void)_configureForCurrentBlurStyle;
- (void)_configureFromScratch;
- (void)_setTransitionFraction:(CGFloat)arg1;
- (void)_updateWallpaperAverageColor:(id)arg1;
- (void)wallpaperDidChangeForVariant:(NSInteger)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(NSInteger)arg2;
- (void)fakeBlurView:(id)arg1 didChangeStyle:(NSInteger)arg2;

/*
    Setting a mask on the layer of this view does not work correctly; it gets removed when -layoutSubviews is called.
    Convert the CALayer mask to an image and then set it here.
    Mask gets weirdly compressed, however.
*/
- (void)setMaskImage:(UIImage *)maskImage masksBlur:(BOOL)maskBlur masksTint:(BOOL)maskTint;

- (BOOL)currentTransitionStateIsOpaque;
- (void)setTransitionState:(SBWallpaperTransitionState)state;
- (BOOL)prepareToAnimateToTransitionState:(inout SBWallpaperTransitionState *)state;
- (void)setStyle:(NSInteger)style;

- (instancetype)initWithWallpaperVariant:(SBWallpaperVariant)variant;

@end

