/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

#import "SBFWallpaperViewInternalObserver-Protocol.h"
#import "SBFWallpaperViewLegibilityObserver-Protocol.h"
#import "SBUIActiveOrientationObserver-Protocol.h"

@class NSHashTable, NSMutableSet, SBFWallpaperView, SBWallpaperEffectView, SBWallpaperPreviewSnapshotCache, UIView, UIWindow;

@interface SBWallpaperController : NSObject <SBFWallpaperViewLegibilityObserver, SBFWallpaperViewInternalObserver, SBUIActiveOrientationObserver, UIWindowDelegate>
{
    UIWindow *_wallpaperWindow;
    UIView *_wallpaperContainerView;
    NSInteger _orientation;
    SBFWallpaperView *_lockscreenWallpaperView;
    SBFWallpaperView *_homescreenWallpaperView;
    SBFWallpaperView *_sharedWallpaperView;
    NSHashTable *_lockscreenObservers;
    NSHashTable *_homescreenObservers;
    CDStruct_f206ec99 _lockscreenPriorityInfo[3];
    CDStruct_f206ec99 _homescreenPriorityInfo[6];
    CDStruct_04b3617e _lockscreenStyleTransitionState;
    CDStruct_04b3617e _homescreenStyleTransitionState;
    SBWallpaperEffectView *_lockscreenEffectView;
    SBWallpaperEffectView *_homescreenEffectView;
    NSMutableSet *_suspendColorSamplingReasons;
    NSMutableSet *_suspendWallpaperAnimationReasons;
    NSMutableSet *_requireWallpaperReasons;
    NSMutableSet *_hideHomescreenWallpaperReasons;
    NSMutableSet *_hideLockscreenWallpaperReasons;
    NSInteger _displayedVariant;
    CGFloat _lockscreenOnlyWallpaperAlpha;
    NSHashTable *_lockscreenBlurViews;
    NSHashTable *_homescreenBlurViews;
    NSInteger _disallowRasterizationBlockCount;
    NSMutableSet *_disallowRasterizationReasonsHomeVariant;
    NSMutableSet *_disallowRasterizationReasonsLockVariant;
    CGColorRef _homescreenLightForegroundBlurColor;
    CGRect _homescreenLightForegroundBlurColorRect;
    BOOL _isSuspendingMotionEffectsForBlur;
    SBWallpaperPreviewSnapshotCache *_previewCache;
    NSInteger _activeOrientationSource;
    BOOL _coalescingGeometryChanges;
    NSInteger _locationsWithCoalescedGeometryChanges;
    CGFloat _homescreenWallpaperScale;
    CGFloat _lockscreenWallpaperScale;
}

+ (instancetype)sharedInstance;

@property(nonatomic) CGFloat lockscreenWallpaperScale; // @synthesize lockscreenWallpaperScale=_lockscreenWallpaperScale;
@property(nonatomic) CGFloat homescreenWallpaperScale; // @synthesize homescreenWallpaperScale=_homescreenWallpaperScale;
@property(nonatomic) NSInteger variant;
@property(nonatomic) CGFloat windowLevel;

- (id)initWithOrientation:(NSInteger)orientation variant:(NSInteger)variant;
- (void)activeInterfaceOrientationDidChangeToOrientation:(NSInteger)arg1 willAnimateWithDuration:(NSTimeInterval)arg2 fromOrientation:(NSInteger)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(NSInteger)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(NSInteger)arg1 duration:(NSTimeInterval)arg2;
- (BOOL)_isAcceptingOrientationChangesFromSource:(NSInteger)arg1;
- (void)setActiveOrientationSource:(NSInteger)arg1 andUpdateToOrientation:(NSInteger)arg2;
- (void)_updateRasterizationState;
- (void)_endDisallowRasterizationBlock;
- (void)_beginDisallowRasterizationBlock;
- (id)_getImageInRect:(struct CGRect)arg1 withZoomFactor:(CGFloat)arg2 forVariant:(NSInteger)arg3 style:(inout NSInteger *)arg4;
- (id)_newFakeBlurViewForVariant:(NSInteger)arg1;
- (void)_clearHomescreenLightForegroundBlurColor;
- (void)_createHomescreenLightForegroundBlurColorIfNecessary;
- (void)_updateBlurGeneration;
- (id)_sourceForFakeBlurView:(id)arg1;
- (void)_unregisterFakeBlurView:(id)arg1;
- (void)_registerFakeBlurView:(id)arg1;
- (void)_suspendOrResumeWallpaperAnimation;
- (void)_suspendOrResumeColorSampling;
- (id)_blurViewsForVariant:(NSInteger)arg1;
- (id)_observersForVariant:(NSInteger)arg1;
- (id)_wallpaperViewForVariant:(NSInteger)arg1;
- (id)_blurImageObservableForBlurView:(id)arg1 sourceView:(id)arg2;
- (void)_updateBlurImagesForVariant:(NSInteger)arg1;
- (void)_reconfigureBlurViewsForVariant:(NSInteger)arg1;
- (void)_handleWallpaperGeometryChangedForVariant:(NSInteger)arg1;
- (void)_handleWallpaperLegibilitySettingsChanged:(id)arg1 forVariant:(NSInteger)arg2;
- (void)_handleWallpaperChangedForVariant:(NSInteger)arg1;
- (BOOL)_updateEffectViewForVariant:(NSInteger)arg1 withFactory:(id)arg2;
- (void)_updateMotionEffectsForState:(CDStruct_04b3617e)arg1;
- (BOOL)_shouldSuspendMotionEffectsForState:(CDStruct_04b3617e)arg1;
- (void)_endSuspendingMotionEffectsForBlurIfNeeded;
- (void)_beginSuspendingMotionEffectsForBlurIfNeeded;
- (void)_updateScreenBlanked;
- (void)_accessibilityEnhanceBackgroundContrastChanged:(id)arg1;
- (void)_motionEffectsChanged;
- (id)_newWallpaperEffectViewForVariant:(NSInteger)arg1 transitionState:(CDStruct_04b3617e)arg2;
- (void)_clearWallpaperEffectView:(id *)arg1;
- (void)_clearWallpaperView:(id *)arg1;
- (id)_newWallpaperViewForProcedural:(id)arg1 orImage:(id)arg2;
- (void)_updateSeparateWallpaper;
- (void)_updateSharedWallpaper;
- (void)_updateWallpaperForLocations:(NSInteger)arg1 withCompletion:(id)arg2;
- (BOOL)variantsShareWallpaper;
- (void)_updateWallpaperHidden;
- (void)_setWallpaperHidden:(BOOL)arg1 variant:(NSInteger)arg2 reason:(id)arg3;
- (BOOL)_setDisallowRasterization:(BOOL)arg1 withReason:(id)arg2 reasons:(id)arg3;
- (BOOL)_isRasterizationDisallowedForCurrentVariant;
- (void)setDisallowsRasterization:(BOOL)arg1 forVariant:(NSInteger)arg2 withReason:(id)arg3;
- (id)previewCache;
- (CGSize)homescreenLightForegroundBlurColorPhaseForRect:(CGRect)arg1;
- (CGColorRef)homescreenLightForegroundBlurColor;
- (id)averageColorInRect:(CGRect)arg1 forVariant:(NSInteger)arg2 withSmudgeRadius:(CGFloat)arg3;
- (id)averageColorInRect:(CGRect)arg1 forVariant:(NSInteger)arg2;
- (id)averageColorForVariant:(NSInteger)arg1;
- (id)legibilitySettingsForVariant:(NSInteger)arg1;
- (void)resumeWallpaperAnimationForReason:(id)arg1;
- (void)suspendWallpaperAnimationForReason:(id)arg1;
- (void)resumeColorSamplingForReason:(id)arg1;
- (void)suspendColorSamplingForReason:(id)arg1;
- (void)removeObserver:(id)arg1 forVariant:(NSInteger)arg2;
- (void)addObserver:(id)arg1 forVariant:(NSInteger)arg2;
- (void)endRequiringWithReason:(id)arg1;
- (void)beginRequiringWithReason:(id)arg1;
- (void)removeHomescreenStyleForGuidedAccessPriorityWithAnimationFactory:(id)arg1;
- (void)setHomescreenStyleForGuidedAccessPriorityWithAnimationFactory:(id)arg1;
- (BOOL)removeLockscreenStyleForPriority:(NSInteger)arg1 withAnimationFactory:(id)arg2;
- (BOOL)removeHomescreenStyleForPriority:(NSInteger)arg1 withAnimationFactory:(id)arg2;
- (BOOL)setLockscreenStyleTransitionState:(CDStruct_04b3617e)arg1 forPriority:(NSInteger)arg2 withAnimationFactory:(id)arg3;
- (BOOL)setHomescreenStyleTransitionState:(CDStruct_04b3617e)arg1 forPriority:(NSInteger)arg2 withAnimationFactory:(id)arg3;
- (BOOL)setLockscreenStyle:(NSInteger)arg1 forPriority:(NSInteger)arg2 withAnimationFactory:(id)arg3;
- (BOOL)setHomescreenStyle:(NSInteger)arg1 forPriority:(NSInteger)arg2 withAnimationFactory:(id)arg3;
- (CDStruct_04b3617e)currentHomescreenStyleTransitionState;
- (void)setLockscreenOnlyWallpaperAlpha:(CGFloat)arg1;
- (void)setLockscreenWallpaperContentsRect:(CGRect)arg1;
- (void)setVariant:(NSInteger)arg1 withOutAnimationFactory:(id)arg2 inAnimationFactory:(id)arg3 completion:(id)arg4;

@end

