//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAnimationStepper.h"

@class SBWallpaperEffectView;

@interface _SBWallpaperAnimationStepper : SBAnimationStepper
{
    int _variant;
    int _homescreenPriority;
    SBWallpaperEffectView *_toEffectView;
    SBWallpaperEffectView *_fromEffectView;
    CDStruct_04b3617e _toState;
    CDStruct_04b3617e _fromState;
}

@property(nonatomic) CDStruct_04b3617e fromState; // @synthesize fromState=_fromState;
@property(nonatomic) CDStruct_04b3617e toState; // @synthesize toState=_toState;
@property(retain, nonatomic) SBWallpaperEffectView *fromEffectView; // @synthesize fromEffectView=_fromEffectView;
@property(retain, nonatomic) SBWallpaperEffectView *toEffectView; // @synthesize toEffectView=_toEffectView;
@property(nonatomic) int homescreenPriority; // @synthesize homescreenPriority=_homescreenPriority;
@property(nonatomic) int variant; // @synthesize variant=_variant;
- (void)didFinishBackwardToStart;
- (void)setPercentage:(float)arg1;
- (void)dealloc;

@end

