//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BBSectionInfo.h"

@interface BBSectionInfo (SBWidgetSectionComparisonSupport)
- (id)sb_localizedDisplayName;
- (BOOL)sb_isNewWidget;
- (int)sb_compareWidgetConsideringShowsInNotificationCenter:(id)arg1;
- (int)sb_compareWidgetConsideringIsNew:(id)arg1;
- (int)sb_compareWidget:(id)arg1;
@end

