//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAppSwitcherPageView.h"

@class SBSaturatedIconView, UILabel, UIView;

@interface SBAppSwitcherContinuityAppPageView : SBAppSwitcherPageView
{
    UIView *_infoView;
    UIView *_iconTintView;
    SBSaturatedIconView *_saturatedIconView;
    UILabel *_deviceNameLabelBackdrop;
    UILabel *_deviceNameLabelForeground;
    float _deviceLabelOffset;
}

- (void)_viewDismissing:(id)arg1;
- (id)auxiliaryView;
- (void)layoutSubviews;
- (float)_heightForDeviceLabel:(id)arg1 withWidth:(float)arg2;
- (void)setView:(id)arg1 animated:(BOOL)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 suggestedApp:(id)arg2;

@end

