//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSObject<OS_dispatch_queue>, NSString, NSURL;

@interface SBAppSwitcherPeopleContactAction : NSObject <NSCopying>
{
    unsigned int _contactType;
    int _abRecordID;
    NSString *_label;
    NSString *_destinationID;
    NSObject<OS_dispatch_queue> *_urlUpdateQueue;
    unsigned int _actionType;
}

@property(readonly, nonatomic) NSString *destinationID; // @synthesize destinationID=_destinationID;
@property(readonly, nonatomic) NSString *label; // @synthesize label=_label;
@property(readonly, nonatomic) unsigned int actionType; // @synthesize actionType=_actionType;
- (id)description;
@property(readonly, nonatomic) NSURL *url;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithType:(unsigned int)arg1 label:(id)arg2 destinationID:(id)arg3 addressBookRecordID:(int)arg4;

@end

