//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, NSString, SBAppSwitcherPeopleContactItem, UIImage;

@protocol SBAppSwitcherPeopleDataSource <NSObject>
@property(nonatomic) id <SBAppSwitcherPeopleDataSourceConsumer> consumer;
- (void)purgeCaches;
- (UIImage *)silhouetteMonogramOfSize:(float)arg1;
- (UIImage *)existingCachedMonogramImageForPersonID:(int)arg1 ofSize:(float)arg2 outIsMask:(char *)arg3;
- (void)cachedMonogramImageForPersonID:(int)arg1 ofSize:(float)arg2 generatingIfNecessaryWithResult:(void (^)(UIImage *, BOOL))arg3;
- (void)updateIfNecessary;
- (NSString *)optionalEmptyPlaceholderStringForSection:(unsigned int)arg1;
- (NSString *)titleForSection:(unsigned int)arg1;
- (SBAppSwitcherPeopleContactItem *)contactItemForIndexPath:(NSIndexPath *)arg1;
- (unsigned int)numberOfContactsInSection:(unsigned int)arg1;
- (unsigned int)numberOfSections;
@end

