//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBAppSwitcherPageContentView.h"

@class NSObject<OS_dispatch_queue>, NSString, SBAppSwitcherSettings, SBAppSwitcherStatusBarViewCache, SBApplication, SBDisplayItem, SBSnapshotImageInfo, SBWallpaperEffectView, SBZoomableCrossfadeView, UIImage, UIImageView, UIView<SBAppSwitcherCacheVended>;

@interface SBAppSwitcherSnapshotView : UIView <SBAppSwitcherPageContentView>
{
    SBDisplayItem *_displayItem;
    SBApplication *_application;
    UIView *_containerView;
    SBAppSwitcherSettings *_settings;
    SBWallpaperEffectView *_wallpaperEffectView;
    SBSnapshotImageInfo *_snapshotImageInfo;
    UIImageView *_snapshotImageView;
    struct CGSize _imageSize;
    SBZoomableCrossfadeView *_updateCrossfadeView;
    SBZoomableCrossfadeView *_zoomUpCrossfadeView;
    UIImageView *_zoomUpSnapshotView;
    struct CGSize _zoomUpImageSize;
    UIImage *_deferredUpdateImage;
    SBAppSwitcherStatusBarViewCache *_statusBarCache;
    UIView<SBAppSwitcherCacheVended> *_statusBar;
    BOOL _isVisible;
    BOOL _simplifyForMotion;
    BOOL _invalidated;
    BOOL _needsZoomFilter;
    BOOL _loadedImage;
    BOOL _needsZoomUpImage;
    int _appSnapshotUpdatedSequenceID;
    NSObject<OS_dispatch_queue> *_snapshotQueue;
    BOOL _shouldTransitionToDefaultPng;
    int _orientation;
}

+ (id)_fallbackDefaultBackgroundColor;
+ (id)appSwitcherSnapshotViewForDisplayItem:(id)arg1 orientation:(int)arg2 loadAsync:(BOOL)arg3 withQueue:(id)arg4 statusBarCache:(id)arg5;
@property BOOL invalidated; // @synthesize invalidated=_invalidated;
@property(retain, nonatomic) UIImage *deferredUpdateImage; // @synthesize deferredUpdateImage=_deferredUpdateImage;
@property(retain, nonatomic) SBZoomableCrossfadeView *updateCrossfadeView; // @synthesize updateCrossfadeView=_updateCrossfadeView;
@property(nonatomic) BOOL shouldTransitionToDefaultPng; // @synthesize shouldTransitionToDefaultPng=_shouldTransitionToDefaultPng;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) SBSnapshotImageInfo *snapshotImageInfo; // @synthesize snapshotImageInfo=_snapshotImageInfo;
@property(readonly, copy, nonatomic) SBDisplayItem *displayItem; // @synthesize displayItem=_displayItem;
- (void)_viewDismissing:(id)arg1;
- (void)_viewPresenting:(id)arg1;
- (void)_updateStatusbarTranslucency;
- (void)_updateTranslucency;
- (id)_snapshotImageForImageInfo:(id)arg1 downscaledIfAvailable:(BOOL)arg2 downscaledWasAvailableOut:(out char *)arg3;
- (struct CGImage *)_cgImageForSnapshotInfo:(id)arg1 downscaled:(BOOL)arg2;
- (id)_cachedImageForImageInfos:(id)arg1 downscaled:(BOOL)arg2 foundInfo:(out id *)arg3;
- (struct CGAffineTransform)_rotationTransformForOrientation;
- (int)_containerOrientation;
- (struct CGRect)_snapshotFrame;
- (void)_snapshotImageLoaded:(struct CGImage *)arg1 withInfo:(id)arg2 downscaled:(BOOL)arg3;
- (void)_loadImageAsyncFromSnapshotInfo:(id)arg1;
- (void)_loadImageAsyncBodySnapshotInfo:(id)arg1 displayItem:(id)arg2;
- (BOOL)_queue_keepGoing;
- (struct CGImage *)_queue_createDecodedImageIfPossible:(struct CGImage *)arg1;
- (id)_snapshotInfos;
- (id)_snapshotInfoForDefaultPNGWithLaunchOrientation:(int)arg1;
- (id)_snapshotInfoForDefaultPNG;
- (id)_snapshotInfoForSnapshotFromInfos:(id)arg1;
- (id)_cachedSnapshotForSnapshotInfos:(id)arg1 downscaled:(BOOL)arg2 foundInfo:(out id *)arg3;
- (id)_snapshotName;
- (void)_loadSnapshotAsync;
- (void)_loadZoomUpSnapshotSync;
- (void)_loadSnapshotSync;
- (id)_imageFromSnapshotInfos:(id)arg1 forZoomUp:(BOOL)arg2 loadedImageInfoOut:(out id *)arg3 loadedDownscaledOut:(out char *)arg4;
- (void)invalidate;
- (void)setOrientation:(int)arg1 orientationBehavior:(int)arg2;
- (void)layoutSubviews;
- (void)_layoutContainer;
- (void)_crossfadeToNewSnapshotImage:(id)arg1;
- (void)_crossfadeToZoomUpViewIfNecessary;
- (void)_snapshotChanged:(id)arg1;
- (void)respondToBecomingInvisibleIfNecessary;
- (void)prepareToBecomeVisibleIfNecessary;
- (void)unsimplifyAfterMotion;
- (void)simplifyForMotion;
- (void)_layoutStatusBar;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithDisplayItem:(id)arg1 application:(id)arg2 orientation:(int)arg3 async:(BOOL)arg4 withQueue:(id)arg5 statusBarCache:(id)arg6;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

