//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString, SBAppSwitcherScrollView, SBStopScrollingGestureRecognizer, UITapGestureRecognizer;

@interface SBAppSwitcherPageViewController : UIViewController <UIScrollViewDelegate>
{
    NSMutableArray *_displayLayouts;
    NSMutableDictionary *_items;
    BOOL _itemsListIsValid;
    SBAppSwitcherScrollView *_scrollView;
    BOOL _dragMaster;
    BOOL _preventScroll;
    UITapGestureRecognizer *_tapGesture;
    SBStopScrollingGestureRecognizer *_stopScrollingGesture;
    int _layoutOrientation;
    CDUnknownBlockType _scrollDoneBlock;
    BOOL _isMoving;
    BOOL _isLayingOutForReachability;
    id <SBAppSwitcherScrollingViewDelegate> _delegate;
}

@property(nonatomic) id <SBAppSwitcherScrollingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleReachabilityModeDeactivated;
- (void)handleReachabilityModeActivated;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_notifyDelegateOfKillOffsetChange;
- (void)_fireAndCleanupScrollCompleteBlockIfNecessary;
- (void)_setContentOffset:(struct CGPoint)arg1 animated:(BOOL)arg2;
- (void)_enableScrolling;
- (void)_disableScrolling;
- (BOOL)_isItemVisible:(id)arg1 withSidePadding:(float)arg2;
- (void)_updateVisiblePageViews;
- (void)_layout;
- (void)_layoutItemContainer:(id)arg1;
- (void)_generateContentViewForDisplayLayoutIfNecessary:(id)arg1;
- (struct CGRect)_naturalScrollViewFrame;
- (struct CGPoint)_centerOfIndex:(unsigned int)arg1;
- (float)_distanceBetweenCenters;
- (void)_handleStopGesture:(id)arg1;
- (void)_handleTapGesture:(id)arg1;
- (void)replaceItemAtIndex:(unsigned int)arg1 withNewItem:(id)arg2 duration:(double)arg3;
- (void)removeItem:(id)arg1 duration:(double)arg2 updateScrollPosition:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)insertItem:(id)arg1 atIndex:(unsigned int)arg2 duration:(double)arg3 updateScrollPosition:(BOOL)arg4 completion:(CDUnknownBlockType)arg5;
- (void)cancelPossibleRemovalOfDisplayItem:(id)arg1;
- (id)_createScrollViewForItem;
- (void)reloadInOrientation:(int)arg1;
- (float)_halfWidth;
- (id)_safeDelegate;
- (void)loadView;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (float)preferredHeightForOrientation:(int)arg1;
- (void)switcherWasDismissed:(BOOL)arg1;
- (struct _NSRange)visibleItems;
- (BOOL)isScrolling;
- (BOOL)_isAnyScrollContainerScrolling;
- (id)pageViewForDisplayLayout:(id)arg1;
- (unsigned int)currentPage;
- (void)_setScrollingDoneBlock:(CDUnknownBlockType)arg1;
- (BOOL)isDisplayLayoutVisible:(id)arg1;
- (unsigned int)settledIndexForNormalizedOffset:(inout float *)arg1 andXVelocity:(float)arg2;
@property(nonatomic) float normalizedOffset;
- (void)setOffsetToIndex:(unsigned int)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setOffsetToIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)cancelScrolling;
- (void)cancelTracking;
- (float)_maxXOffset;
@property(copy, nonatomic) NSArray *displayLayouts;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

