//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBApplicationPlaceholderObserver.h"
#import "SBLeafIconDataSource.h"

@class FBApplicationPlaceholder, NSMutableDictionary, NSMutableSet, NSString;

@interface SBApplicationPlaceholder : NSObject <FBApplicationPlaceholderObserver, SBLeafIconDataSource>
{
    FBApplicationPlaceholder *_placeholderProxy;
    NSString *_applicationBundleID;
    NSString *_applicationDisplayName;
    double _fractionProgress;
    BOOL _installing;
    BOOL _isNewsstand;
    BOOL _observingKVO;
    unsigned int _installType;
    BOOL _invalidated;
    NSMutableDictionary *_generatedIconImagesByKey;
    NSMutableSet *_formatsPendingGeneration;
}

+ (id)backgroundQueue;
@property(copy, nonatomic) NSString *applicationDisplayName; // @synthesize applicationDisplayName=_applicationDisplayName;
@property(copy, nonatomic) NSString *applicationBundleID; // @synthesize applicationBundleID=_applicationBundleID;
- (BOOL)icon:(id)arg1 launchFromLocation:(int)arg2;
- (BOOL)iconAllowsLaunch:(id)arg1;
- (BOOL)iconCompleteUninstall:(id)arg1;
- (BOOL)iconAllowsUninstall:(id)arg1;
- (BOOL)iconIsBeta:(id)arg1;
- (BOOL)iconIsRecentlyUpdated:(id)arg1;
- (id)iconFormattedAccessoryString:(id)arg1;
- (id)iconBadgeNumberOrString:(id)arg1;
- (int)iconAccessoryType:(id)arg1;
- (BOOL)iconProgressIsPaused:(id)arg1;
- (float)iconProgressPercent:(id)arg1;
- (int)iconProgressState:(id)arg1;
- (BOOL)iconAppearsInNewsstand:(id)arg1;
- (BOOL)iconCanTightenLabel:(id)arg1;
- (BOOL)iconCanEllipsizeLabel:(id)arg1;
- (id)icon:(id)arg1 defaultImageWithFormat:(int)arg2;
- (id)icon:(id)arg1 imageWithFormat:(int)arg2;
- (unsigned int)iconPriority:(id)arg1;
- (id)iconDisplayName:(id)arg1;
- (void)_reloadThumbnailImage;
- (void)_generatePendingIconFormats;
- (void)_generateIconImageWithFormat:(int)arg1;
- (id)_iconImageKeyForBundleID:(id)arg1 format:(int)arg2;
- (int)_newsstandImageOptions;
- (id)_defaultIconImageWithFormat:(int)arg1;
- (id)_getOrGenerateIconImageWithFormat:(int)arg1;
- (void)placeholderDidChangeSignificantly:(id)arg1;
- (void)placeholderInstallPhaseDidChange:(id)arg1;
- (void)placeholderInstallStateDidChange:(id)arg1;
- (void)placeholderPausabilityDidChange:(id)arg1;
- (void)placeholderCancellabilityDidChange:(id)arg1;
- (void)placeholderPercentCompleteDidChange:(id)arg1;
- (void)_progressChanged;
- (BOOL)_shouldDisplayAppName;
- (id)_downloadingLabel;
- (void)_prioritize;
- (void)cancel;
- (void)resume;
- (void)pause;
- (BOOL)isNewsstand;
- (BOOL)isContentRestricted;
- (BOOL)isInstalling;
- (BOOL)isDownloading;
- (BOOL)isCancelable;
- (BOOL)isPausable;
- (BOOL)isFailed;
- (BOOL)isPaused;
- (BOOL)isActive;
- (BOOL)isDone;
- (unsigned int)installType;
- (id)fetchIconImageWithFormat:(int)arg1;
- (void)iconChanged;
@property(retain, nonatomic) FBApplicationPlaceholder *placeholderProxy; // @synthesize placeholderProxy=_placeholderProxy;
@property(readonly, copy) NSString *description;
- (BOOL)isEqual:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithPlaceholderProxy:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

