//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollViewDelegate.h"

@class NSIndexPath, NSString, SBAppSwitcherPeopleScrollView, SBScrollViewItemWrapper, UIView<SBPeopleScrollViewItemView>;

@protocol SBAppSwitcherPeopleScrollViewDelegate <UIScrollViewDelegate>
- (NSString *)peopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1 placeholderStringForEmptySection:(unsigned int)arg2;
- (NSString *)peopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1 titleForSection:(unsigned int)arg2;
- (struct CGSize)peopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1 sizeForItem:(id)arg2 expanded:(BOOL)arg3;
- (struct CGSize)peopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1 sizeForPlaceholderForSection:(int)arg2;
- (UIView<SBPeopleScrollViewItemView> *)peopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1 viewForItem:(id <NSCopying>)arg2;
- (SBScrollViewItemWrapper *)peopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1 itemAtIndexPath:(NSIndexPath *)arg2;
- (int)peopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInPeopleScrollView:(SBAppSwitcherPeopleScrollView *)arg1;
@end

