//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIPluginHost.h"

@class BSEventQueue, FBUIApplicationResignActiveAssertion, NSHashTable, NSMutableSet, NSString, SBAssistantWindow, SBPasscodeLockDisableAssertion, UIViewController<SBUIPluginViewControllerInterface>;

@interface SBAssistantController : SBUIPluginHost
{
    BSEventQueue *_operationQueue;
    NSString *_appDisplayIDBeingHosted;
    SBAssistantWindow *_assistantWindow;
    BOOL _unlockedDevice;
    BOOL _launchedInStark;
    BOOL _isHidingOtherWindows;
    int _activationEvent;
    SBPasscodeLockDisableAssertion *_disableAssertion;
    NSMutableSet *_dismissingReasons;
    int _pendingDismissViewType;
    NSHashTable *_observers;
    FBUIApplicationResignActiveAssertion *_resignActiveAssertion;
    UIViewController<SBUIPluginViewControllerInterface> *_mainScreenViewController;
}

+ (BOOL)isAssistantRunningHidden;
+ (BOOL)isAssistantViewVisible:(int)arg1;
+ (BOOL)isAssistantVisible;
+ (BOOL)shouldEnterAssistant;
+ (BOOL)supportedAndEnabled;
+ (id)sharedInstanceIfExists;
+ (id)sharedInstance;
@property(nonatomic) BOOL unlockedDevice; // @synthesize unlockedDevice=_unlockedDevice;
- (void)uiPlugin:(id)arg1 forceUpdateToInterfaceOrientation:(int)arg2 animated:(BOOL)arg3;
- (void)uiPlugin:(id)arg1 isNowRunning:(BOOL)arg2;
- (void)uiPluginUserEventOccurred:(id)arg1;
- (BOOL)uiPlugin:(id)arg1 openURL:(id)arg2;
- (BOOL)uiPlugin:(id)arg1 launchApplicationWithBundleID:(id)arg2 openURL:(id)arg3 allowDismissal:(BOOL)arg4;
- (BOOL)uiPluginAttemptDeviceUnlock:(id)arg1 withPassword:(id)arg2 lockViewOwner:(id)arg3;
- (BOOL)uiPluginWantsActivation:(id)arg1 forEvent:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_dismissUIPlugin:(id)arg1 animated:(BOOL)arg2;
- (void)dismissPluginForEvent:(int)arg1;
- (BOOL)pluginSuppressesNotifications;
- (BOOL)pluginWantsScreenDimInterval:(double *)arg1;
- (BOOL)pluginWantsInterfaceOrientation:(int *)arg1;
- (void)preparePluginForActivationEvent:(int)arg1 eventSource:(int)arg2 afterInterval:(double)arg3;
- (BOOL)pluginWantsActivationEvent:(int)arg1 eventSource:(int)arg2 interval:(double *)arg3;
- (void)_viewController:(id)arg1 animateDisappearanceWithContext:(id)arg2;
- (void)_viewController:(id)arg1 willAnimateDisappearanceWithContext:(id)arg2;
- (void)_viewController:(id)arg1 animateAppearanceWithContext:(id)arg2;
- (void)_viewController:(id)arg1 willAnimateAppearanceWithContext:(id)arg2;
- (void)_viewController:(id)arg1 setShowsStatusBar:(BOOL)arg2;
- (void)_dismissForMainScreenWithFactory:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_fakeStatusBarForOrientation:(int)arg1;
- (void)_presentForMainScreenAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_notifyObserversViewDidDisappear:(int)arg1;
- (void)_notifyObserversViewWillDisappear:(int)arg1;
- (void)_notifyObserversViewDidAppear:(int)arg1;
- (void)_notifyObserversViewWillAppear:(int)arg1;
- (void)_viewDidDisappearWithType:(int)arg1;
- (void)_viewDidAppearWithType:(int)arg1;
- (void)_bioAuthenticated:(id)arg1;
- (void)_starkSiriDidDisappear:(id)arg1;
- (void)_starkSiriWillDisappear:(id)arg1;
- (void)_starkSiriDidAppear:(id)arg1;
- (void)_starkSiriWillAppear:(id)arg1;
- (void)_viewDidDisappearOnMainScreen:(BOOL)arg1;
- (void)_viewWillDisappearOnMainScreen:(BOOL)arg1;
- (void)_viewDidAppearOnMainScreen:(BOOL)arg1;
- (void)_viewWillAppearOnMainScreen:(BOOL)arg1;
- (id)_activationSettingsWithDismissalDisallowed:(BOOL)arg1;
- (BOOL)_isPluginLoaded;
- (void)_loadPlugin;
- (BOOL)_isDismissingAllViews;
- (double)_defaultAnimatedDismissDurationForMainScreen;
- (id)transferOwnershipOfPasscodeLockDisableAssertion;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)mainScreenView;
- (id)window;
- (BOOL)activateIgnoringTouches;
- (BOOL)shouldShowLockStatusBarTime;
- (void)dismissAssistantView:(int)arg1 forAlertActivation:(id)arg2;
- (void)dismissAssistantViewIfNecessary:(int)arg1 withAnimation:(int)arg2 factory:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)dismissAssistantViewIfNecessary:(int)arg1 withAnimation:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissAssistantViewIfNecessary:(int)arg1 withAnimation:(int)arg2;
- (void)dismissAssistantViewIfNecessary:(int)arg1;
- (id)activationSettings;
- (void)handleSiriPreheatCommand;
- (void)handleSiriButtonUpEventFromSource:(int)arg1;
- (BOOL)handleSiriButtonDownEventFromSource:(int)arg1 activationEvent:(int)arg2;
- (void)_notePluginVisibilityDidChange;
- (void)dealloc;
- (id)init;
- (BOOL)_runActivateAssistantTest:(id)arg1;
- (void)_activateSiriForPPT;
- (BOOL)isAssistantViewVisible:(int)arg1;

@end

