//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "SBAwayListCellButtonHandler.h"
#import "SBUIQuietModePlayability.h"

@class NSDate, NSString, SBLockScreenActionContext;

@interface SBAwayListItem : NSObject <SBAwayListCellButtonHandler, SBUIQuietModePlayability, NSCopying>
{
    NSDate *_timestamp;
    BOOL _isNewItem;
    SBLockScreenActionContext *_lockScreenActionContext;
    NSString *_buttonLabel;
}

@property(copy, nonatomic) NSString *buttonLabel; // @synthesize buttonLabel=_buttonLabel;
@property(nonatomic) BOOL isNewItem; // @synthesize isNewItem=_isNewItem;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
- (BOOL)overridesQuietMode;
- (BOOL)isCritical;
- (BOOL)inertWhenLocked;
- (void)dealloc;
- (void)prepareWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)canBeClearedByNotificationCenter;
- (BOOL)wantsHighlightOnInsert;
- (void)buttonPressed;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

