//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBoundLayoutConstraint.h"

@interface SBBaselineBoundLayoutConstraint : SBBoundLayoutConstraint
{
    float _baselineConstant;
}

+ (id)constraintWithItem:(id)arg1 attribute:(int)arg2 relatedBy:(int)arg3 toItem:(id)arg4 attribute:(int)arg5 textAttributesObject:(id)arg6 keyPath:(id)arg7 baselineConstant:(float)arg8;
- (void)_boundValueDidChange;

@end

