//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BKSProcessAssertion, NSString;

@interface SBBackgroundFetchTask : NSObject
{
    BOOL _finished;
    BKSProcessAssertion *_assertion;
    CDUnknownBlockType _completionHandler;
    NSString *_bundleID;
    unsigned int _trigger;
    int _sequenceNumber;
}

@property(readonly) BOOL finished; // @synthesize finished=_finished;
@property(readonly) int sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;
@property(readonly) unsigned int trigger; // @synthesize trigger=_trigger;
@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) BKSProcessAssertion *assertion; // @synthesize assertion=_assertion;
- (id)description;
- (void)dealloc;
- (void)_fireCompletionHandlerWithResult:(unsigned int)arg1;
- (void)finishWithResult:(unsigned int)arg1;
- (id)initForApplication:(id)arg1 trigger:(unsigned int)arg2 sequenceNumber:(int)arg3 withCompletion:(CDUnknownBlockType)arg4;

@end

