//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBannerGestureHandler.h"

@class _UIDynamicValueAnimation;

@interface SBBannerPullDownGestureHandler : SBBannerGestureHandler
{
    BOOL _pulledDown;
    BOOL _startedPulledDown;
    _UIDynamicValueAnimation *_animation;
    BOOL _invalidated;
    BOOL _completed;
}

- (void)_stopAnimating;
- (float)_finalDisplacementForShow:(BOOL)arg1;
- (id)_pullForShow:(BOOL)arg1 finalDisplacement:(float)arg2;
- (id)_boundaryForShow:(BOOL)arg1 finalDisplacement:(float)arg2;
- (id)_newAnimationForShow:(BOOL)arg1 withDisplacement:(double)arg2 velocity:(double)arg3;
- (float)_pullDownDistance;
- (void)_updateWithDisplacement:(float)arg1 velocity:(float)arg2;
- (void)_finishGestureWithDisplacement:(float)arg1 velocity:(float)arg2;
- (BOOL)_shouldFinishWithLocation:(struct CGPoint)arg1 velocity:(float)arg2;
- (void)invalidate;
- (BOOL)handleGestureType:(int)arg1 state:(int)arg2 location:(struct CGPoint)arg3 displacement:(float)arg4 velocity:(float)arg5;
- (void)dealloc;

@end

