//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBUIBannerView.h"
#import "SBVibrantBannerView.h"

@class NSString, SBBannerViewCallbackManager, SBNotificationSeparatorView, SBUIBannerContext, UIImage, UIImageView, UIView<SBUIBannerView>, _UIBackdropView;

@interface SBBannerContextView : UIView <SBUIBannerView, SBVibrantBannerView>
{
    _UIBackdropView *_backdropView;
    UIImageView *_backgroundImageView;
    UIView *_contentContainerView;
    UIView<SBUIBannerView> *_contentView;
    UIView *_accessoryView;
    UIView *_pullDownView;
    UIView *_pullDownContainerView;
    UIView *_secondaryContentView;
    SBNotificationSeparatorView *_separatorView;
    SBUIBannerContext *_context;
    SBBannerViewCallbackManager *_callbacks;
    SBBannerViewCallbackManager *_wrapperCallbacks;
    BOOL _isDismissing;
    struct CGSize _grabberSize;
    UIView *_grabberView;
    BOOL _hidesGrabberOnPullDown;
    float _minimumHeight;
    struct {
        unsigned int providesDefaultElementColors:1;
        unsigned int supportsElementColors:1;
    } _contentViewFlags;
    BOOL _grabberVisible;
    BOOL _separatorVisible;
    float _maximumHeight;
    float _pullDownViewHeight;
    float _pullDownBottomOverhangHeight;
}

+ (id)defaultColorForElement:(int)arg1;
+ (id)_defaultButtonTextColor;
+ (id)_defaultButtonColor;
+ (id)_defaultGrabberColor;
@property(retain, nonatomic) UIView *secondaryContentView; // @synthesize secondaryContentView=_secondaryContentView;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(nonatomic) float pullDownBottomOverhangHeight; // @synthesize pullDownBottomOverhangHeight=_pullDownBottomOverhangHeight;
@property(nonatomic) float pullDownViewHeight; // @synthesize pullDownViewHeight=_pullDownViewHeight;
@property(retain, nonatomic) UIView *pullDownView; // @synthesize pullDownView=_pullDownView;
@property(nonatomic) BOOL separatorVisible; // @synthesize separatorVisible=_separatorVisible;
@property(nonatomic) BOOL grabberVisible; // @synthesize grabberVisible=_grabberVisible;
@property(nonatomic) float maximumHeight; // @synthesize maximumHeight=_maximumHeight;
@property(readonly, nonatomic, getter=isDismissing) BOOL dismissing; // @synthesize dismissing=_isDismissing;
- (float)_grabberAlpha;
- (id)_newGrabberView:(BOOL)arg1;
- (void)_setGrabberColor:(id)arg1;
- (id)_grabberColor;
- (BOOL)shouldBorrowScreen;
- (id)bannerContext;
- (struct CGSize)_contentSizeThatFits:(struct CGSize)arg1;
- (struct CGRect)_centeredBoundsForRect:(struct CGRect)arg1;
- (struct CGRect)_centeredBounds;
- (void)_layoutGrabber;
- (void)_layoutPullDownContainerView;
- (void)_layoutAccessoryView;
- (void)_updateContentAlpha;
- (void)_layoutSeparatorView;
- (void)_layoutContentView;
- (void)_layoutContentContainerView;
- (void)_layoutBackdropView;
- (void)_layoutBackgroundView;
- (void)layoutSubviews;
- (BOOL)_canPullDown;
- (float)_pullDownContentAlpha;
- (void)setColor:(id)arg1 forElement:(int)arg2;
- (id)colorForElement:(int)arg1;
- (id)_vibrantContentView;
- (id)defaultColorForElement:(int)arg1;
- (void)noteDidDismissWithReason:(int)arg1;
- (void)noteWillDismissWithReason:(int)arg1;
- (void)noteDidAppear;
- (void)noteWillAppear;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setBannerContext:(id)arg1 withReplaceReason:(int)arg2;
- (float)minimumHeight;
- (float)percentPulledDown;
- (BOOL)isPulledDown;
@property(retain, nonatomic) UIImage *backgroundImage;
@property(readonly, retain, nonatomic) _UIBackdropView *backdrop;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

