//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDynamicBehavior.h"

@class UIAttachmentBehavior, UICollisionBehavior, UIDynamicItemBehavior, UIGravityBehavior;

@interface SBBounceBehavior : UIDynamicBehavior
{
    float _midwayPosition;
    float _completionThreshold;
    struct CGRect _targetFrame;
    id <UIDynamicItem> _item;
    UIDynamicItemBehavior *_bodyBehavior;
    UICollisionBehavior *_collisionBehavior;
    UIGravityBehavior *_gravityBehavior;
    UIDynamicItemBehavior *_pushBehavior;
    UIAttachmentBehavior *_draggingBehavior;
    float _gravity;
    float _velocity;
    float _elasticity;
    float _friction;
    float _resistance;
    float _minVelocityToAssist;
    float _maxVelocityToAssist;
    float _maxVelocityAssistance;
    struct UIEdgeInsets _boundaryInsets;
}

@property(nonatomic) struct UIEdgeInsets boundaryInsets; // @synthesize boundaryInsets=_boundaryInsets;
@property(nonatomic) float maxVelocityAssistance; // @synthesize maxVelocityAssistance=_maxVelocityAssistance;
@property(nonatomic) float maxVelocityToAssist; // @synthesize maxVelocityToAssist=_maxVelocityToAssist;
@property(nonatomic) float minVelocityToAssist; // @synthesize minVelocityToAssist=_minVelocityToAssist;
@property(nonatomic) float resistance; // @synthesize resistance=_resistance;
@property(nonatomic) float friction; // @synthesize friction=_friction;
@property(nonatomic) float elasticity; // @synthesize elasticity=_elasticity;
@property(nonatomic) float velocity; // @synthesize velocity=_velocity;
@property(nonatomic) float gravity; // @synthesize gravity=_gravity;
- (BOOL)allowsAnimatorToStop;
- (float)_maxVelocityToAssist;
- (float)_minVelocityToAssist;
- (float)_velocityAssistance;
- (BOOL)_shouldAssistWithVelocity:(float)arg1;
- (float)_adjustedVelocity:(float)arg1;
- (float)_itemOriginY;
- (BOOL)_itemStopped;
- (BOOL)_itemCompleted;
- (BOOL)_itemPastMidway;
- (float)_percentRemaining;
- (float)_percentComplete;
- (void)_removeDraggingBehavior;
- (void)_beginInteraction;
- (void)finishInteraction;
- (void)finishInteractionWithVelocity:(struct CGPoint)arg1;
- (void)finishInteractionWithVelocity:(struct CGPoint)arg1 removingGravityAtMidway:(BOOL)arg2;
- (void)updateInteractionWithPoint:(struct CGPoint)arg1;
- (void)initiateInteractionFromPoint:(struct CGPoint)arg1;
- (void)bounce;
- (void)_setupCollisionBoundaries;
- (void)_frameCollisionBoundaryPoints:(struct CGPoint *)arg1;
- (BOOL)_isGravityDown;
- (BOOL)isActive;
- (void)dealloc;
- (id)initWithItem:(id)arg1;
- (id)initWithItem:(id)arg1 targetFrame:(struct CGRect)arg2;

@end

