//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UISettings.h"

@interface SBCarDisplaySettings : _UISettings
{
    BOOL _animateLockOutModeChanges;
    int _lockOutMode;
}

+ (id)settingsControllerModule;
@property int lockOutMode; // @synthesize lockOutMode=_lockOutMode;
@property BOOL animateLockOutModeChanges; // @synthesize animateLockOutModeChanges=_animateLockOutModeChanges;
- (void)setDefaultValues;

@end

