//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBCCSettingModule.h"

@class BBBehaviorOverride, BBSettingsGateway;

@interface SBCCDoNotDisturbSetting : SBCCSettingModule
{
    BBSettingsGateway *_settingsGateway;
    BBBehaviorOverride *_activeOverride;
    int _activeStatus;
}

+ (id)displayName;
+ (id)identifier;
- (id)glyphImageForState:(int)arg1;
- (id)statusUpdate;
- (void)_updateActiveOverrides:(id)arg1;
- (void)_setDNDEnabled:(BOOL)arg1 updateServer:(BOOL)arg2 source:(unsigned int)arg3;
- (void)_setDNDStatus:(int)arg1;
- (void)_updateState;
- (BOOL)_toggleState;
- (void)_tearDown;
- (void)deactivate;
- (void)activate;
- (id)aggdKey;
- (void)dealloc;

@end

