//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBCCButtonModule : NSObject
{
    BOOL _enabled;
    BOOL _inoperative;
    id <SBCCButtonModuleDelegate> _delegate;
}

+ (BOOL)enabledByDefault;
+ (BOOL)isSupported:(int)arg1;
+ (id)displayName;
+ (id)identifier;
@property(nonatomic, getter=isInoperative) BOOL inoperative; // @synthesize inoperative=_inoperative;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) id <SBCCButtonModuleDelegate> delegate; // @synthesize delegate=_delegate;
- (id)glyphImageForState:(int)arg1;
- (id)glyphImageForState:(int)arg1 section:(int)arg2;
- (id)unavailableText;
- (id)statusUpdate;
- (void)_updateState;
- (BOOL)_toggleState;
- (void)_noteDisplayPropertiesDidChange;
- (void)_noteButtonStateDidChange;
- (void)toggleState;
- (int)state;
- (BOOL)isRestricted;
- (void)cooldown;
- (void)warmup;
- (void)deactivate;
- (void)activate;
- (id)aggdKey;
- (id)displayName;
- (id)identifier;
- (id)description;

@end

