//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UISettings.h"

@class SBControlCenterSettingsSectionSettings, SBControlCenterShortcutSectionSettings, UIColor;

@interface SBControlCenterSettings : _UISettings
{
    BOOL _highlightUsesPlusL;
    BOOL _forceVibrantControls;
    BOOL _useNewBounce;
    SBControlCenterSettingsSectionSettings *_settingsSectionSettings;
    SBControlCenterShortcutSectionSettings *_shortcutSectionSettings;
    float _controlAlpha;
    float _controlAlpha1x;
    float _minControlAlpha;
    float _maxControlAlpha;
    float _disabledAlpha;
    float _disabledAlpha1x;
    float _highlightAlpha;
    float _glowAlpha;
    UIColor *_highlightColor;
    float _oldBounceFriction;
    float _bounceDensityFactor;
    float _bounceResistance;
    float _minVelocity;
    float _maxVelocity;
    float _attachmentThreshold;
    float _attachmentFrequencyAbove;
    float _attachmentFrequencyBelow;
    float _attachmentVelocityDamping;
    float _attachmentMinDamping;
    float _attachmentMaxDamping;
    float _backgroundAlphaFactor;
}

+ (id)settingsControllerModule;
@property float backgroundAlphaFactor; // @synthesize backgroundAlphaFactor=_backgroundAlphaFactor;
@property float attachmentMaxDamping; // @synthesize attachmentMaxDamping=_attachmentMaxDamping;
@property float attachmentMinDamping; // @synthesize attachmentMinDamping=_attachmentMinDamping;
@property float attachmentVelocityDamping; // @synthesize attachmentVelocityDamping=_attachmentVelocityDamping;
@property float attachmentFrequencyBelow; // @synthesize attachmentFrequencyBelow=_attachmentFrequencyBelow;
@property float attachmentFrequencyAbove; // @synthesize attachmentFrequencyAbove=_attachmentFrequencyAbove;
@property float attachmentThreshold; // @synthesize attachmentThreshold=_attachmentThreshold;
@property float maxVelocity; // @synthesize maxVelocity=_maxVelocity;
@property float minVelocity; // @synthesize minVelocity=_minVelocity;
@property float bounceResistance; // @synthesize bounceResistance=_bounceResistance;
@property float bounceDensityFactor; // @synthesize bounceDensityFactor=_bounceDensityFactor;
@property float oldBounceFriction; // @synthesize oldBounceFriction=_oldBounceFriction;
@property BOOL useNewBounce; // @synthesize useNewBounce=_useNewBounce;
@property(retain) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property float glowAlpha; // @synthesize glowAlpha=_glowAlpha;
@property BOOL forceVibrantControls; // @synthesize forceVibrantControls=_forceVibrantControls;
@property BOOL highlightUsesPlusL; // @synthesize highlightUsesPlusL=_highlightUsesPlusL;
@property float highlightAlpha; // @synthesize highlightAlpha=_highlightAlpha;
@property float disabledAlpha1x; // @synthesize disabledAlpha1x=_disabledAlpha1x;
@property float disabledAlpha; // @synthesize disabledAlpha=_disabledAlpha;
@property float maxControlAlpha; // @synthesize maxControlAlpha=_maxControlAlpha;
@property float minControlAlpha; // @synthesize minControlAlpha=_minControlAlpha;
@property float controlAlpha1x; // @synthesize controlAlpha1x=_controlAlpha1x;
@property float controlAlpha; // @synthesize controlAlpha=_controlAlpha;
@property(retain) SBControlCenterShortcutSectionSettings *shortcutSectionSettings; // @synthesize shortcutSectionSettings=_shortcutSectionSettings;
@property(retain) SBControlCenterSettingsSectionSettings *settingsSectionSettings; // @synthesize settingsSectionSettings=_settingsSectionSettings;
- (float)resolvedDisabledAlpha;
- (float)resolvedControlAlpha;
- (void)setDefaultValues;

@end

