//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "SBActivationSettings.h"
#import "SBDeactivationSettings.h"
#import "SBStateSettings.h"

@class SBDisplaySettings, UIStatusBarStyleRequest;

@protocol SBDisplayProtocol <NSObject, SBActivationSettings, SBDeactivationSettings, SBStateSettings>
- (void)clearStateSettings;
- (void)clearDeactivationSettings;
- (void)clearActivationSettings;
- (SBDisplaySettings *)copyDisplaySettings;
- (void)deactivate;
- (void)activate;
- (BOOL)suppressesControlCenter;
- (BOOL)suppressesNotificationCenter;
- (BOOL)suppressesBanners;
- (BOOL)allowsEventOnlySuspension;
- (UIStatusBarStyleRequest *)effectiveStatusBarStyleRequest;
- (UIStatusBarStyleRequest *)statusBarStyleRequest;
- (int)starkStatusBarStyle;
- (int)statusBarStyle;
@end

