//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBRootIconListView.h"

@interface SBDockIconListView : SBRootIconListView
{
}

+ (unsigned int)iconRowsForInterfaceOrientation:(int)arg1;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)arg1;
+ (unsigned int)iconColumnsOrRows;
+ (float)defaultHeight;
- (unsigned int)columnAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)arg1;
- (float)_additionalVerticalInsetToCenterIcons;
- (float)_additionalHorizontalInsetToCenterIcons;
- (unsigned int)rowAtPoint:(struct CGPoint)arg1;
- (id)iconAtPoint:(struct CGPoint)arg1 index:(unsigned int *)arg2 proposedOrder:(int *)arg3 grabbedIcon:(id)arg4;
- (float)sideIconInset;
- (float)bottomIconInset;
- (float)topIconInset;
- (unsigned int)iconsInColumnForSpacingCalculation;
- (unsigned int)iconsInRowForSpacingCalculation;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (int)iconLocation;
- (id)initWithModel:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3;

@end

