//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderView.h"

#import "UIGestureRecognizerDelegate.h"
#import "_UISettingsKeyObserver.h"

@class NSMapTable, NSMutableArray, NSString, SBFloatyFolderBackgroundClipView, SBFolderSettings, UILongPressGestureRecognizer, UIPinchGestureRecognizer, UITapGestureRecognizer;

@interface SBFloatyFolderView : SBFolderView <UIGestureRecognizerDelegate, _UISettingsKeyObserver>
{
    SBFloatyFolderBackgroundClipView *_scrollClipView;
    NSMutableArray *_pageBackgroundViews;
    NSMapTable *_pageBackgroundViewsForIconListViews;
    unsigned int _scalingViewPageIndex;
    UITapGestureRecognizer *_tapGesture;
    UIPinchGestureRecognizer *_pinchGesture;
    UILongPressGestureRecognizer *_longPressGesture;
    SBFolderSettings *_folderSettings;
    struct CGPoint _preReachabilityTitleOrigin;
    struct CGPoint _reachabilityTitleOrigin;
    struct CGPoint _preReachabilityScaleOrigin;
    struct CGPoint _reachabilityScaleOrigin;
    float _reachabilityYOffset;
    BOOL _layingOutForReachability;
    BOOL _displayingMultipleIconLists;
    BOOL _animatingRotation;
}

+ (unsigned int)_countOfAdditionalPagesToKeepVisibleInOneDirection;
+ (Class)_scrollViewClass;
@property(nonatomic, getter=isAnimatingRotation) BOOL animatingRotation; // @synthesize animatingRotation=_animatingRotation;
@property(nonatomic, getter=isDisplayingMultipleIconLists) BOOL displayingMultipleIconLists; // @synthesize displayingMultipleIconLists=_displayingMultipleIconLists;
- (void)_handleReachabilityDectivatedAnimate:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_handleReachabilityActivatedAnimate:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (float)reachabilityYOffset;
- (void)handleReachabilityActivated:(BOOL)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)_tapToCloseGestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_handleLongPressGesture:(id)arg1;
- (void)_handlePinchGesture:(id)arg1;
- (void)_handleOutsideTap:(id)arg1;
- (void)_configureGestures;
- (void)_convertToSingleIconListAnimated:(BOOL)arg1;
- (void)_convertToMultipleIconListsAnimated:(BOOL)arg1;
- (void)fadeContentForMinificationFraction:(float)arg1;
- (void)fadeContentForMagnificationFraction:(float)arg1;
- (void)returnScalingView;
- (id)borrowScalingView;
- (void)didAnimate;
- (void)willAnimate;
- (float)_titleVerticalOffsetForOrientation:(int)arg1;
- (float)_titleFontSize;
- (BOOL)_showsTitle;
- (id)iconListViewAtPoint:(struct CGPoint)arg1;
- (BOOL)locationCountsAsInsideFolder:(struct CGPoint)arg1;
- (float)_offsetToCenterPageControlInSpaceForPageControl;
- (struct CGRect)_frameForScalingView;
- (void)_updateScalingViewLocation;
- (void)_currentPageIndexDidChange;
- (void)_updateIconListContainment:(id)arg1 atIndex:(unsigned int)arg2;
- (struct CGRect)_iconListFrameForPageRect:(struct CGRect)arg1 atIndex:(unsigned int)arg2;
- (struct CGRect)_pageBackgroundFrameForPageRect:(struct CGRect)arg1;
- (void)_layoutSubviews;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)_orientationDidChange:(int)arg1;
- (BOOL)_shouldConvertToMultipleIconListsInLandscapeOrientation;
- (unsigned int)_countOfAdditionalPagesToKeepAnimatingInOneDirection;
- (void)_removeIconListView:(id)arg1;
- (void)_addIconListView:(id)arg1;
- (id)_newPageBackgroundView;
- (void)setLegibilitySettings:(id)arg1;
- (struct CGPoint)visibleFolderRelativeImageCenterForIcon:(id)arg1;
- (void)setBackgroundAlpha:(float)arg1;
- (void)dealloc;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

