//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSString, UIColor, UIFont;

@interface SBIconLabelImageParameters : NSObject <NSCopying, NSMutableCopying>
{
    UIFont *_font;
    NSString *_text;
    BOOL _containsNonLatinLikeCharacters;
    BOOL _containsEmoji;
    BOOL _canEllipsize;
    BOOL _canTighten;
    float _scale;
    struct CGSize _maxSize;
    int _style;
    UIColor *_textColor;
    BOOL _recalculateHash;
    BOOL _canUseMemoryPool;
    BOOL _accessibilityIncreaseContrastEnabled;
    UIColor *_focusHighlightColor;
    struct UIEdgeInsets _textInsets;
    struct UIEdgeInsets _fontLanguageInsets;
    int _iconLocation;
    unsigned int _hash;
}

@property(readonly, nonatomic) int iconLocation; // @synthesize iconLocation=_iconLocation;
@property(readonly, nonatomic) struct UIEdgeInsets fontLanguageInsets; // @synthesize fontLanguageInsets=_fontLanguageInsets;
@property(readonly, nonatomic) struct UIEdgeInsets textInsets; // @synthesize textInsets=_textInsets;
@property(readonly, retain, nonatomic) UIColor *focusHighlightColor; // @synthesize focusHighlightColor=_focusHighlightColor;
@property(readonly, nonatomic) BOOL accessibilityIncreaseContrastEnabled; // @synthesize accessibilityIncreaseContrastEnabled=_accessibilityIncreaseContrastEnabled;
@property(readonly, retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(readonly, nonatomic) int style; // @synthesize style=_style;
@property(readonly, nonatomic) BOOL canUseMemoryPool; // @synthesize canUseMemoryPool=_canUseMemoryPool;
@property(readonly, nonatomic) BOOL containsEmoji; // @synthesize containsEmoji=_containsEmoji;
@property(readonly, nonatomic) BOOL containsNonLatinLikeCharacters; // @synthesize containsNonLatinLikeCharacters=_containsNonLatinLikeCharacters;
@property(readonly, nonatomic) BOOL canTighten; // @synthesize canTighten=_canTighten;
@property(readonly, nonatomic) BOOL canEllipsize; // @synthesize canEllipsize=_canEllipsize;
@property(readonly, nonatomic) float scale; // @synthesize scale=_scale;
@property(readonly, retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(readonly, nonatomic) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)_noteNeedsHashRecalculation;
- (BOOL)colorspaceIsGrayscale;
- (void)dealloc;
- (id)initWithParameters:(id)arg1;
- (id)init;

@end

