//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBReusableViewMap.h"

@interface SBIconLabelAccessoryViewMap : SBReusableViewMap
{
}

+ (struct CGSize)labelAccessoryViewSizeForType:(int)arg1;
+ (id)homescreenMap;
- (id)viewForLabelAccessoryType:(int)arg1;

@end

