//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBBulletin, NSString;

@interface SBLockScreenActionContext : NSObject
{
    NSString *_lockLabel;
    NSString *_shortLockLabel;
    CDUnknownBlockType _action;
    NSString *_identifier;
    float _fontSize;
    BOOL _requiresUIUnlock;
    BOOL _deactivateAwayController;
    BOOL _canBypassPinLock;
    BOOL _requiresAuthentication;
    BBBulletin *_bulletin;
}

@property(nonatomic) BBBulletin *bulletin; // @synthesize bulletin=_bulletin;
@property(nonatomic) BOOL requiresAuthentication; // @synthesize requiresAuthentication=_requiresAuthentication;
@property(nonatomic) BOOL canBypassPinLock; // @synthesize canBypassPinLock=_canBypassPinLock;
@property(nonatomic) BOOL deactivateAwayController; // @synthesize deactivateAwayController=_deactivateAwayController;
@property(nonatomic) BOOL requiresUIUnlock; // @synthesize requiresUIUnlock=_requiresUIUnlock;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(retain, nonatomic) NSString *shortLockLabel; // @synthesize shortLockLabel=_shortLockLabel;
@property(retain, nonatomic) NSString *lockLabel; // @synthesize lockLabel=_lockLabel;
@property(readonly, nonatomic) BOOL hasCustomUnlockLabel;
- (void)dealloc;
- (id)initWithLockLabel:(id)arg1 shortLockLabel:(id)arg2 action:(CDUnknownBlockType)arg3 identifier:(id)arg4;

@end

