//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLockScreenNotificationCell.h"

@interface SBLockScreenBulletinCell : SBLockScreenNotificationCell
{
}

+ (float)paddingBetweenTitleAndRelevanceDate;
+ (float)rowHeightForTitle:(id)arg1 subtitle:(id)arg2 body:(id)arg3 maxLines:(unsigned int)arg4 attachmentSize:(struct CGSize)arg5 secondaryContentSize:(struct CGSize)arg6 datesVisible:(BOOL)arg7 rowWidth:(float)arg8 includeUnlockActionText:(BOOL)arg9;

@end

