//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SBLockScreenActionContext, SBLockScreenSlideUpToAppController, SBLockScreenView, UIView<_SBFVibrantView>, UIViewController;

@protocol SBLockScreenSlideUpToAppControllerDelegate
- (UIViewController *)viewControllerToUseAsParent;
- (void)passcodeViewDidBecomeActive:(BOOL)arg1 forController:(SBLockScreenSlideUpToAppController *)arg2;
- (void)updateSlideToUnlockTextForController:(SBLockScreenSlideUpToAppController *)arg1;
- (void)setUnlockActionContext:(SBLockScreenActionContext *)arg1;
- (BOOL)isAnotherSlideUpControllerBlockingController:(SBLockScreenSlideUpToAppController *)arg1;
- (BOOL)controllerShouldInvertVerticalPadding:(SBLockScreenSlideUpToAppController *)arg1;
- (BOOL)controllerShouldUseAdditionalTopPadding:(SBLockScreenSlideUpToAppController *)arg1;
- (void)adjustWallpaperForVerticalScrollPercentage:(float)arg1;
- (UIView<_SBFVibrantView> *)grabberViewInLockScreenView:(SBLockScreenView *)arg1 forController:(SBLockScreenSlideUpToAppController *)arg2;
- (void)addGrabberView:(UIView<_SBFVibrantView> *)arg1 toLockScreenView:(SBLockScreenView *)arg2 forController:(SBLockScreenSlideUpToAppController *)arg3;
- (int)presentingControllerIdentifierForController:(SBLockScreenSlideUpToAppController *)arg1;
- (void)prepareForSlideUpAppLaunchAnimated:(BOOL)arg1;
@end

