//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconLabelImageParameters.h"

@class NSString, UIColor, UIFont;

@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters
{
}

@property(nonatomic) struct UIEdgeInsets fontLanguageInsets; // @dynamic fontLanguageInsets;
@property(nonatomic) struct UIEdgeInsets textInsets; // @dynamic textInsets;
@property(retain, nonatomic) UIColor *focusHighlightColor; // @dynamic focusHighlightColor;
@property(nonatomic) BOOL accessibilityIncreaseContrastEnabled; // @dynamic accessibilityIncreaseContrastEnabled;
@property(nonatomic) float scale; // @dynamic scale;
@property(retain, nonatomic) UIColor *textColor; // @dynamic textColor;
@property(nonatomic) int style; // @dynamic style;
@property(nonatomic) BOOL canUseMemoryPool;
@property(nonatomic) BOOL containsEmoji; // @dynamic containsEmoji;
@property(nonatomic) BOOL canTighten; // @dynamic canTighten;
@property(nonatomic) BOOL canEllipsize; // @dynamic canEllipsize;
@property(nonatomic) int iconLocation; // @dynamic iconLocation;
@property(nonatomic) BOOL containsNonLatinLikeCharacters; // @dynamic containsNonLatinLikeCharacters;
@property(retain, nonatomic) UIFont *font; // @dynamic font;
@property(nonatomic) struct CGSize maxSize; // @dynamic maxSize;
@property(copy, nonatomic) NSString *text; // @dynamic text;
- (id)copy;

@end

