//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderIcon.h"

@interface SBNewsstandIcon : SBFolderIcon
{
}

- (BOOL)hasFolderIconView;
- (BOOL)isNewsstandIcon;
- (id)getUnmaskedIconImage:(int)arg1;
- (id)generateIconImage:(int)arg1;
- (id)_generateImageUsingMask:(BOOL)arg1;
- (id)_newsstandIconImageName;
- (id)folder;
- (void)launchFromLocation:(int)arg1;
- (id)displayName;

@end

