//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolder.h"

@interface SBNewsstandFolder : SBFolder
{
}

+ (BOOL)isNewsstandFolderClass;
- (id)nodeIdentifier;
- (BOOL)isNewsstandFolder;
- (void)setDisplayName:(id)arg1;
- (BOOL)canAddIcon;
- (BOOL)canEditDisplayName;
- (BOOL)canRemoveIcons;
- (BOOL)shouldRemoveWhenEmpty;
- (Class)listModelClass;
- (void)setIsOpen:(BOOL)arg1;
- (id)icon;
- (id)initWithMaxListCount:(unsigned int)arg1 maxIconCountInLists:(unsigned int)arg2;

@end

