//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

#import "UIAlertViewDelegate.h"

@class NSMutableIndexSet, NSString, SBUserInstalledApplicationIcon;

@interface SBRelatedDataDeletionAlertItem : SBAlertItem <UIAlertViewDelegate>
{
    SBUserInstalledApplicationIcon *_icon;
    NSMutableIndexSet *_relatedDataStores;
    NSMutableIndexSet *_dataStoresToPurge;
    int _deleteButtonIndex;
}

- (BOOL)dismissOnLock;
- (BOOL)shouldShowInLockScreen;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (BOOL)_hasUnconsideredDataStores;
- (unsigned int)_currentDataStoreCandidate;
- (void)setHasGameKitData:(BOOL)arg1;
- (void)setHasHealthKitData:(BOOL)arg1;
- (void)dealloc;
- (id)initWithIcon:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

