//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_UISettings.h"

@interface SBReachabilitySettings : _UISettings
{
    BOOL _allowOnAllDevices;
    unsigned int _triggerMethod;
    unsigned int _numberOfTapsForTapTrigger;
    float _yOffsetFactor;
    float _mass;
    float _stiffness;
    float _damping;
    float _epsilon;
    double _fingerOnMesaRequiredDuration;
    double _tapToTapMaxInterval;
    double _reachabilityDefaultKeepAlive;
    double _reachabilityInteractiveKeepAlive;
    double _reducedMotionSlideDuration;
}

+ (id)settingsControllerModule;
@property(nonatomic) double reducedMotionSlideDuration; // @synthesize reducedMotionSlideDuration=_reducedMotionSlideDuration;
@property(nonatomic) float epsilon; // @synthesize epsilon=_epsilon;
@property(nonatomic) float damping; // @synthesize damping=_damping;
@property(nonatomic) float stiffness; // @synthesize stiffness=_stiffness;
@property(nonatomic) float mass; // @synthesize mass=_mass;
@property(nonatomic) float yOffsetFactor; // @synthesize yOffsetFactor=_yOffsetFactor;
@property(nonatomic) double reachabilityInteractiveKeepAlive; // @synthesize reachabilityInteractiveKeepAlive=_reachabilityInteractiveKeepAlive;
@property(nonatomic) double reachabilityDefaultKeepAlive; // @synthesize reachabilityDefaultKeepAlive=_reachabilityDefaultKeepAlive;
@property(nonatomic) double tapToTapMaxInterval; // @synthesize tapToTapMaxInterval=_tapToTapMaxInterval;
@property(nonatomic) unsigned int numberOfTapsForTapTrigger; // @synthesize numberOfTapsForTapTrigger=_numberOfTapsForTapTrigger;
@property(nonatomic) BOOL allowOnAllDevices; // @synthesize allowOnAllDevices=_allowOnAllDevices;
@property(nonatomic) double fingerOnMesaRequiredDuration; // @synthesize fingerOnMesaRequiredDuration=_fingerOnMesaRequiredDuration;
@property(nonatomic) unsigned int triggerMethod; // @synthesize triggerMethod=_triggerMethod;
- (id)animationFactory;
- (void)setDefaultValues;

@end

