//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderController.h"

@class SBRootFolder, SBRootFolderView, UIWindow;

@interface SBRootFolderController : SBFolderController
{
    BOOL _managesStatusBarWidth;
    UIWindow *_dockAnimationWindow;
}

+ (Class)listViewClass;
@property(nonatomic) BOOL managesStatusBarWidth; // @synthesize managesStatusBarWidth=_managesStatusBarWidth;
@property(retain, nonatomic) UIWindow *dockAnimationWindow; // @synthesize dockAnimationWindow=_dockAnimationWindow;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (struct UIEdgeInsets)statusBarInsetsForOrientation:(int)arg1;
- (void)_configureAppStatusBarInsetsForOrientation:(int)arg1;
- (void)_configureAppStatusBarInsets;
- (void)_configureAppStatusBarInsetsAnimated:(BOOL)arg1;
- (void)_configureDockViewForOrientationWithoutAnimation:(int)arg1;
- (void)_configureDockViewForOrientationDuringAnimation:(int)arg1;
- (BOOL)_dockLayoutReversedForInterfaceOrientation:(int)arg1;
- (unsigned int)_dockEdgeForInterfaceOrientation:(int)arg1;
- (BOOL)_shouldSlideDockOutDuringRotationFromOrientation:(int)arg1 toOrientation:(int)arg2;
- (BOOL)_isDockSwitchedForOrientation:(int)arg1;
- (void)prepareToClose;
- (void)prepareToOpen;
- (void)addAdditionalInnerFolderAnimations;
- (BOOL)popFolderAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (BOOL)pushFolder:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)_listIndexIsVisible:(unsigned int)arg1;
- (struct CGRect)_autoscrollExclusionRegion;
@property(nonatomic) unsigned int dockEdge;
- (void)setDockVerticalStretch:(float)arg1;
- (void)setDockOffscreenFraction:(float)arg1;
- (id)dockListView;
- (BOOL)isDisplayingIcon:(id)arg1;
- (void)setIdleText:(id)arg1;
- (BOOL)setCurrentPageIndex:(int)arg1 animated:(BOOL)arg2;
- (id)folderControllers;
- (unsigned int)_depth;
- (Class)_contentViewClass;
- (void)dealloc;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3;

// Remaining properties
@property(readonly, retain, nonatomic) SBRootFolderView *contentView;
@property(retain, nonatomic) SBRootFolder *folder;

@end

