//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBSetupManager : NSObject
{
    BOOL _inSetupMode;
}

+ (id)sharedInstance;
- (BOOL)_setInSetupMode:(BOOL)arg1;
- (BOOL)setupIsRunningForUpdateInstall;
- (BOOL)setupHasFinishedRestoringFromBackup;
- (BOOL)updateInSetupMode;
@property(readonly, nonatomic, getter=isInSetupMode) BOOL inSetupMode;

@end

