//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBSearchGesture;

@protocol SBSearchGestureObserver <NSObject>
- (void)searchGesture:(SBSearchGesture *)arg1 changedPercentComplete:(float)arg2;

@optional
- (void)searchGesture:(SBSearchGesture *)arg1 completedShowing:(BOOL)arg2;
@end

