//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIBannerItem.h"

@class NSArray, NSDate, NSHashTable, NSMutableSet, NSString, UIImage;

@interface SBStarkBannerItem : SBUIBannerItem
{
    NSHashTable *_observers;
    NSMutableSet *_displayReasons;
}

- (void)_callOrFaceTimeStateChanged;
- (BOOL)_inCallOrFaceTime;
- (BOOL)isStarkBannerItem;
- (BOOL)matchesContext:(id)arg1;
- (void)reloadDisplayProperties;
@property(readonly, copy, nonatomic) NSArray *subActionLabels;
- (CDUnknownBlockType)ignoreAction;
@property(readonly, nonatomic) int effectiveDefaultActionType;
@property(readonly, nonatomic) int defaultActionType;
@property(readonly, retain, nonatomic) NSDate *sourceDate;
@property(readonly, retain, nonatomic) UIImage *categoryImage;
@property(readonly, copy, nonatomic) NSString *message;
@property(readonly, copy, nonatomic) NSString *subTitle;
@property(readonly, copy, nonatomic) NSString *title;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (id)init;

@end

