//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderController.h"

@class NSIndexPath, SBIcon;

@interface SBStarkFolderController : SBFolderController
{
    NSIndexPath *_focusedIndex;
    unsigned int _interactionAffordances;
    BOOL _supportsKnobEvents;
}

- (void)folderView:(id)arg1 currentPageIndexDidChange:(int)arg2;
- (void)_setFocusedIndex:(id)arg1 animated:(BOOL)arg2 scrollToPageIfNecessary:(BOOL)arg3;
- (void)setInnerFolderController:(id)arg1;
@property(nonatomic) unsigned int interactionAffordances;
- (void)focusChangedByAmount:(int)arg1;
- (void)setFocusedIndex:(id)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) NSIndexPath *focusedIndex;
@property(retain, nonatomic) SBIcon *focusedIcon;
- (id)_iconPageIndicatorImageSetCache;
- (Class)_contentViewClass;
- (void)dealloc;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3;

@end

