//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBStarkIconLayoutOverrideStrategy : NSObject
{
    struct UIEdgeInsets _layoutInsets;
    BOOL _preservesCurrentListOrigin;
}

@property(readonly, nonatomic) BOOL preservesCurrentListOrigin; // @synthesize preservesCurrentListOrigin=_preservesCurrentListOrigin;
@property(readonly, nonatomic) struct UIEdgeInsets layoutInsets; // @synthesize layoutInsets=_layoutInsets;
- (id)initWithFullscreenOverrideStrategy:(id)arg1;

@end

