//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBApplicationRestrictionObserver.h"
#import "SBFolderControllerDelegate.h"
#import "SBIconModelDelegate.h"
#import "SBIconViewDelegate.h"
#import "SBIconViewMapDelegate.h"
#import "SBLeafIconDataSource.h"

@class AVExternalDevice, NSIndexPath, NSSet, NSString, SBIcon, SBIconModel, SBIconViewMap, SBStarkFakeIconOperationController, SBStarkFolderController, SBStarkIconLayoutOverrideStrategy, _UILegibilitySettings;

@interface SBStarkIconController : UIViewController <SBIconModelDelegate, SBApplicationRestrictionObserver, SBFolderControllerDelegate, SBIconViewMapDelegate, SBIconViewDelegate, SBLeafIconDataSource>
{
    SBIconModel *_iconModel;
    SBIconViewMap *_iconViewMap;
    SBStarkFolderController *_rootFolderController;
    unsigned int _interactionAffordances;
    AVExternalDevice *_externalDevice;
    _UILegibilitySettings *_legibilitySettings;
    SBIcon *_highlightedIcon;
    SBIcon *_launchingIcon;
    SBIcon *_focusedIconForLayout;
    NSIndexPath *_indexPathToResetTo;
    SBStarkFakeIconOperationController *_fakeIconOperationController;
    SBStarkIconLayoutOverrideStrategy *_iconLayoutOverrideStrategy;
    BOOL _geoSupported;
    NSSet *_visibleTags;
    NSSet *_hiddenTags;
    BOOL _invalidated;
    BOOL _hidden;
}

@property(retain, nonatomic) SBStarkIconLayoutOverrideStrategy *iconLayoutOverrideStrategy; // @synthesize iconLayoutOverrideStrategy=_iconLayoutOverrideStrategy;
@property(retain, nonatomic) SBStarkFakeIconOperationController *fakeIconOperationController; // @synthesize fakeIconOperationController=_fakeIconOperationController;
- (BOOL)iconIsBeta:(id)arg1;
- (BOOL)iconIsRecentlyUpdated:(id)arg1;
- (BOOL)icon:(id)arg1 launchFromLocation:(int)arg2;
- (BOOL)iconAllowsLaunch:(id)arg1;
- (BOOL)iconCompleteUninstall:(id)arg1;
- (BOOL)iconAllowsUninstall:(id)arg1;
- (id)iconFormattedAccessoryString:(id)arg1;
- (id)iconBadgeNumberOrString:(id)arg1;
- (int)iconAccessoryType:(id)arg1;
- (BOOL)iconProgressIsPaused:(id)arg1;
- (float)iconProgressPercent:(id)arg1;
- (int)iconProgressState:(id)arg1;
- (BOOL)iconAppearsInNewsstand:(id)arg1;
- (BOOL)iconCanTightenLabel:(id)arg1;
- (BOOL)iconCanEllipsizeLabel:(id)arg1;
- (id)icon:(id)arg1 defaultImageWithFormat:(int)arg2;
- (id)icon:(id)arg1 imageWithFormat:(int)arg2;
- (unsigned int)iconPriority:(id)arg1;
- (id)iconDisplayName:(id)arg1;
- (BOOL)iconViewDisplaysBadges:(id)arg1;
- (void)iconTapped:(id)arg1;
- (void)_launchIcon:(id)arg1;
- (void)_clearHighlightedIcon;
- (BOOL)iconShouldAllowTap:(id)arg1;
- (void)icon:(id)arg1 touchEnded:(BOOL)arg2;
- (void)icon:(id)arg1 touchMoved:(id)arg2;
- (void)iconTouchBegan:(id)arg1;
- (int)viewMap:(id)arg1 locationForIcon:(id)arg2;
- (id)windowForRecycledViewsInViewMap:(id)arg1;
- (unsigned int)viewMap:(id)arg1 maxRecycledViewsOfClass:(Class)arg2;
- (Class)iconViewClassForIcon:(id)arg1 location:(int)arg2;
- (void)folderControllerDidEndScrolling:(id)arg1;
- (void)folderControllerShouldBeginEditing:(id)arg1;
- (void)folderControllerShouldClose:(id)arg1;
- (void)folderController:(id)arg1 draggedIconShouldDropFromListView:(id)arg2;
- (BOOL)folderController:(id)arg1 draggedIconMightDropFromListView:(id)arg2;
- (BOOL)folderController:(id)arg1 draggedIconDidMoveFromListView:(id)arg2 toListView:(id)arg3;
- (BOOL)folderController:(id)arg1 draggedIconDidPauseAtLocation:(struct CGPoint)arg2 inListView:(id)arg3;
- (Class)controllerClassForFolder:(id)arg1;
- (Class)_controllerClassForFolderClass:(Class)arg1;
- (void)applicationRestrictionController:(id)arg1 didUpdateVisibleTags:(id)arg2 hiddenTags:(id)arg3;
- (id)applicationIconForBundleIdentifier:(id)arg1;
- (id)iconForLeafID:(id)arg1;
- (id)currentFolderController;
- (void)didDeleteIconState:(id)arg1;
- (void)didSaveIconState:(id)arg1;
- (BOOL)canSaveIconState:(id)arg1;
- (BOOL)canAddDownloadingIconForApplication:(id)arg1;
- (BOOL)canAddWebClip:(id)arg1;
- (BOOL)supportsDock;
- (unsigned int)maxColCountForListInRootFolderWithInterfaceOrientation:(int)arg1;
- (unsigned int)maxRowCountForListInRootFolderWithInterfaceOrientation:(int)arg1;
- (unsigned int)maxIconCountForDock;
- (unsigned int)maxIconCountForListInFolderClass:(Class)arg1;
- (unsigned int)maxListCountForFolders;
- (void)_geoSupportChanged;
- (void)_installedAppsDidChange:(id)arg1;
- (void)_iconModelDidLayout:(id)arg1;
- (void)_iconModelWillLayout:(id)arg1;
- (void)_iconModelDidReloadIcons:(id)arg1;
- (void)_iconModelWillReloadIcons:(id)arg1;
- (void)_iconVisibilityChanged:(id)arg1;
- (BOOL)_buttons:(id)arg1 hasType:(int)arg2;
- (void)_physicalButtonsEnded:(id)arg1 withEvent:(id)arg2;
- (void)_physicalButtonsBegan:(id)arg1 withEvent:(id)arg2;
- (void)_moveWithEvent:(id)arg1;
- (void)loadView;
- (void)_resetRootIconLists;
- (void)_prepareToResetRootIconLists;
- (id)iconsView;
- (void)setHidden:(BOOL)arg1 withAnimationFactory:(id)arg2;
- (BOOL)isHidden;
- (void)invalidate;
- (void)relayout;
- (id)rootFolder;
- (void)dealloc;
- (id)initWithInteractionAffordances:(unsigned int)arg1 externalDevice:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

