//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBFolderView.h"

@class SBStarkIconLayoutOverrideStrategy, UIButton;

@interface SBStarkFolderView : SBFolderView
{
    BOOL _buttonUXEnabled;
    UIButton *_scrollLeftButton;
    UIButton *_scrollRightButton;
    struct CGSize _scrollButtonSize;
    SBStarkIconLayoutOverrideStrategy *_iconLayoutOverrideStrategy;
    struct UIEdgeInsets _listViewInsets;
}

- (void)_scrollButtonPressed:(id)arg1;
- (void)_updateScrollButtonStatesForIndex:(int)arg1;
- (void)_evaluateScrollingForListViewsIfNecessary;
- (void)_updatePageControlToIndex:(int)arg1;
- (void)_updateIconListFrames;
- (void)updateIconListViews;
- (void)resetIconListViews;
- (void)_layoutSubviews;
- (float)_offsetToCenterPageControlInSpaceForPageControl;
- (id)_newPageControl;
@property(retain, nonatomic) SBStarkIconLayoutOverrideStrategy *iconLayoutOverrideStrategy;
- (void)setInteractionAffordances:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithFolder:(id)arg1 orientation:(int)arg2 viewMap:(id)arg3;

@end

