//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBAnimationStepper, SBApplication, SBStretchTransformer;

@interface SBSwitchAppGestureView : UIView
{
    int m_orientation;
    SBApplication *m_startingApp;
    SBApplication *m_endingApp;
    SBApplication *m_leftwardApp;
    SBApplication *m_rightwardApp;
    int m_startingViewOrientation;
    int m_leftwardViewOrientation;
    int m_rightwardViewOrientation;
    UIView *m_startingView;
    UIView *m_leftwardView;
    UIView *m_rightwardView;
    float m_pageWidth;
    float m_percentage;
    float m_contentOffset;
    SBStretchTransformer *m_stretchTransformer;
    BOOL m_finishingPaging;
    BOOL m_underflowing;
    BOOL m_overflowing;
    CDUnknownBlockType m_completion;
    SBAnimationStepper *_wallpaperAnimationStepper;
    int _startingWallpaperStyle;
    int _leftwardWallpaperStyle;
    int _rightwardWallpaperStyle;
}

@property(nonatomic) int rightwardWallpaperStyle; // @synthesize rightwardWallpaperStyle=_rightwardWallpaperStyle;
@property(nonatomic) int leftwardWallpaperStyle; // @synthesize leftwardWallpaperStyle=_leftwardWallpaperStyle;
@property(nonatomic) int startingWallpaperStyle; // @synthesize startingWallpaperStyle=_startingWallpaperStyle;
@property(retain, nonatomic) SBAnimationStepper *wallpaperAnimationStepper; // @synthesize wallpaperAnimationStepper=_wallpaperAnimationStepper;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=m_completion;
@property(nonatomic, getter=isOverflowing) BOOL overflowing; // @synthesize overflowing=m_overflowing;
@property(nonatomic, getter=isUnderflowing) BOOL underflowing; // @synthesize underflowing=m_underflowing;
@property(retain, nonatomic) SBStretchTransformer *stretchTransformer; // @synthesize stretchTransformer=m_stretchTransformer;
@property(nonatomic) float contentOffset; // @synthesize contentOffset=m_contentOffset;
@property(nonatomic) float percentage; // @synthesize percentage=m_percentage;
@property(nonatomic) float pageWidth; // @synthesize pageWidth=m_pageWidth;
@property(nonatomic) int rightwardViewOrientation; // @synthesize rightwardViewOrientation=m_rightwardViewOrientation;
@property(nonatomic) int leftwardViewOrientation; // @synthesize leftwardViewOrientation=m_leftwardViewOrientation;
@property(nonatomic) int startingViewOrientation; // @synthesize startingViewOrientation=m_startingViewOrientation;
@property(retain, nonatomic) UIView *rightwardView; // @synthesize rightwardView=m_rightwardView;
@property(retain, nonatomic) UIView *leftwardView; // @synthesize leftwardView=m_leftwardView;
@property(retain, nonatomic) UIView *startingView; // @synthesize startingView=m_startingView;
@property(retain, nonatomic) SBApplication *rightwardApp; // @synthesize rightwardApp=m_rightwardApp;
@property(retain, nonatomic) SBApplication *leftwardApp; // @synthesize leftwardApp=m_leftwardApp;
@property(retain, nonatomic) SBApplication *endingApp; // @synthesize endingApp=m_endingApp;
@property(retain, nonatomic) SBApplication *startingApp; // @synthesize startingApp=m_startingApp;
@property(nonatomic) int orientation; // @synthesize orientation=m_orientation;
@property(readonly, nonatomic, getter=isPagingRightward) BOOL pagingRightward;
@property(readonly, nonatomic, getter=isPagingLeftward) BOOL pagingLeftward;
- (BOOL)isPagingOverflowPercentage:(float)arg1;
- (BOOL)isPagingUnderflowPercentage:(float)arg1;
- (void)cleanUpWallpaperAnimation;
- (void)stretchTransformerAnimationDidStop:(BOOL)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)moveToContentOffset:(float)arg1 percentage:(float)arg2 animated:(BOOL)arg3;
- (void)moveToApp:(id)arg1 animated:(BOOL)arg2;
- (void)moveToApp:(id)arg1;
- (float)opacityForPercentage:(float)arg1;
- (float)scaleForPercentage:(float)arg1;
- (float)percentageForApp:(id)arg1;
- (float)contentOffsetForApp:(id)arg1;
- (void)finishBackwardToStartWithCompletion:(CDUnknownBlockType)arg1;
- (void)finishForwardToEndWithPercentage:(float)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updatePaging:(float)arg1;
- (void)beginPaging;
- (id)viewForApp:(id)arg1;
- (void)transformGestureViewContainer:(id)arg1;
- (void)dealloc;
- (id)initWithInterfaceOrientation:(int)arg1 startingApp:(id)arg2 leftwardApp:(id)arg3 rightwardApp:(id)arg4;

@end

