//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBWorkspaceTransaction.h"

#import "FBApplicationUpdateScenesTransactionObserver.h"
#import "FBSynchronizedTransactionDelegate.h"

@class FBUIApplicationResignActiveAssertion, NSArray, NSMutableArray, NSMutableDictionary, NSSet, NSString, SBDisplayLayout, SBSceneBackgroundedStatusAssertion;

@interface SBToAppsWorkspaceTransaction : SBWorkspaceTransaction <FBApplicationUpdateScenesTransactionObserver, FBSynchronizedTransactionDelegate>
{
    NSArray *_toApplications;
    NSSet *_scenesToBackground;
    NSSet *_fromApplicationScenes;
    SBDisplayLayout *_toDisplayLayout;
    BOOL _fromAssistant;
    BOOL _fromSwitcher;
    BOOL _toSpringBoard;
    BOOL _underLockScreenInForeground;
    CDUnknownBlockType _resultBlock;
    SBSceneBackgroundedStatusAssertion *_scenesBackgroundedStatusAssertion;
    NSMutableDictionary *_sceneIDsToApps;
    FBUIApplicationResignActiveAssertion *_resignActiveAssertion;
    NSMutableArray *_appsActivatingForeground;
    NSSet *_trackedProcesses;
}

@property(readonly, retain, nonatomic) NSSet *trackedProcesses; // @synthesize trackedProcesses=_trackedProcesses;
@property(readonly, retain, nonatomic) NSArray *toApplications; // @synthesize toApplications=_toApplications;
- (void)_captureApplicationData;
- (void)_fireAndClearResultBlockIfNecessaryForFailure:(BOOL)arg1;
- (void)transaction:(id)arg1 didCommitSceneUpdate:(id)arg2;
- (void)transaction:(id)arg1 willCommitSceneUpdate:(id)arg2;
- (BOOL)shouldWatchdog:(id *)arg1;
- (double)watchdogTimeout;
- (void)synchronizedTransaction:(id)arg1 didCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransaction:(id)arg1 willCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransactionReadyToCommit:(id)arg1;
- (id)_customizedDescriptionProperties;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)_didInterruptWithReason:(id)arg1;
- (void)_didComplete;
- (void)_begin;
- (void)_willBegin;
- (void)_synchronizeSceneUpdatesNowForScenes:(id)arg1;
- (void)_beginAnimation;
- (void)_setupAnimation;
- (void)_synchronizeWithSceneUpdates;
- (void)_handleApplicationUpdateScenesTransactionFailed:(id)arg1;
- (void)_relinquishResignActiveAssertion;
- (void)_handleApplicationDidNotChange:(id)arg1;
- (id)_scenesToBackground;
- (id)_applicationForScene:(id)arg1;
- (void)activateApplications;
- (void)enumerateForegroundToApplicationsWithBlock:(CDUnknownBlockType)arg1;
- (void)enumerateToApplicationsWithBlock:(CDUnknownBlockType)arg1;
- (void)toggleStatusBarForCleanup;
- (BOOL)isGoingToLauncher;
- (void)performToAppStateCleanup;
- (BOOL)shouldAnimateOrientationChangeOnCompletion;
- (BOOL)shouldDismissSwitcher;
- (BOOL)shouldPlaceOutgoingScenesUnderLockOnCompletion;
- (BOOL)shouldRestoreSpringBoardContentOnCleanup;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
- (BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
- (BOOL)shouldHideSpringBoardStatusBarOnCleanup;
- (void)dealloc;
- (id)initWithAlertManager:(id)arg1 activationRequest:(id)arg2 withResult:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

