//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertViewAdapter.h"

@interface SBUIFullscreenAlertViewAdapter : SBAlertViewAdapter
{
    BOOL _revealedContentBeneathForDismiss;
    BOOL _animatingOut;
}

- (void)setAlert:(id)arg1;
- (void)setShouldAnimateIn:(BOOL)arg1;
- (void)dismiss;
- (void)updateSpringBoardInPreparationForTransparentDismiss;
- (void)viewAnimatedOut;
- (BOOL)isAnimatingOut;
- (BOOL)shouldAnimateIconsIn;
- (void)alertDisplayWillBecomeVisible;
- (BOOL)isReadyToBeRemovedFromView;
- (id)alert;

@end

