//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class SBAlert, SBDisableAppStatusBarAlphaChangesAssertion, SBWindow, UIView, UIView<FBWindowContextAppearance>;

@interface SBUIAnimationFadeAlertToHostedApp : SBUIMainScreenAnimationController
{
    SBWindow *_transitionWindow;
    SBAlert *_deactivatingAlert;
    UIView<FBWindowContextAppearance> *_viewToAnimate;
    BOOL _reallyFinishedAnimating;
    SBDisableAppStatusBarAlphaChangesAssertion *_disableStatusBarAlphaChangeAssertion;
    int _launchingOrientation;
    UIView *_fakeStatusBarViewContainer;
    BOOL _appIsTranslucent;
}

@property(retain, nonatomic, getter=_viewToAnimate, setter=_setViewToAnimate:) UIView *viewToAnimate; // @synthesize viewToAnimate=_viewToAnimate;
- (void)_removeFakeStatusBarIfNecessary;
- (void)_showFakeStatusBarIfNecessary;
- (void)_setupFakeStatusBarIfNecessary;
- (void)_maybeReportAnimationFinished;
- (BOOL)_isApplicationLaunchFinished;
- (void)_applicationDependencyStateChanged;
- (void)_noteAnimationDidFinish;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)_animationProgressDependency;
- (BOOL)_waitsForApplicationActivationIfNecessary;
- (void)_setHidden:(BOOL)arg1;
- (id)_getTransitionWindow;
- (void)_reallyFinishedAnimating;
- (BOOL)_shouldAnimateWallpaper;
- (id)_deactivatingAlert;
- (void)dealloc;
- (id)initWithAlert:(id)arg1 activatingApp:(id)arg2;

@end

