//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSURL, SBWidgetViewController;

@protocol SBWidgetViewControllerDelegate <NSObject>

@optional
- (int)activeLayoutModeForWidget:(SBWidgetViewController *)arg1;
- (BOOL)widgetShouldAttemptReconnectionAfterUnanticipatedDisconnection:(SBWidgetViewController *)arg1;
- (BOOL)shouldRequestWidgetRemoteViewControllers;
- (void)contentAvailabilityDidChangeForWidget:(SBWidgetViewController *)arg1;
- (void (^)(void))widget:(SBWidgetViewController *)arg1 didUpdatePreferredHeight:(float)arg2 completion:(void (^)(BOOL))arg3;
- (void)widget:(SBWidgetViewController *)arg1 requestsLaunchOfURL:(NSURL *)arg2;
- (void)widget:(SBWidgetViewController *)arg1 requestsPresentationOfViewController:(NSString *)arg2 presentationStyle:(int)arg3 context:(NSDictionary *)arg4 completion:(void (^)(void))arg5;
- (void)remoteViewControllerDidConnectForWidget:(SBWidgetViewController *)arg1;
@end

