//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BBSectionInfo, BBSettingsGateway, NSMutableArray, NSString, SBWidgetsSettingsTableViewController;

@interface SBWidgetsSettingsViewController : UINavigationController <UITableViewDelegate, UITableViewDataSource>
{
    SBWidgetsSettingsTableViewController *_tableViewController;
    BBSettingsGateway *_bbSettings;
    NSMutableArray *_chronologicalSections;
    NSMutableArray *_enabledWidgets;
    NSMutableArray *_disabledWidgets;
    BBSectionInfo *_todaySection;
    BBSectionInfo *_tomorrowSection;
    BBSectionInfo *_coreRoutineSection;
    BOOL _coreRoutineIsAvailable;
}

- (BOOL)_updateCoreRoutineAvailability;
- (BOOL)_isFixedSnippetsSection:(id)arg1;
- (int)_indexOfFirstEnabledWidget;
- (int)_indexOfLastEnabledWidget;
- (unsigned int)_indexForInsertingSection:(id)arg1 intoArray:(id)arg2;
- (id)_sectionInfoForIndexPath:(id)arg1;
- (id)_sectionInfoArrayForIndexPath:(id)arg1;
- (void)_disableWidgetAtIndexPath:(id)arg1 inTableView:(id)arg2;
- (void)_enableWidgetAtIndexPath:(id)arg1 inTableView:(id)arg2;
- (BOOL)_setSectionInfo:(id)arg1 enabled:(BOOL)arg2;
- (void)_saveWidgetsState;
- (void)_saveWidgetsSections;
- (void)_loadWidgetsSections;
- (id)_newBackgroundView;
- (void)_dismissWidgetsSettings;
- (BOOL)tableView:(id)arg1 shouldDrawTopSeparatorForSection:(int)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndReorderingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

