//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSHashTable, NSMutableDictionary, NSMutableOrderedSet;

@interface SBAppStatusBarManager : NSObject
{
    NSHashTable *_disableAlphaChangeAssertions;
    NSMutableOrderedSet *_windowLevelOverrideReasons;
    NSMutableDictionary *_windowLevelOverrideMap;
    double _defaultWindowLevel;
}

+ (id)sharedInstance;
- (void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_addDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_updateWindowLevel;
- (void)removeWindowLevelOverrideReason:(id)arg1;
- (void)setWindowLevel:(double)arg1 forOverrideReason:(id)arg2;
- (void)setDefaultWindowLevel:(double)arg1;
- (void)setStatusBarAlpha:(double)arg1;
- (void)hideStatusBar;
- (void)showStatusBar;
- (_Bool)isStatusBarHidden;
- (void)dealloc;
- (id)init;

@end

