//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SBFakeStatusBarViewCache : NSObject
{
    NSMutableDictionary *_cachedStatusBarQueues;
}

- (void)dealloc;
- (id)barForKey:(id)arg1 withGenerationBlockIfNecessary:(CDUnknownBlockType)arg2;
- (void)recycleBar:(id)arg1 forKey:(id)arg2;
- (id)init;

@end

