//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconLabelImageParameters.h"

@class NSString, UIFont;

@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters
{
}

@property(nonatomic) long long style; // @dynamic style;
@property(nonatomic) _Bool containsEmoji; // @dynamic containsEmoji;
@property(nonatomic) _Bool canEllipsize; // @dynamic canEllipsize;
@property(nonatomic) _Bool containsNonLatinLikeCharacters; // @dynamic containsNonLatinLikeCharacters;
@property(retain, nonatomic) UIFont *font; // @dynamic font;
@property(nonatomic) struct CGSize maxSize; // @dynamic maxSize;
@property(copy, nonatomic) NSString *text; // @dynamic text;
- (id)copy;

@end

