//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBBBulletinInfo.h"

@class UIImage;

@interface SBSnippetBulletinInfo : SBBBBulletinInfo
{
    double _viewHeight;
    struct CGRect _textRect;
    struct CGSize _referenceSize;
    UIImage *_icon;
}

@property(retain, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (void)populateReusableView:(id)arg1;
- (double)heightForReusableViewInTableView:(id)arg1;
- (_Bool)_isLayoutValidWithReferenceSize:(struct CGSize)arg1;
- (id)_representedBulletin;
- (void)invalidateCachedLayoutData;
- (Class)reusableViewClass;
- (id)identifier;
- (void)dealloc;

@end

