//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SBStarkBackgroundProvider;

@protocol SBStarkBackgroundProviderManagerObserver
- (void)removedBackgroundProvider:(SBStarkBackgroundProvider *)arg1;
- (void)addedBackgroundProvider:(SBStarkBackgroundProvider *)arg1;
@end

