//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBStarkBackgroundProvidersViewController;

@protocol SBStarkBackgroundProvidersViewControllerDelegate <NSObject>
- (void)starkBackgroundProvidersViewControllerWillAnimateInInitially:(SBStarkBackgroundProvidersViewController *)arg1;
- (void)starkBackgroundProvidersViewController:(SBStarkBackgroundProvidersViewController *)arg1 didStartWithAnimation:(_Bool)arg2;
- (void)starkBackgroundProvidersViewController:(SBStarkBackgroundProvidersViewController *)arg1 willStartWithAnimation:(_Bool)arg2;
@end

