//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLeafIcon.h"

@interface SBStarkNowPlayingIcon : SBLeafIcon
{
}

- (void)_nowPlayingInfoChanged:(id)arg1;
- (id)generateIconImage:(int)arg1;
- (void)drawNowPlayingKnobIconInBounds:(struct CGRect)arg1 withArtwork:(id)arg2;
- (void)drawNowPlayingCanvasIconInBounds:(struct CGRect)arg1 withArtwork:(id)arg2;
- (void)dealloc;
- (id)initWithLeafIdentifier:(id)arg1 applicationBundleID:(id)arg2;

@end

