/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIAnimation.h"


@interface _UIOldSliderAnimation : UIAnimation {
	CGFloat _startValue;
	CGFloat _endValue;
	BOOL _sendAction;
}
-(void)setProgress:(CGFloat)progress;
@end

