/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIImageAndTextTableCell.h"


@interface UIDateTableCell : UIImageAndTextTableCell {
	CGFloat _horizontalOffset;
	CGFloat _verticalOffset;
}
-(id)initWithFrame:(CGRect)frame;
-(void)setHorizontalOffset:(CGFloat)offset;
-(void)setVerticalOffset:(CGFloat)offset;
-(CGRect)contentBounds;
-(id)shadowColor;
@end

