/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import <UIKit/UIColor.h>

__attribute__((visibility("hidden")))
@interface UIDeviceRGBColor : UIColor {
	CGFloat redComponent;
	CGFloat greenComponent;
	CGFloat blueComponent;
	CGFloat alphaComponent;
	CGColorRef cachedColor;
}
// inherited: -(id)initWithHue:(CGFloat)hue saturation:(CGFloat)saturation brightness:(CGFloat)brightness alpha:(CGFloat)alpha;
// inherited: -(id)initWithRed:(CGFloat)red green:(CGFloat)green blue:(CGFloat)blue alpha:(CGFloat)alpha;
// inherited: -(id)initWithCGColor:(CGColorRef)cgcolor;
// inherited: -(void)dealloc;
// inherited: -(id)colorWithAlphaComponent:(CGFloat)alphaComponent;
-(CGColorRef)_createCGColorWithAlpha:(CGFloat)alpha;
// inherited: -(void)set;
// inherited: -(void)setFill;
// inherited: -(void)setStroke;
-(id)colorSpaceName;
// inherited: -(id)description;
// inherited: -(BOOL)isEqual:(id)equal;
// inherited: -(unsigned)hash;
// inherited: -(CGColorRef)CGColor;
// inherited (since 3.2): -(CGFloat)alphaComponent;
@end

