/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import "UIKit-Structs.h"


@interface UIFloatArray : NSObject {
	int _count;
	int _gapCount;
	int* _gaps;
	CGFloat _gapValue;
	CGFloat _minValue;
	union {
		CGFloat singleton;
		CGFloat* array;
	} _values;
	struct {
		unsigned valueIsSingleton : 1;
		unsigned hideGaps : 1;
		unsigned unused : 30;
	} _CGFloatArrayFlags;
}
-(BOOL)_setupValuesWithCount:(int)count singleValue:(CGFloat)value isRefresh:(BOOL)refresh;
-(BOOL)_setupValuesWithCount:(int)count dataProvider:(id)provider isRefresh:(BOOL)refresh;
-(BOOL)_setupGapIndexesWithCount:(int)count dataProvider:(id)provider isRefresh:(BOOL)refresh;
-(BOOL)_setupWithDataProvider:(id)dataProvider valueIsSingleton:(BOOL)singleton singletonValue:(CGFloat)value isRefresh:(BOOL)refresh;
-(id)init;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(BOOL)refreshWithDataProvider:(id)dataProvider singleValue:(CGFloat)value;
-(BOOL)refreshWithDataProvider:(id)dataProvider;
-(CGFloat)singleValue;
-(CGFloat)minValue;
-(int)valueCount;
-(CGFloat)sum;
-(CGPoint)offsetsForIndex:(int)index;
-(CGPoint)offsetsForGapIndex:(int)gapIndex;
-(XXStruct_7U_TLD)_indexesViaSingletonFromOffset:(CGFloat)offset toOffset:(CGFloat)offset2;
-(XXStruct_7U_TLD)_indexesViaArrayFromOffset:(CGFloat)offset toOffset:(CGFloat)offset2;
-(XXStruct_7U_TLD)indexesFromOffset:(CGFloat)offset toOffset:(CGFloat)offset2;
-(int)indexForGapIndex:(int)gapIndex;
-(void)hideGaps:(BOOL)gaps;
@end

