/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>
#import <GraphicsServices/GSFont.h>
#import <Availability2.h>

@class NSString;

@interface UIFont ()
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2
+(id)__newDummy;
#else
+(id)__dummy;
#endif
+(UIFont*)fontWithFamilyName:(NSString*)familyName traits:(GSFontTraitMask)traits size:(CGFloat)fontSize;
+(UIFont*)fontWithMarkupDescription:(NSString*)markupDescription;
+(CGFloat)labelFontSize;
+(CGFloat)buttonFontSize;
+(CGFloat)smallSystemFontSize;
+(CGFloat)systemFontSize;
-(id)initWithName:(id)name size:(CGFloat)size;
-(id)initWithFamilyName:(id)familyName traits:(int)traits size:(CGFloat)size;
-(id)initWithMarkupDescription:(id)markupDescription;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(Class)classForCoder;
-(GSFontTraitMask)traits;
-(BOOL)isFixedPitch;
-(NSString*)markupDescription;
@end

