/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import "UIKit-Structs.h"
#import "UIAnimation.h"


@interface UIPickerScrollAnimation : UIAnimation {
	CGFloat _initialDuration;
	CGPoint _originalOffset;
	CGPoint _targetOffset;
}
-(CGPoint)targetOffset;
-(void)setTargetOffset:(CGPoint)offset;
-(void)setOriginalOffset:(CGPoint)offset;
-(void)setProgress:(CGFloat)progress;
-(CGFloat)initialDuration;
-(void)setInitialDuration:(CGFloat)duration;
@end

