/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Availability2.h>

#if __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_3_2

#include_next <UIKit/UIPinchGestureRecognizer.h>

@interface UIPinchGestureRecognizer ()

#else

#import "UIKit-Structs.h"
#import "UIGestureRecognizer.h"

@interface UIPinchGestureRecognizer : UIGestureRecognizer {
	CGFloat _lastTouchDistance;
	double _lastTouchTime;
	CGFloat _velocity;
	CGFloat _previousVelocity;
	CGFloat _scaleThreshold;
	CGAffineTransform _transform;
	CGPoint _anchorPoint;
	unsigned _scrollViewGesture : 1;
}
@property(readonly, assign, nonatomic) CGFloat velocity;
@property(readonly, assign, nonatomic) CGFloat scale;
#endif
@property(readonly, assign, nonatomic) CGAffineTransform transform;
@property(assign, nonatomic) CGFloat scaleThreshold;
@property(assign, nonatomic, getter=isScrollViewGesture) BOOL scrollViewGesture;
@property(readonly, assign, nonatomic) CGPoint anchorPoint;
// inherited: -(id)initWithTarget:(id)target action:(SEL)action;
// inherited: -(void)reset;
-(CGFloat)_distanceBetweenTouches:(id)touches;
// inherited: -(void)touchesBegan:(id)began withEvent:(id)event;
// inherited: -(void)touchesMoved:(id)moved withEvent:(id)event;
// inherited: -(void)touchesEnded:(id)ended withEvent:(id)event;
// inherited: -(void)touchesCancelled:(id)cancelled withEvent:(id)event;
// inherited: -(BOOL)_shouldSaveGestureFromExclusion:(id)exclusion;
@end
