/**
 * This header is generated by class-dump-z 0.1-11o.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface UITableColumn : NSObject {
	NSString* _identifier;
	NSString* _title;
	CGFloat _width;
}
-(id)initWithTitle:(id)title identifier:(id)identifier width:(CGFloat)width;
-(void)dealloc;
-(id)title;
-(void)setTitle:(id)title;
-(void)setIdentifier:(id)identifier;
-(id)identifier;
-(CGFloat)width;
-(void)setWidth:(CGFloat)width;
@end

