/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <UIKit/UIPinchGestureRecognizer.h>

@interface _PUZoomRotateGestureRecognizer : UIPinchGestureRecognizer {

	CGFloat _rotation;
	CGFloat _originalAngle;
	BOOL _hasT1;
	BOOL _hasT2;
	CGPoint _previousT1;
	CGPoint _previousT2;

}

@property (nonatomic,readonly) CGFloat rotation;              //@synthesize rotation=_rotation - In the implementation block
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(CGFloat)rotation;
@end

