/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:06 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	double field1;
	double field2;
} SCD_Struct_PU8;

typedef struct {
	double latitude;
	double longitude;
} SCD_Struct_PU9;

typedef struct PUGridCoordinates {
	int row;
	int column;
} PUGridCoordinates;

typedef struct {
	SCD_Struct_PU9 center;
	SCD_Struct_PU9 span;
} SCD_Struct_PU11;

typedef struct {
	int index;
	CGSize imageSize;
	CGSize minimumSize;
	BOOL hasCaption;
	BOOL isBatchStart;
} SCD_Struct_PU14;

typedef struct {
	int field1;
	CGSize field2;
	CGSize field3;
	BOOL field4;
	BOOL field5;
} SCD_Struct_PU15;

