/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <PhotosUI/PhotosUI-Structs.h>
@interface PUAbstractTransition : NSObject {

	double _progress;
	CGPoint _center;

}

@property (assign,nonatomic) double progress;              //@synthesize progress=_progress - In the implementation block
@property (assign,nonatomic) CGPoint center;               //@synthesize center=_center - In the implementation block
-(CGPoint)center;
-(void)setCenter:(CGPoint)arg1 ;
-(void)setProgress:(double)arg1 ;
-(double)progress;
@end

