/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:06 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PUAbstractNavigationBannerDelegate;
@class UIView;

@interface PUAbstractNavigationBanner : NSObject {

	<PUAbstractNavigationBannerDelegate>* _delegate;

}

@property (assign,nonatomic,__weak) <PUAbstractNavigationBannerDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) CGFloat height; 
@property (nonatomic,readonly) UIView * view; 
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(id)view;
-(CGFloat)height;
-(void).cxx_destruct;
@end

