/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIActionSheet.h>
#import <UIKit/UIActionSheetDelegate.h>

@interface PUActionSheet : UIActionSheet <UIActionSheetDelegate> {

	/*^block*/ id _completionHandler;

}

@property (nonatomic,copy) id completionHandler;              //@synthesize completionHandler=_completionHandler - In the implementation block
-(void)setDelegate:(id)arg1 ;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(/*^block*/ id)completionHandler;
-(void)setCompletionHandler:(/*^block*/ id)arg1 ;
-(id)initWithTitle:(id)arg1 cancelButtonTitle:(id)arg2 destructiveButtonTitle:(id)arg3 otherButtonTitles:(id)arg4 ;
-(void)showFromObject:(id)arg1 animated:(BOOL)arg2 withCompletionHandler:(/*^block*/ id)arg3 ;
-(void)_tearDown;
-(void)showFromViewController:(id)arg1 withCompletionHandler:(/*^block*/ id)arg2 ;
-(void).cxx_destruct;
@end

