/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableOrderedSet, PUActivityViewController, NSOrderedSet;

@interface PUActivityItemSourceController : NSObject {

	NSMutableOrderedSet* _assets;
	NSMutableOrderedSet* _assetItemSources;
	PUActivityViewController* _activityViewController;

}

@property (assign,nonatomic,__weak) PUActivityViewController * activityViewController;              //@synthesize activityViewController=_activityViewController - In the implementation block
@property (nonatomic,copy) NSOrderedSet * assets;                                                   //@synthesize assets=_assets - In the implementation block
@property (nonatomic,readonly) NSOrderedSet * assetItemSources; 
-(id)activityViewController;
-(void)setActivityViewController:(id)arg1 ;
-(id)assets;
-(void)setAssets:(id)arg1 ;
-(id)assetItemSources;
-(int)countOfAssetType:(short)arg1 ;
-(void)addAsset:(id)arg1 ;
-(void)removeAsset:(id)arg1 ;
-(void).cxx_destruct;
@end

