/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:03 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <UIKit/UIView.h>

@class UIView, UIColor;

@interface PUAlbumListSeparatorView : UIView {

	UIView* _separatorLine;
	UIColor* _lineColor;

}

@property (nonatomic,copy) UIColor * lineColor;              //@synthesize lineColor=_lineColor - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setLineColor:(id)arg1 ;
-(id)lineColor;
-(void).cxx_destruct;
@end

