/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:03 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@protocol PUAlbumListTableViewCellDelegate;
@interface PUAlbumListTableViewCell : UITableViewCell {

	<PUAlbumListTableViewCellDelegate>* _stateChangeDelegate;

}

@property (assign,nonatomic,__weak) <PUAlbumListTableViewCellDelegate> * stateChangeDelegate;              //@synthesize stateChangeDelegate=_stateChangeDelegate - In the implementation block
-(void)willTransitionToState:(unsigned)arg1 ;
-(void)setStateChangeDelegate:(id)arg1 ;
-(id)stateChangeDelegate;
-(void).cxx_destruct;
@end

