/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <PhotosUI/PUAlbumListViewControllerSpec.h>

@interface PUAlbumListViewControllerPhoneSpec : PUAlbumListViewControllerSpec
-(CGSize)stackSize;
-(CGFloat)sectionHeaderHeight;
-(CGFloat)sectionFooterHeight;
-(CGSize)photoSize;
-(CGSize)cellSizeForBounds:(CGRect)arg1 ;
-(id)photosPickerViewControllerSpec;
-(id)_nameOfEmptySharedAlbumPlaceholderImage;
-(id)_nameOfAddSharedAlbumPlaceholderImage;
-(int)fastImageFormat;
-(int)qualityImageFormat;
-(unsigned)stackViewStyle;
-(id)stackPhotoDecoration;
-(id)emptyStackPhotoDecoration;
-(UIOffset)stackOffset;
-(UIEdgeInsets)stackPerspectiveInsets;
-(UIOffset)stackPerspectiveOffset;
-(BOOL)allowsAlbumCountSubtitle;
-(int)albumDeletionConfirmationStyle;
-(id)gridViewControllerSpec;
-(id)panoramaViewControllerSpec;
-(id)feedViewControllerSpec;
@end

