/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface PUCloudSharedBackdropView : UIView {

	UIView* _backdropView;
	BOOL _isMask;
	BOOL _hasRoundedCorners;

}

@property (assign,nonatomic) BOOL hasRoundedCorners;              //@synthesize hasRoundedCorners=_hasRoundedCorners - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)arg1 asMask:(BOOL)arg2 ;
-(void)setHasRoundedCorners:(BOOL)arg1 ;
-(BOOL)hasRoundedCorners;
-(void).cxx_destruct;
@end

