/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PUCollectionViewLayoutDelegating <NSObject>
@property (assign,nonatomic,__weak) <PUCollectionViewLayoutTransitioningDelegate> * transitioningDelegate; 
@required
-(id)transitioningDelegate;
-(void)setTransitioningDelegate:(id)arg1;
@end

