/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotoLibraryServices/PLAssetContainerList.h>

@class NSOrderedSet;

@interface PUFeedAssetContainerList : NSObject <PLAssetContainerList> {

	NSOrderedSet* _sectionInfos;

}

@property (nonatomic,retain) NSOrderedSet * sectionInfos;              //@synthesize sectionInfos=_sectionInfos - In the implementation block
@property (nonatomic,readonly) unsigned containersCount; 
-(BOOL)isEmpty;
-(id)managedObjectContext;
-(id)photoLibrary;
-(id)containers;
-(BOOL)canEditContainers;
-(id)containersRelationshipName;
-(unsigned)containersCount;
-(void)setSectionInfos:(id)arg1 ;
-(id)sectionInfos;
-(void).cxx_destruct;
@end

