/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:03 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PUValueFilter.h>

@class NSArray;

@interface PUGroupValueFilter : PUValueFilter {

	NSArray* _filters;

}

@property (nonatomic,copy) NSArray * filters;              //@synthesize filters=_filters - In the implementation block
-(void)setFilters:(id)arg1 ;
-(id)filters;
-(void)setInputValue:(double)arg1 ;
-(double)outputValue;
-(void).cxx_destruct;
@end

