/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PUGridLayoutProtocol <NSObject,PUCollectionViewLayoutDelegating>
@property (nonatomic,readonly) NSIndexPath * globalFooterIndexPath; 
@property (assign,nonatomic) float globalFooterHeight; 
@property (assign,nonatomic) float globalTopPadding; 
@property (assign,nonatomic) float globalBottomPadding; 
@property (nonatomic,copy) NSSet * hiddenItemIndexPaths; 
@property (nonatomic,copy) NSString * sectionHeaderElementKind; 
@property (assign,nonatomic) float sectionHeaderHeight; 
@property (assign,nonatomic) float sectionTopPadding; 
@required
-(void)setSectionHeaderHeight:(float)arg1;
-(float)sectionHeaderHeight;
-(id)sectionHeaderElementKind;
-(void)invalidateLayoutForVerticalScroll;
-(id)assetIndexPathsForElementsInRect:(CGRect)arg1;
-(float)globalFooterHeight;
-(void)setGlobalFooterHeight:(float)arg1;
-(id)globalFooterIndexPath;
-(float)globalTopPadding;
-(void)setGlobalTopPadding:(float)arg1;
-(float)globalBottomPadding;
-(void)setGlobalBottomPadding:(float)arg1;
-(id)hiddenItemIndexPaths;
-(void)setHiddenItemIndexPaths:(id)arg1;
-(void)setSectionHeaderElementKind:(id)arg1;
-(float)sectionTopPadding;
-(void)setSectionTopPadding:(float)arg1;
@end

