/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <UIKit/UICollectionViewLayout.h>

@protocol PUHorizontalTiledCollectionViewLayoutDelegate;
@class PUCollectionViewData;

@interface PUHorizontalTiledCollectionViewLayout : UICollectionViewLayout {

	PUCollectionViewData* _data;
	CGFloat _interitemSpacing;
	<PUHorizontalTiledCollectionViewLayoutDelegate>* _delegate;
	UIEdgeInsets _itemsContentInset;

}

@property (assign,nonatomic) CGFloat interitemSpacing;                                                         //@synthesize interitemSpacing=_interitemSpacing - In the implementation block
@property (assign,nonatomic) UIEdgeInsets itemsContentInset;                                                 //@synthesize itemsContentInset=_itemsContentInset - In the implementation block
@property (assign,nonatomic,__weak) <PUHorizontalTiledCollectionViewLayoutDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) BOOL hasReferenceIndexPath; 
+(Class)invalidationContextClass;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)delegate;
-(CGSize)collectionViewContentSize;
-(id)layoutAttributesForItemAtIndexPath:(id)arg1 ;
-(void)prepareLayout;
-(id)layoutAttributesForElementsInRect:(CGRect)arg1 ;
-(BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1 ;
-(id)invalidationContextForBoundsChange:(CGRect)arg1 ;
-(void)invalidateLayoutWithContext:(id)arg1 ;
-(void)setInteritemSpacing:(CGFloat)arg1 ;
-(UIEdgeInsets)itemsContentInset;
-(BOOL)hasReferenceIndexPath;
-(void)setItemsContentInset:(UIEdgeInsets)arg1 ;
-(void)invalidateCachedLayout;
-(CGFloat)interitemSpacing;
-(BOOL)_shouldInvalidateCachedLayoutForBoundsChange:(CGRect)arg1 ;
-(id)_layoutAttributesForItemAtIndexPath:(id)arg1 ;
-(id)_next:(int)arg1 indexPathsFollowingIndexPath:(id)arg2 direction:(int)arg3 ;
-(BOOL)_updateLayoutData:(id)arg1 inDirection:(int)arg2 outDeltaOriginX:(CGFloat*)arg3 ;
-(void)_ensureRect:(CGRect)arg1 inData:(id)arg2 outDeltaOriginX:(CGFloat*)arg3 ;
-(void)_ensureIndexPath:(id)arg1 inData:(id)arg2 ;
-(void).cxx_destruct;
@end

