/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PUImageViewExtraction : NSObject {

	BOOL __cancelled;

}

@property (setter=_setCancelled:,getter=_isCancelled) BOOL _cancelled;              //@synthesize _cancelled=__cancelled - In the implementation block
-(BOOL)_isCancelled;
-(void)cancel;
-(void)_setCancelled:(BOOL)arg1 ;
@end

