/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <PhotosUI/PhotosUI-Structs.h>
@interface PUMapAnnotationAnimationInfo : NSObject {

	BOOL _remove;
	id _annotation;
	id _destinationAnnotation;
	int _fadeType;
	id _annotationForCountSwap;
	int _reason;
	SCD_Struct_PU9 _sourceCoordinate;
	SCD_Struct_PU9 _destinationCoordinate;

}

@property (nonatomic,readonly) id annotation;                                     //@synthesize annotation=_annotation - In the implementation block
@property (nonatomic,readonly) id destinationAnnotation;                          //@synthesize destinationAnnotation=_destinationAnnotation - In the implementation block
@property (nonatomic,readonly) SCD_Struct_PU9 sourceCoordinate;                   //@synthesize sourceCoordinate=_sourceCoordinate - In the implementation block
@property (nonatomic,readonly) SCD_Struct_PU9 destinationCoordinate;              //@synthesize destinationCoordinate=_destinationCoordinate - In the implementation block
@property (nonatomic,readonly) int fadeType;                                      //@synthesize fadeType=_fadeType - In the implementation block
@property (nonatomic,readonly) BOOL remove;                                       //@synthesize remove=_remove - In the implementation block
@property (nonatomic,readonly) id annotationForCountSwap;                         //@synthesize annotationForCountSwap=_annotationForCountSwap - In the implementation block
@property (nonatomic,readonly) int reason;                                        //@synthesize reason=_reason - In the implementation block
-(BOOL)remove;
-(id)annotation;
-(int)reason;
-(id)initWithAnnotation:(id)arg1 destinationAnnotation:(id)arg2 sourceCoordinate:(SCD_Struct_PU9)arg3 destinationCoordinate:(SCD_Struct_PU9)arg4 fadeType:(int)arg5 remove:(BOOL)arg6 annotationForCountSwap:(id)arg7 reason:(int)arg8 ;
-(id)destinationAnnotation;
-(SCD_Struct_PU9)sourceCoordinate;
-(SCD_Struct_PU9)destinationCoordinate;
-(int)fadeType;
-(id)annotationForCountSwap;
-(void).cxx_destruct;
@end

