/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <PhotosUI/PhotosUI-Structs.h>
@interface PUPhotosPanoramaViewControllerSpec : NSObject
-(unsigned)supportedInterfaceOrientations;
-(CGFloat)sectionHeaderHeight;
-(id)gridSpec;
-(int)thumbnailImageFormat;
-(int)cellFillMode;
-(CGFloat)globalFooterHeight;
-(id)photoBrowserSpec;
-(void)configureCollectionViewGridLayout:(id)arg1 ;
-(CGSize)itemSizeForOrientation:(int)arg1 ;
-(int)fastThumbnailImageFormat;
@end

