/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <PhotosUI/PhotosUI-Structs.h>
@class PUPhotosPickerViewControllerSpec, PUAlbumPickerViewControllerSpec;

@interface PUPhotosGridViewControllerSpec : NSObject {

	BOOL _canDisplayOptionsInPopover;
	BOOL _canDisplaySlideshowButton;
	BOOL _canDisplayEditActionsInNavigationBar;
	BOOL _usesStackPopTransition;
	PUPhotosPickerViewControllerSpec* _photosPickerViewControllerSpec;
	PUAlbumPickerViewControllerSpec* _albumPickerViewControllerSpec;
	CGSize _baseInterItemSpacing;

}

@property (nonatomic,readonly) CGSize contentSizeForViewInPopover; 
@property (nonatomic,readonly) float globalFooterHeight; 
@property (nonatomic,readonly) CGSize baseInterItemSpacing;                                                    //@synthesize baseInterItemSpacing=_baseInterItemSpacing - In the implementation block
@property (nonatomic,readonly) int thumbnailImageFormat; 
@property (nonatomic,readonly) int cellFillMode; 
@property (nonatomic,readonly) BOOL canDisplayOptionsInPopover;                                                //@synthesize canDisplayOptionsInPopover=_canDisplayOptionsInPopover - In the implementation block
@property (nonatomic,readonly) BOOL canDisplaySlideshowButton;                                                 //@synthesize canDisplaySlideshowButton=_canDisplaySlideshowButton - In the implementation block
@property (nonatomic,readonly) BOOL shouldPlaceDeleteInCenterToolbarPosition; 
@property (nonatomic,readonly) BOOL canDisplayEditActionsInNavigationBar;                                      //@synthesize canDisplayEditActionsInNavigationBar=_canDisplayEditActionsInNavigationBar - In the implementation block
@property (nonatomic,readonly) BOOL usesStackPopTransition;                                                    //@synthesize usesStackPopTransition=_usesStackPopTransition - In the implementation block
@property (nonatomic,readonly) BOOL displaysAvalancheStacks; 
@property (nonatomic,readonly) PUPhotosPickerViewControllerSpec * photosPickerViewControllerSpec;              //@synthesize photosPickerViewControllerSpec=_photosPickerViewControllerSpec - In the implementation block
@property (nonatomic,readonly) PUAlbumPickerViewControllerSpec * albumPickerViewControllerSpec;                //@synthesize albumPickerViewControllerSpec=_albumPickerViewControllerSpec - In the implementation block
-(unsigned)supportedInterfaceOrientations;
-(CGSize)contentSizeForViewInPopover;
-(int)thumbnailImageFormat;
-(int)cellFillMode;
-(BOOL)shouldPlaceDeleteInCenterToolbarPosition;
-(BOOL)canDisplayEditActionsInNavigationBar;
-(BOOL)canDisplayOptionsInPopover;
-(BOOL)canDisplaySlideshowButton;
-(id)albumPickerViewControllerSpec;
-(void)configureCollectionViewGridLayout:(id)arg1 forWidth:(float)arg2 ;
-(float)globalFooterHeight;
-(BOOL)displaysAvalancheStacks;
-(BOOL)usesStackPopTransition;
-(id)photoBrowserSpec;
-(void)protoSettingsDidChange;
-(CGSize)baseInterItemSpacing;
-(id)photosPickerViewControllerSpec;
-(void).cxx_destruct;
@end

