/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <PhotosUI/PUPhotosSharingGridCell.h>

@class UIView;

@interface PUPhotosZoomingSharingGridCell : PUPhotosSharingGridCell {

	CGRect _defaultBounds;
	CGPoint _badgeViewDefaultCenter;
	unsigned _badgeViewLayoutAnchor;
	UIView* _badgeView;

}
-(void)layoutSubviews;
-(void)setZoomingImage:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 exampleCell:(id)arg2 badgeView:(id)arg3 layoutAnchor:(unsigned)arg4 ;
-(void)setZoomScale:(CGFloat)arg1 translation:(CGPoint)arg2 rotation:(CGFloat)arg3 animated:(BOOL)arg4 completion:(/*^block*/ id)arg5 ;
-(void).cxx_destruct;
@end

