/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:06 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PLAssetContainerList;
@class NSIndexPath;

@interface PUPhotosSharingTransitionContext : NSObject {

	<PLAssetContainerList>* _collections;
	NSIndexPath* _keyAssetIndexPath;

}

@property (nonatomic,retain) <PLAssetContainerList> * collections;              //@synthesize collections=_collections - In the implementation block
@property (nonatomic,retain) NSIndexPath * keyAssetIndexPath;                   //@synthesize keyAssetIndexPath=_keyAssetIndexPath - In the implementation block
-(id)collections;
-(id)keyAssetIndexPath;
-(void)setCollections:(id)arg1 ;
-(void)setKeyAssetIndexPath:(id)arg1 ;
-(void).cxx_destruct;
@end

