/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <CoreFoundation/NSCopying.h>

@class UIColor;

@interface PUPhotoDecoration : NSObject <NSCopying> {

	UIColor* _borderColor;
	CGFloat _borderWidth;
	UIColor* _foregroundColor;

}

@property (nonatomic,copy) UIColor * borderColor;                  //@synthesize borderColor=_borderColor - In the implementation block
@property (assign,nonatomic) CGFloat borderWidth;                    //@synthesize borderWidth=_borderWidth - In the implementation block
@property (nonatomic,copy) UIColor * foregroundColor;              //@synthesize foregroundColor=_foregroundColor - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)copyWithZone:(NSZone)arg1 ;
-(void)setBorderWidth:(CGFloat)arg1 ;
-(void)setBorderColor:(id)arg1 ;
-(CGFloat)borderWidth;
-(id)borderColor;
-(id)foregroundColor;
-(void)setForegroundColor:(id)arg1 ;
-(id)photoDecorationVariantsWithIncreasingBorderBrightness:(int)arg1 ;
-(id)photoDecorationVariantsWithIncreasingAlpha:(int)arg1 ;
-(UIEdgeInsets)overlayInsets;
-(id)overlayImage;
-(BOOL)_displaysBorderForWidth:(CGFloat)arg1 color:(id)arg2 ;
-(void).cxx_destruct;
@end

