/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:06 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PUPhotosGridLayoutHelper : NSObject
+(int)zIndexForItemAtIndexPath:(id)arg1 ;
+(int)zIndexForSupplementaryViewOfKind:(id)arg1 forVisualSection:(int)arg2 supplementaryViewIndex:(int)arg3 ;
+(int)zIndexForFloatingHeaderForVisualSection:(int)arg1 ;
@end

