/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface PUPhotosSharingProgressOverlay : UIView {

	UIView* _progressView;

}

@property (nonatomic,retain) UIView * progressView;              //@synthesize progressView=_progressView - In the implementation block
-(id)statusBarWindow;
-(void)willRemoveSubview:(id)arg1 ;
-(id)initOverlay;
-(void)addProgressView:(id)arg1 atScreenFrame:(CGRect)arg2 ;
-(id)progressView;
-(void)setupOverlay;
-(void)setProgressView:(id)arg1 ;
-(void)tearDownOverlay;
-(id)screenshotImage;
-(id)grayScaleImageFromImage:(id)arg1 ;
-(void).cxx_destruct;
@end

