/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <PhotosUI/PUPhotosGridViewControllerSpec.h>

@interface PUPhotosGridViewControllerPhoneSpec : PUPhotosGridViewControllerSpec
-(unsigned)supportedInterfaceOrientations;
-(int)thumbnailImageFormat;
-(int)cellFillMode;
-(BOOL)canDisplayOptionsInPopover;
-(id)albumPickerViewControllerSpec;
-(void)configureCollectionViewGridLayout:(id)arg1 forWidth:(CGFloat)arg2 ;
-(CGFloat)globalFooterHeight;
-(id)photoBrowserSpec;
-(CGSize)baseInterItemSpacing;
-(id)photosPickerViewControllerSpec;
@end

