/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:06 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface PUReviewInstructionalView : UIView {

	UILabel* __instructionalLabel;

}

@property (nonatomic,readonly) UILabel * _instructionalLabel;              //@synthesize _instructionalLabel=__instructionalLabel - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)_commonPUReviewInstructionalViewInitialization;
-(id)_instructionalLabel;
-(void).cxx_destruct;
@end

