/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class PUAlbumListViewControllerSpec, PUAbstractAlbumListViewController, PUZoomableGridViewControllerSpec, PUFeedViewControllerSpec;

@interface PUTabbedLibraryViewControllerSpec : NSObject {

	PUAlbumListViewControllerSpec* _albumListViewControllerSpec;
	PUAbstractAlbumListViewController* _createAlbumListViewController;
	PUAbstractAlbumListViewController* _createSharedAlbumListViewController;
	PUZoomableGridViewControllerSpec* _zoomableGridViewControllerSpec;
	PUFeedViewControllerSpec* _feedViewControllerSpec;

}

@property (nonatomic,readonly) PUAlbumListViewControllerSpec * albumListViewControllerSpec;                          //@synthesize albumListViewControllerSpec=_albumListViewControllerSpec - In the implementation block
@property (nonatomic,readonly) PUAbstractAlbumListViewController * createAlbumListViewController;                    //@synthesize createAlbumListViewController=_createAlbumListViewController - In the implementation block
@property (nonatomic,readonly) PUAbstractAlbumListViewController * createSharedAlbumListViewController;              //@synthesize createSharedAlbumListViewController=_createSharedAlbumListViewController - In the implementation block
@property (nonatomic,readonly) PUZoomableGridViewControllerSpec * zoomableGridViewControllerSpec;                    //@synthesize zoomableGridViewControllerSpec=_zoomableGridViewControllerSpec - In the implementation block
@property (nonatomic,readonly) PUFeedViewControllerSpec * feedViewControllerSpec;                                    //@synthesize feedViewControllerSpec=_feedViewControllerSpec - In the implementation block
-(id)feedViewControllerSpec;
-(id)albumListViewControllerSpec;
-(id)zoomableGridViewControllerSpec;
-(id)createAlbumListViewController;
-(id)createSharedAlbumListViewController;
-(void).cxx_destruct;
@end

