/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:06 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface PUTiledLayoutGeneratorScanState : NSObject {

	BOOL _scannedBatchHasCaption;
	int _scanLocation;
	id _scannedBatchID;
	int _scanSpecialSequenceCount;

}

@property (assign,nonatomic) int scanLocation;                          //@synthesize scanLocation=_scanLocation - In the implementation block
@property (nonatomic,retain) id scannedBatchID;                         //@synthesize scannedBatchID=_scannedBatchID - In the implementation block
@property (assign,nonatomic) BOOL scannedBatchHasCaption;               //@synthesize scannedBatchHasCaption=_scannedBatchHasCaption - In the implementation block
@property (assign,nonatomic) int scanSpecialSequenceCount;              //@synthesize scanSpecialSequenceCount=_scanSpecialSequenceCount - In the implementation block
-(void)setScanLocation:(int)arg1 ;
-(int)scanLocation;
-(void)setScannedBatchID:(id)arg1 ;
-(void)setScannedBatchHasCaption:(BOOL)arg1 ;
-(id)scannedBatchID;
-(BOOL)scannedBatchHasCaption;
-(int)scanSpecialSequenceCount;
-(void)setScanSpecialSequenceCount:(int)arg1 ;
-(void).cxx_destruct;
@end

