/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <UIKit/UIViewControllerAnimatedTransitioning.h>

@protocol UIViewControllerContextTransitioning;
@class UIPercentDrivenInteractiveTransition;

@interface PUViewControllerTransition : NSObject <UIViewControllerAnimatedTransitioning> {

	double _duration;
	<UIViewControllerContextTransitioning>* _transitionContext;
	UIPercentDrivenInteractiveTransition* _interactiveTransition;
	BOOL _interactive;
	CGFloat _interactiveProgress;

}

@property (nonatomic,readonly) double duration;                                                      //@synthesize duration=_duration - In the implementation block
@property (assign,getter=isInteractive,nonatomic) BOOL interactive;                                  //@synthesize interactive=_interactive - In the implementation block
@property (assign,setter=_setInteractiveProgress:,nonatomic) CGFloat interactiveProgress;              //@synthesize interactiveProgress=_interactiveProgress - In the implementation block
+(id)interactionControllerForAnimationController:(id)arg1 ;
-(id)containerView;
-(double)transitionDuration:(id)arg1 ;
-(BOOL)isInteractive;
-(void)completeTransition:(BOOL)arg1 ;
-(void)animateTransition:(id)arg1 ;
-(void)animationEnded:(BOOL)arg1 ;
-(id)transitionContext;
-(void)cancelInteractiveTransition;
-(void)finishInteractiveTransition;
-(double)duration;
-(id)fromViewController;
-(id)toViewController;
-(CGRect)finalToViewFrame;
-(id)interactiveTransition;
-(void)setInteractive:(BOOL)arg1 ;
-(void)updateInteractiveTransitionProgress:(CGFloat)arg1 ;
-(void)_setInteractiveProgress:(CGFloat)arg1 ;
-(id)_newInteractiveTransition;
-(id)initWithDuration:(double)arg1 ;
-(CGRect)initialFromViewFrame;
-(CGRect)initialToViewFrame;
-(CGRect)finalFromViewFrame;
-(CGFloat)interactiveProgress;
-(void).cxx_destruct;
@end

