/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <CoreFoundation/NSCopying.h>

@class UIColor, UIImage;

@interface PUViewDecoration : NSObject <NSCopying> {

	UIColor* _shadowColor;
	CGFloat _shadowRadius;
	UIColor* _borderColor;
	CGFloat _borderWidth;
	UIColor* _edgeColor;
	CGSize _shadowOffset;

}

@property (nonatomic,retain) UIColor * shadowColor;                     //@synthesize shadowColor=_shadowColor - In the implementation block
@property (assign,nonatomic) CGFloat shadowRadius;                        //@synthesize shadowRadius=_shadowRadius - In the implementation block
@property (assign,nonatomic) CGSize shadowOffset;                       //@synthesize shadowOffset=_shadowOffset - In the implementation block
@property (nonatomic,retain) UIColor * borderColor;                     //@synthesize borderColor=_borderColor - In the implementation block
@property (assign,nonatomic) CGFloat borderWidth;                         //@synthesize borderWidth=_borderWidth - In the implementation block
@property (nonatomic,retain) UIColor * edgeColor;                       //@synthesize edgeColor=_edgeColor - In the implementation block
@property (nonatomic,readonly) UIEdgeInsets overlayInsets; 
@property (nonatomic,readonly) UIImage * overlayImage; 
-(id)copyWithZone:(NSZone)arg1 ;
-(void)setShadowColor:(id)arg1 ;
-(void)setShadowOffset:(CGSize)arg1 ;
-(CGSize)shadowOffset;
-(id)shadowColor;
-(void)setBorderWidth:(CGFloat)arg1 ;
-(void)setBorderColor:(id)arg1 ;
-(CGFloat)borderWidth;
-(id)borderColor;
-(void)setShadowRadius:(CGFloat)arg1 ;
-(CGFloat)shadowRadius;
-(id)edgeColor;
-(void)setEdgeColor:(id)arg1 ;
-(BOOL)_displayShadow;
-(BOOL)_displayBorder;
-(BOOL)_displayEdges;
-(id)decorationVariantsWithDecreasingBrightness:(int)arg1 ;
-(UIEdgeInsets)overlayInsets;
-(id)overlayImage;
-(void).cxx_destruct;
@end

