/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:05 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotosUI/PhotosUI-Structs.h>
#import <PhotosUI/PUZoomableGridViewControllerSpec.h>

@interface PUZoomableGridViewControllerPhoneSpec : PUZoomableGridViewControllerSpec
-(CGSize)magnifiedImageSize;
-(UIEdgeInsets)magnifiedDragEdgeInsets;
-(void)configureFullMomentsLevelGridLayout:(id)arg1 forWidth:(CGFloat)arg2 ;
-(int)fullMomentsSectionHeaderStyle;
-(UIEdgeInsets)fullMomentsLevelSectionHeaderContentInset;
-(UIEdgeInsets)fullMomentsLevelSectionHeaderHighlightInset;
-(int)fullMomentsLevelThumbnailFormat;
-(int)yearsLevelThumbnailFormat;
-(void)configureYearsLevelGridLayout:(id)arg1 forWidth:(CGFloat)arg2 ;
-(int)yearsSectionHeaderStyle;
-(UIEdgeInsets)yearsLevelSectionHeaderContentInset;
-(UIEdgeInsets)yearsLevelSectionHeaderHighlightInset;
-(int)collectionsLevelThumbnailFormat;
-(void)configureCollectionsLevelGridLayout:(id)arg1 forWidth:(CGFloat)arg2 ;
-(int)collectionsSectionHeaderStyle;
-(UIEdgeInsets)collectionsLevelSectionHeaderContentInset;
-(UIEdgeInsets)collectionsLevelSectionHeaderHighlightInset;
-(id)newGridSpec;
-(id)mapViewControllerSpec;
-(BOOL)canDisplayMultipleRightBarButtonItems;
-(int)magnifiedImageFormat;
-(CGFloat)magnifiedYOffset;
@end

