/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:55:04 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIActionSheetDelegate <NSObject>
@optional
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)actionSheetCancel:(id)arg1;
-(void)willPresentActionSheet:(id)arg1;
-(void)didPresentActionSheet:(id)arg1;
-(void)actionSheet:(id)arg1 willDismissWithButtonIndex:(int)arg2;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
@end

