/*
* This header is generated by classdump-dyld 0.2
* on Sunday, December 29, 2013 at 10:54:59 PM India Standard Time
* Operating System: Version 7.0.4 (Build 11B554a)
* Image Source: /System/Library/PrivateFrameworks/PhotoBoothEffects.framework/PhotoBoothEffects
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <PhotoBoothEffects/PhotoBoothEffects-Structs.h>
#import <PhotoBoothEffects/PBFilter.h>

@interface PBMirrorFilter : PBFilter {

	CGFloat lastInputX;
	CGFloat lastInputY;
	CGFloat lastInputAngle;
	bool firstTime;
	CGFloat inputOrientation;
	CGPoint inputPoint;

}

@property (assign) CGPoint inputPoint; 
@property (assign) CGFloat inputOrientation; 
-(void)setDefaults;
-(CGPoint)inputPoint;
-(void)setInputPoint:(CGPoint)arg1 ;
-(id)ciFilterName;
-(BOOL)needsWrapMirror;
-(void)applyParametersToCIFilter:(BOOL)arg1 extent:(CGRect)arg2 ;
-(void)setInputOrientation:(CGFloat)arg1 ;
-(CGFloat)inputOrientation;
@end

